"""Generate SOL_substitute_effects.txt — per-market tier assignment effects."""
from __future__ import annotations

import sys
from typing import List

from ._data import (
    SHORTAGE_TIERS, SURPLUS_TIERS, ALL_TIER_SUFFIXES,
    COMPAT_GOODS, INDICATOR_GROUPS,
    ALL_GOODS, GOOD_TO_IND_GROUP,
    SCARCITY_SCORE_MAX_OFFSET,
    _good_list_name,
)

EFFECTS_HEADER = """\
# @AUTOGENERATED by scripts/gen_scarcity.py — do not edit; run script to regenerate.
### ============================================================
### SECTION: Substitute Goods Scarcity Cache
### ============================================================
# Computes per-market scarcity tier for all pop-demand substitute goods.
#
# 6 tiers (3 shortage + 3 surplus):
#   Severe     (> 2.30× default): weight ×0.25   list: SOL_<good>_severe_markets
#   Moderate   (> 1.70× default): weight ×0.50   list: SOL_<good>_moderate_markets
#   Mild       (> 1.30× default): weight ×0.75   list: SOL_<good>_mild_markets
#   Normal     (0.85×–1.30×):      weight ×1.00   (no list)
#   Affordable (< 0.85× default): weight ×1.25   list: SOL_<good>_affordable_markets
#   Cheap      (< 0.65× default): weight ×1.50   list: SOL_<good>_cheap_markets
#   Very Cheap (< 0.40× default): weight ×2.00   list: SOL_<good>_vcheap_markets
#
# Each market belongs to at most one tier list per good.
# No hysteresis — yearly update rate damps oscillation adequately.
#
# Storage: 6 global variable lists per good (56 goods × 6 = 336 lists).
# Pop demand checks: location.market ?= { is_target_in_global_variable_list = { ... } }
#
# AUTO-GENERATED by scripts/gen_scarcity.py — do not edit by hand.
"""


def _gen_good_effects(good: str) -> str:
    """Generate the per-market tier assignment block for one good."""
    lines: List[str] = []
    is_compat = good in COMPAT_GOODS
    indent = "        "  # 8 spaces (inside every_market_in_world)

    lines.append(f"{indent}# {good}")

    # Step 1: Remove from all tier lists
    for suffix in ALL_TIER_SUFFIXES:
        lst = _good_list_name(good, suffix)
        if is_compat:
            lines += [
                f"{indent}if = {{",
                f"{indent}    limit = {{",
                f"{indent}        sol_pp_victuals_compat_is_on = yes",
                f"{indent}        has_global_variable_list = {lst}",
                f"{indent}        is_target_in_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}    }}",
                f"{indent}    remove_list_global_variable = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]
        else:
            lines += [
                f"{indent}if = {{",
                f"{indent}    limit = {{",
                f"{indent}        has_global_variable_list = {lst}",
                f"{indent}        is_target_in_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}    }}",
                f"{indent}    remove_list_global_variable = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]

    # Step 2: Add to correct tier via if/else_if chain
    first = True
    for suffix, threshold, _weight, _desc in SHORTAGE_TIERS:
        lst = _good_list_name(good, suffix)
        kw = "if" if first else "else_if"
        first = False
        price_cmp = f'"market_price(goods:{good})"'
        def_price = f'"default_price(goods:{good})"'
        if is_compat:
            lines += [
                f"{indent}{kw} = {{",
                f"{indent}    limit = {{",
                f"{indent}        sol_pp_victuals_compat_is_on = yes",
                f"{indent}        {price_cmp} > {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]
        else:
            lines += [
                f"{indent}{kw} = {{",
                f"{indent}    limit = {{",
                f"{indent}        {price_cmp} > {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]

    for suffix, threshold, _weight, _desc in SURPLUS_TIERS:
        lst = _good_list_name(good, suffix)
        price_cmp = f'"market_price(goods:{good})"'
        def_price = f'"default_price(goods:{good})"'
        if is_compat:
            lines += [
                f"{indent}else_if = {{",
                f"{indent}    limit = {{",
                f"{indent}        sol_pp_victuals_compat_is_on = yes",
                f"{indent}        {price_cmp} < {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]
        else:
            lines += [
                f"{indent}else_if = {{",
                f"{indent}    limit = {{",
                f"{indent}        {price_cmp} < {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]

    return "\n".join(lines)


_SCARCITY_SCORE_HEADER = """\
# @AUTOGENERATED by scripts/gen_scarcity.py — do not edit; run script to regenerate.
# Defines SOL_compute_scarcity_score (location scope).
# Checks all {n} goods across 20 groups; per-good tier deltas scaled so
# sol_market_scarcity_adj = 1 + sol_scarcity_score stays in [{lo:.2f}, {hi:.2f}].
"""

_BASE_TIER_DELTAS: List[tuple] = [
    ("severe",     -0.04),
    ("moderate",   -0.025),
    ("mild",       -0.01),
    ("affordable",  0.01),
    ("cheap",       0.025),
    ("vcheap",      0.04),
]


def gen_scarcity_score_file() -> str:
    """Generate z_SOL_scarcity_score.txt — SOL_compute_scarcity_score scripted effect."""
    n = len(ALL_GOODS)
    scale = SCARCITY_SCORE_MAX_OFFSET / (n * 0.04)
    tier_deltas = [(s, round(d * scale, 5)) for s, d in _BASE_TIER_DELTAS]

    ind = "\t"
    lines: List[str] = []
    lines.append(_SCARCITY_SCORE_HEADER.format(
        n=n,
        lo=1 - SCARCITY_SCORE_MAX_OFFSET,
        hi=1 + SCARCITY_SCORE_MAX_OFFSET,
    ))
    lines.append("SOL_compute_scarcity_score = {")
    lines.append(f"{ind}set_variable = {{ name = sol_scarcity_score  value = 0 }}")

    prev_group = None
    for good in ALL_GOODS:
        grp = GOOD_TO_IND_GROUP[good]
        if grp != prev_group:
            lines.append(f"{ind}# {grp}")
            prev_group = grp
        for suffix, delta in tier_deltas:
            lst = _good_list_name(good, suffix)
            lines.append(
                f"{ind}if = {{ limit = {{ market ?= {{ is_target_in_global_variable_list = "
                f"{{ name = {lst:<52} target = this }} }} }} "
                f"change_variable = {{ name = sol_scarcity_score  value = {delta:.5f} }} }}"
            )

    lines.append(
        f"{ind}set_variable = {{ name = sol_market_scarcity_adj  "
        f"value = {{ value = 1  add = var:sol_scarcity_score }} }}"
    )
    lines.append("}")
    return "\n".join(lines) + "\n"


def gen_effects_file() -> str:
    body_lines: List[str] = []
    prev_grp = None
    for grp, goods in INDICATOR_GROUPS:
        if grp != prev_grp:
            body_lines.append(f"        # === Group: {grp} ===")
            prev_grp = grp
        for good in goods:
            body_lines.append(_gen_good_effects(good))
            body_lines.append("")

    body = "\n".join(body_lines)
    return (
        EFFECTS_HEADER
        + "\nSOL_update_substitute_scarcity = {\n"
        + "    every_market_in_world = {\n"
        + body
        + "    }\n"
        + "}\n"
    )
