"""Generate SOL_substitute_effects.txt — per-market tier assignment effects."""
from __future__ import annotations

import csv
import sys
from pathlib import Path
from typing import Dict, List

from ._data import (
    SHORTAGE_TIERS, SURPLUS_TIERS, ALL_TIER_SUFFIXES,
    COMPAT_GOODS, INDICATOR_GROUPS,
    ALL_GOODS, GOOD_TO_IND_GROUP, IND_GROUP_SIZE,
    TIER_EXACT_FACTORS,
    ROOT,
    _good_list_name,
)

EFFECTS_HEADER = """\
# @AUTOGENERATED by scripts/gen_scarcity.py — do not edit; run script to regenerate.
### ============================================================
### SECTION: Substitute Goods Scarcity Cache
### ============================================================
# Computes per-market scarcity tier for all pop-demand substitute goods.
#
# 6 tiers (3 shortage + 3 surplus):
#   Severe     (> 2.30× default): weight ×0.25   list: SOL_<good>_severe_markets
#   Moderate   (> 1.70× default): weight ×0.50   list: SOL_<good>_moderate_markets
#   Mild       (> 1.30× default): weight ×0.75   list: SOL_<good>_mild_markets
#   Normal     (0.85×–1.30×):      weight ×1.00   (no list)
#   Affordable (< 0.85× default): weight ×1.25   list: SOL_<good>_affordable_markets
#   Cheap      (< 0.65× default): weight ×1.50   list: SOL_<good>_cheap_markets
#   Very Cheap (< 0.40× default): weight ×2.00   list: SOL_<good>_vcheap_markets
#
# Each market belongs to at most one tier list per good.
# No hysteresis — yearly update rate damps oscillation adequately.
#
# Storage: 6 global variable lists per good (56 goods × 6 = 336 lists).
# Pop demand checks: location.market ?= { is_target_in_global_variable_list = { ... } }
#
# AUTO-GENERATED by scripts/gen_scarcity.py — do not edit by hand.
"""

# Strata order must match alpha_bracket_table.csv row order.
STRATA: List[str] = ["nobles", "clergy", "burghers", "commoners", "tribesmen"]


def _load_alpha_averages() -> Dict[str, Dict[str, float]]:
    """Load alpha_bracket_table.csv and return averaged budget shares per (strata, group)."""
    csv_path = ROOT / "data" / "alpha_bracket_table.csv"
    # Accumulate sum and count per (strata, group)
    totals: Dict[str, Dict[str, float]] = {s: {} for s in STRATA}
    counts: Dict[str, int] = {s: 0 for s in STRATA}
    with csv_path.open(encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        groups_in_csv = [c for c in (reader.fieldnames or [])
                         if c not in ("strata", "bracket", "threshold")]
        for row in reader:
            strata = row["strata"]
            if strata not in totals:
                continue
            counts[strata] += 1
            for grp in groups_in_csv:
                totals[strata][grp] = totals[strata].get(grp, 0.0) + float(row[grp])
    # Compute averages
    result: Dict[str, Dict[str, float]] = {}
    for strata in STRATA:
        n = counts[strata]
        result[strata] = {grp: totals[strata].get(grp, 0.0) / n for grp in groups_in_csv}
    return result


def _gen_good_effects(good: str) -> str:
    """Generate the per-market tier assignment block for one good."""
    lines: List[str] = []
    is_compat = good in COMPAT_GOODS
    indent = "        "  # 8 spaces (inside every_market_in_world)

    lines.append(f"{indent}# {good}")

    # Step 1: Remove from all tier lists
    for suffix in ALL_TIER_SUFFIXES:
        lst = _good_list_name(good, suffix)
        if is_compat:
            lines += [
                f"{indent}if = {{",
                f"{indent}    limit = {{",
                f"{indent}        sol_pp_victuals_compat_is_on = yes",
                f"{indent}        has_global_variable_list = {lst}",
                f"{indent}        is_target_in_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}    }}",
                f"{indent}    remove_list_global_variable = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]
        else:
            lines += [
                f"{indent}if = {{",
                f"{indent}    limit = {{",
                f"{indent}        has_global_variable_list = {lst}",
                f"{indent}        is_target_in_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}    }}",
                f"{indent}    remove_list_global_variable = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]

    # Step 2: Add to correct tier via if/else_if chain
    first = True
    for suffix, threshold, _weight, _desc in SHORTAGE_TIERS:
        lst = _good_list_name(good, suffix)
        kw = "if" if first else "else_if"
        first = False
        price_cmp = f'"market_price(goods:{good})"'
        def_price = f'"default_price(goods:{good})"'
        if is_compat:
            lines += [
                f"{indent}{kw} = {{",
                f"{indent}    limit = {{",
                f"{indent}        sol_pp_victuals_compat_is_on = yes",
                f"{indent}        {price_cmp} > {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]
        else:
            lines += [
                f"{indent}{kw} = {{",
                f"{indent}    limit = {{",
                f"{indent}        {price_cmp} > {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]

    for suffix, threshold, _weight, _desc in SURPLUS_TIERS:
        lst = _good_list_name(good, suffix)
        price_cmp = f'"market_price(goods:{good})"'
        def_price = f'"default_price(goods:{good})"'
        if is_compat:
            lines += [
                f"{indent}else_if = {{",
                f"{indent}    limit = {{",
                f"{indent}        sol_pp_victuals_compat_is_on = yes",
                f"{indent}        {price_cmp} < {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]
        else:
            lines += [
                f"{indent}else_if = {{",
                f"{indent}    limit = {{",
                f"{indent}        {price_cmp} < {{",
                f"{indent}            value = {def_price}",
                f"{indent}            multiply = {threshold}",
                f"{indent}        }}",
                f"{indent}    }}",
                f"{indent}    add_to_global_variable_list = {{ name = {lst} target = this }}",
                f"{indent}}}",
            ]

    return "\n".join(lines)


_SCARCITY_SCORE_HEADER = """\
# @AUTOGENERATED by scripts/gen_scarcity.py — do not edit; run script to regenerate.
# Defines SOL_compute_scarcity_score_<strata> (location scope) for 5 strata.
#
# Per-stratum budget-share-weighted correction.
# Delta formula: -(1 - 1/P_tier) × alpha_avg[strata][group] / n_goods_in_group
# where alpha_avg = mean budget share across all 4 income brackets.
#
# Natural bounds (all goods in a single tier simultaneously):
#   shortage max: -(1 - 1/2.30) = -0.5652  →  adj = 0.435 (never negative)
#   surplus  max: +(1/0.40 - 1) = +1.5000  →  adj = 2.500
# No hard cap applied; demand scales have min = 0 as safety floor.
"""


def gen_scarcity_score_file() -> str:
    """Generate z_SOL_scarcity_score.txt — 5 per-stratum SOL_compute_scarcity_score_* effects."""
    alpha = _load_alpha_averages()
    ind = "\t"
    all_tiers = (
        [(s, t, _w, _d) for s, t, _w, _d in SHORTAGE_TIERS] +
        [(s, t, _w, _d) for s, t, _w, _d in SURPLUS_TIERS]
    )
    # Build lookup: suffix → exact factor
    tier_factors: Dict[str, float] = {suffix: TIER_EXACT_FACTORS[suffix]
                                       for suffix, *_ in all_tiers}

    lines: List[str] = [_SCARCITY_SCORE_HEADER]

    for strata in STRATA:
        score_var = f"sol_scarcity_score_{strata}"
        adj_var   = f"sol_market_scarcity_adj_{strata}"
        effect    = f"SOL_compute_scarcity_score_{strata}"

        lines.append(f"{effect} = {{")
        lines.append(f"{ind}set_variable = {{ name = {score_var}  value = 0 }}")

        prev_group = None
        for good in ALL_GOODS:
            grp    = GOOD_TO_IND_GROUP[good]
            n_grp  = IND_GROUP_SIZE[grp]
            alpha_s_g = alpha[strata].get(grp, 0.0)

            if grp != prev_group:
                lines.append(f"{ind}# {grp}")
                prev_group = grp

            for suffix, *_ in all_tiers:
                raw_delta = tier_factors[suffix] * alpha_s_g / n_grp
                delta = round(raw_delta, 5)
                if delta == 0.0:
                    continue  # skip zero-weight goods (e.g. commoners/luxury_goods)
                lst = _good_list_name(good, suffix)
                lines.append(
                    f"{ind}if = {{ limit = {{ market ?= {{ is_target_in_global_variable_list = "
                    f"{{ name = {lst:<52} target = this }} }} }} "
                    f"change_variable = {{ name = {score_var}  add = {delta:.5f} }} }}"
                )

        lines.append(
            f"{ind}set_variable = {{ name = {adj_var}  "
            f"value = {{ value = 1  add = var:{score_var} }} }}"
        )
        lines.append("}")
        lines.append("")

    return "\n".join(lines) + "\n"


def gen_effects_file() -> str:
    body_lines: List[str] = []
    prev_grp = None
    for grp, goods in INDICATOR_GROUPS:
        if grp != prev_grp:
            body_lines.append(f"        # === Group: {grp} ===")
            prev_grp = grp
        for good in goods:
            body_lines.append(_gen_good_effects(good))
            body_lines.append("")

    body = "\n".join(body_lines)
    return (
        EFFECTS_HEADER
        + "\nSOL_update_substitute_scarcity = {\n"
        + "    every_market_in_world = {\n"
        + body
        + "    }\n"
        + "}\n"
    )
