"""Generate z_SOL_goods_tooltip_override.gui — full GUI override with ratio templates."""
from __future__ import annotations

from pathlib import Path
from typing import List

from ._data import (
    DEMAND_GROUPS, ALL_GOODS, GOODS_DIR,
)

GUI_STATIC_HEADER = """\
# @AUTOGENERATED by scripts/gen_scarcity.py — do not edit; run script to regenerate.
# ============================================================
# z_SOL_goods_tooltip_override.gui
# Overrides 4 vanilla goods tooltip templates to inject substitute group info.
#
# Templates overridden:
#   Goods_tooltip                — generic goods tooltip (Goods scope)
#   SpecificGoodsMarket_tooltip  — market-context goods tooltip (Goods scope)
#   goods_market_price_tooltip   — market price chart tooltip (GoodsMarketEntry scope)
#   GoodsPriceOnMarket_tooltip   — price-on-market tooltip (GoodsPriceOnMarketWrap scope)
#
# All vanilla blockoverrides are replicated unchanged.
# Adds blockoverride "extra_tooltip_content" → SOL_goods_substitute_group_block
# Non-Goods scopes use widget { datacontext = "[X.GetGoods]" } to switch to Goods scope.
#
# AUTO-GENERATED (scaffold + body) by scripts/gen_scarcity.py — do not edit by hand.
# ============================================================

template Goods_tooltip {
\tContextualTooltipType = {
\t\tblockoverride "title_icon" {
\t\t\tbutton = {
\t\t\t\tusing = tooltip_title_icon_size
\t\t\t\ttexture = "[GetGoodsIcon(Goods.Self)]"
\t\t\t\tonclick = "[ShowGoods(Goods.Self)]"
\t\t\t\ttooltipwidget = {
\t\t\t\t\tLeftClickButtonTooltip = {
\t\t\t\t\t\tblockoverride "onclick_text" { text = "OPEN_GOOD_PANEL" }
\t\t\t\t\t}
\t\t\t\t}
\t\t\t}
\t\t}

\t\tblockoverride "title_text" {
\t\t\ttext = "[Goods.GetNameWithNoTooltip]"
\t\t}

\t\tblockoverride "concept_link" {
\t\t\ttext = [goods|e]
\t\t}

\t\tblockoverride "title_button" {
\t\t\tcustom_map_mode_button = {
\t\t\t\tdatacontext = "[GetMapMode('reactive_trade_good')]"

\t\t\t\tblockoverride "on_action" {
\t\t\t\t\ton_action = "[ShowGoodsReactive(Goods.Self)]"
\t\t\t\t}

\t\t\t\tblockoverride "icon" {
\t\t\t\t\ttexture = "[GetGoodsIcon(Goods.Self)]"
\t\t\t\t}
\t\t\t}
\t\t}

\t\tblockoverride "tooltip_content" {
\t\t\tusing = goods_details

\t\t\tTooltipFlavorTextBlock = {
\t\t\t\tblockoverride "text" {
\t\t\t\t\ttext = "[Goods.GetFlavorText]"
\t\t\t\t}
\t\t\t}
\t\t}

\t\t# ── Substitute group info ─────────────────────────────────────
\t\tblockoverride "extra_tooltip_content" {
\t\t\tusing = SOL_goods_substitute_group_block
\t\t}
\t}
}

template SOL_goods_substitute_group_block {
\t# One widget per good — exactly one visible at a time.
\t# Structure per good: vbox (visible=X, expanding) { title, group subtitle, k rows }
\t# Each hbox row is expanding so text_single(expanding) gets space (not compressed to 0).
\t# vbox (not widget) used as wrapper so sizing propagates to TooltipContentSection parent.
\t# Row format: hbox { "1单位NAME" [ICON] "可替代 N单位NAME" [ICON] }
\t# Icon paths: gfx/interface/icons/trade_goods/icon_goods_<key>.dds
\t# AUTO-GENERATED — do not edit by hand.
"""

GUI_STATIC_FOOTER = """\
}

template SpecificGoodsMarket_tooltip {
\tContextualTooltipType = {

\t\tblockoverride "title_icon" {
\t\t\tbutton = {
\t\t\t\tusing = tooltip_title_icon_size
\t\t\t\ttexture = "[GetGoodsIcon(Goods.Self)]"
\t\t\t\ttooltipwidget = {
\t\t\t\t\tusing = Goods_tooltip
\t\t\t\t}
\t\t\t\taction_tooltip = {
\t\t\t\t\tclick_type = left
\t\t\t\t\tclick_mode = single
\t\t\t\t\ttitle = "OPEN_GOOD_PANEL"
\t\t\t\t\ton_action = "[ShowGoods(Goods.Self)]"
\t\t\t\t}
\t\t\t}
\t\t}

\t\tblockoverride "title_text" {
\t\t\ttext = "[Goods.GetNameWithNoTooltip]"
\t\t}

\t\tblockoverride "concept_link" {
\t\t\ttext = [goods|E]
\t\t}

\t\tblockoverride "title_button" {
\t\t\tcustom_map_mode_button = {
\t\t\t\tdatacontext = "[GetMapMode('reactive_trade_good')]"

\t\t\t\tblockoverride "on_action" {
\t\t\t\t\ton_action = "[ShowGoodsReactive(Goods.Self)]"
\t\t\t\t}

\t\t\t\tblockoverride "icon" {
\t\t\t\t\ttexture = "[GetGoodsIcon(Goods.Self)]"
\t\t\t\t}
\t\t\t}
\t\t}

\t\tblockoverride "tooltip_content" {
\t\t\tusing = goods_details
\t\t\tdatacontext = "[Market.GetMarketEntry(Goods.Self)]"

\t\t\tusing = SpecificGoodsFromMarketContent
\t\t\tblockoverride "data_from" {
\t\t\t\tdatacontext = "[Market]"
\t\t\t}

\t\t\tblock "good_details_extra_info" {}

\t\t\tTooltipFlavorTextBlock = {
\t\t\t\ttextcontext = "[Goods.GetFlavorText]"
\t\t\t}
\t\t}

\t\t# ── Substitute group info ─────────────────────────────────────
\t\tblockoverride "extra_tooltip_content" {
\t\t\tusing = SOL_goods_substitute_group_block
\t\t}
\t}
}

template goods_market_price_tooltip {
\tContextualTooltipType = {
\t\tblockoverride "title_icon" {
\t\t\tbutton = {
\t\t\t\tdatacontext = "[GoodsMarketEntry.GetGoods]"
\t\t\t\tusing = tooltip_title_icon_size
\t\t\t\ttexture = "[GetGoodsIcon(GoodsMarketEntry.GetGoods)]"
\t\t\t\ttooltipwidget = {
\t\t\t\t\tusing = Goods_tooltip
\t\t\t\t}
\t\t\t\taction_tooltip = {
\t\t\t\t\tclick_type = left
\t\t\t\t\tclick_mode = single
\t\t\t\t\ttitle = "OPEN_GOOD_PANEL"
\t\t\t\t\ton_action = "[ShowGoods(GoodsMarketEntry.GetGoods)]"
\t\t\t\t}
\t\t\t}
\t\t}

\t\tblockoverride "title_text" {
\t\t\ttext = "GOODS_MARKET_ENTRY_TITLE"
\t\t}

\t\tblockoverride "concept_link" {
\t\t\ttext = "[market_price|e]"
\t\t}

\t\tblockoverride "tooltip_content" {
\t\t\tusing = goods_market_details
\t\t}

\t\t# ── Substitute group info (GoodsMarketEntry scope → Goods via datacontext) ────
\t\tblockoverride "extra_tooltip_content" {
\t\t\twidget = {
\t\t\t\tdatacontext = "[GoodsMarketEntry.GetGoods]"
\t\t\t\tusing = SOL_goods_substitute_group_block
\t\t\t}
\t\t}
\t}
}

template GoodsPriceOnMarket_tooltip {
\tContextualTooltipType = {
\t\tblockoverride "title_icon_texture" {
\t\t\ttexture = "[GetGoodsIcon(GoodsPriceOnMarketWrap.GetGoods)]"
\t\t}

\t\tblockoverride "title_text" {
\t\t\ttext = "[GoodsPriceOnMarketWrap.GetName]"
\t\t}

\t\tblockoverride "concept_link" {
\t\t\ttext = "[market_price|e]"
\t\t}

\t\tblockoverride "tooltip_content" {
\t\t\tdatacontext = "[GoodsPriceOnMarketWrap.GetGoodsMarketEntry]"
\t\t\tdatacontext = "[GoodsPriceOnMarketWrap.GetMarket]"
\t\t\tusing = goods_market_details
\t\t}

\t\t# ── Substitute group info (GoodsPriceOnMarketWrap scope → Goods via datacontext) ────
\t\tblockoverride "extra_tooltip_content" {
\t\t\twidget = {
\t\t\t\tdatacontext = "[GoodsPriceOnMarketWrap.GetGoods]"
\t\t\t\tusing = SOL_goods_substitute_group_block
\t\t\t}
\t\t}
\t}
}
"""


def _good_icon(good: str) -> str:
    return f"gfx/interface/icons/trade_goods/icon_goods_{good}.dds"


def _parse_goods_prices() -> dict:
    prices: dict = {}
    import re
    for fname in sorted(GOODS_DIR.glob("*.txt")):
        if fname.name == "readme.txt":
            continue
        text = fname.read_text(encoding="utf-8")
        current_good = None
        depth = 0
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            opens = line.count("{")
            closes = line.count("}")
            if depth == 0 and opens > 0:
                m = re.match(r'^(\w+)\s*=\s*\{', stripped)
                if m:
                    current_good = m.group(1)
                    prices.setdefault(current_good, 1.0)
            elif current_good and depth == 1:
                m = re.match(r'default_market_price\s*=\s*([\d.]+)', stripped)
                if m:
                    prices[current_good] = float(m.group(1))
            depth += opens - closes
            if depth <= 0:
                depth = 0
                current_good = None
    return prices


def gen_group_ratio_templates(prices: dict) -> str:
    lines: List[str] = [
        "# ============================================================",
        "#  Per-good static ratio templates (SOL_subst_ratios_{good})",
        "#  Each shows only the outgoing ratios for that specific good.",
        "#  Scope-agnostic: static text + icons, no ScriptValue calls.",
        "#  AUTO-GENERATED by scripts/gen_scarcity.py — do not edit by hand.",
        "# ============================================================",
        "",
    ]
    for grp, members in DEMAND_GROUPS:
        grp_title_key = f"SOL_TT_{grp.upper()}_TITLE"
        for a in members:
            a_icon = _good_icon(a)
            lines += [
                f"template SOL_subst_ratios_{a} {{",
                f"\tvbox = {{",
                f"\t\tlayoutpolicy_horizontal = expanding",
                f"\t\tspacing = 3",
                f"\t\tmargin = {{ 4 4 }}",
                f"\t\tusing = bg_listbase_template",
                f'\t\ttext_single = {{ layoutpolicy_horizontal = expanding text = "{grp_title_key}" }}',
            ]
            for b in members:
                if b == a:
                    continue
                b_icon = _good_icon(b)
                lines += [
                    f"\t\thbox = {{",
                    f"\t\t\tlayoutpolicy_horizontal = expanding",
                    f"\t\t\tspacing = 6",
                    f"\t\t\thbox = {{",
                    f'\t\t\t\ttext_single = {{ text = "SOL_SUBST_FROM_{a}" }}',
                    f'\t\t\t\ticon = {{ size = {{ 20 20 }} texture = "{a_icon}" }}',
                    f"\t\t\t}}",
                    f"\t\t\thbox = {{",
                    f'\t\t\t\ttext_single = {{ text = "SOL_SUBST_RATIO_{a}_{b}" }}',
                    f'\t\t\t\ticon = {{ size = {{ 20 20 }} texture = "{b_icon}" }}',
                    f"\t\t\t}}",
                    f"\t\t}}",
                ]
            lines += [
                f"\t}}",
                f"}}",
                f"",
            ]
    return "\n".join(lines) + "\n"


def gen_goods_gui_override_file(prices: dict) -> str:
    good_to_groups: dict = {}
    for grp, members in DEMAND_GROUPS:
        for good in members:
            good_to_groups.setdefault(good, []).append((grp, members))

    lines: List[str] = []
    for good in ALL_GOODS:
        if good not in good_to_groups:
            continue
        good_icon = _good_icon(good)
        lines += [
            f"\tvbox = {{",
            f'\t\tvisible = "[EqualTo_string(Goods.GetKey, \'{good}\')]"',
            f"\t\tlayoutpolicy_horizontal = expanding",
            f"\t\tspacing = 6",
            f"\t\tmargin = {{ 4 4 }}",
            f"\t\tusing = bg_listbase_template",
            f'\t\ttext_single = {{ layoutpolicy_horizontal = expanding text = "SOL_SUBST_SECTION_TITLE" }}',
        ]
        lines.append(f"\t\tusing = SOL_subst_ratios_{good}")
        lines += [f"\t}}", ""]

    body = "\n".join(lines)
    return gen_group_ratio_templates(prices) + GUI_STATIC_HEADER + body + GUI_STATIC_FOOTER
