"""Generate SOL_substitute_good_indicators.txt and SOL_substitute_group_indicators.txt."""
from __future__ import annotations

from typing import List, Tuple

from ._data import (
    SHORTAGE_TIERS, SURPLUS_TIERS,
    INDICATOR_GROUPS, COMPAT_GOODS, GOOD_TO_IND_GROUP, IND_GROUP_SIZE,
    DEMAND_GROUPS, DEMAND_GROUP_SIZE,
    ABSENT_SUFFIX,
    _good_list_name,
)

INDICATORS_HEADER = """\
# @AUTOGENERATED by scripts/gen_scarcity.py — do not edit; run script to regenerate.
### ============================================================
### SECTION: Per-Good Scarcity Tier Indicators (GUI tooltip helpers)
### ============================================================
# Per good, this file emits six script values (all evaluated at location scope
# via Location.MakeScope.ScriptValue):
#
#   sol_good_<good>_scarcity_tier  — int 0–3: 0=normal, 1=mild, 2=moderate, 3=severe
#   sol_good_<good>_surplus_tier   — int 0–3: 0=normal, 1=affordable, 2=cheap, 3=very cheap
#   sol_good_<good>_scarce         — binary 1 if any scarcity tier (backward compat)
#   sol_good_<good>_absent         — binary 1 if good is neither produced nor traded in market
#   sol_weight_indicator_<good>    — float 0.25–2.00 (effective weight for display)
#   sol_demand_share_<good>        — float 0–100 (% share within indicator group)
#
# Per indicator group, one sol_<grp>_base_total_weight value is emitted.
#
# AUTO-GENERATED by scripts/gen_scarcity.py — do not edit by hand.
"""

GROUP_INDICATORS_HEADER = """\
# @AUTOGENERATED by scripts/gen_scarcity.py — do not edit; run script to regenerate.
### ============================================================
### SECTION: Substitute Group Scarcity Indicators (GUI helpers)
### ============================================================
# Each value returns 1 if any good in the demand group is currently
# scarce (any shortage tier) at the evaluated location's market.
#
# Used by location_window.gui demography_item blockoverride to drive
# visibility of per-stratum substitute-goods icons in the Population tab.
#
# Scope when evaluated: location (via Location.MakeScope.ScriptValue)
#
# AUTO-GENERATED by scripts/gen_scarcity.py — do not edit by hand.
"""


def _list_check(good: str, suffix: str, scope_prefix: str = "market") -> str:
    lst = _good_list_name(good, suffix)
    return f"{scope_prefix} ?= {{ is_target_in_global_variable_list = {{ name = {lst} target = this }} }}"


def _gen_good_indicators(good: str) -> List[str]:
    is_compat = good in COMPAT_GOODS
    ind_grp = GOOD_TO_IND_GROUP[good]
    lines: List[str] = []

    lines.append(f"sol_good_{good}_scarcity_tier = {{")
    lines.append(f"    value = 0")
    for i, (suffix, _t, _w, _d) in enumerate(SHORTAGE_TIERS):
        kw = "if" if i == 0 else "else_if"
        if is_compat:
            lines += [
                f"    {kw} = {{ limit = {{ sol_pp_victuals_compat_is_on = yes {_list_check(good, suffix)} }} value = {3 - i} }}",
            ]
        else:
            lines.append(f"    {kw} = {{ limit = {{ {_list_check(good, suffix)} }} value = {3 - i} }}")
    lines.append("}")

    lines.append(f"sol_good_{good}_surplus_tier = {{")
    lines.append(f"    value = 0")
    for i, (suffix, _t, _w, _d) in enumerate(SURPLUS_TIERS):
        kw = "if" if i == 0 else "else_if"
        if is_compat:
            lines += [
                f"    {kw} = {{ limit = {{ sol_pp_victuals_compat_is_on = yes {_list_check(good, suffix)} }} value = {3 - i} }}",
            ]
        else:
            lines.append(f"    {kw} = {{ limit = {{ {_list_check(good, suffix)} }} value = {3 - i} }}")
    lines.append("}")

    lines.append(f"sol_good_{good}_scarce = {{")
    lines.append(f"    value = 0")
    for i, (suffix, _t, _w, _d) in enumerate(SHORTAGE_TIERS):
        kw = "if" if i == 0 else "else_if"
        if is_compat:
            lines.append(f"    {kw} = {{ limit = {{ sol_pp_victuals_compat_is_on = yes {_list_check(good, suffix)} }} value = 1 }}")
        else:
            lines.append(f"    {kw} = {{ limit = {{ {_list_check(good, suffix)} }} value = 1 }}")
    lines.append("}")

    lines.append(f"sol_good_{good}_absent = {{")
    lines.append(f"    value = 0")
    lines.append(f"    if = {{ limit = {{ {_list_check(good, ABSENT_SUFFIX)} }} value = 1 }}")
    lines.append("}")

    if is_compat:
        lines += [
            f"sol_weight_indicator_{good} = {{",
            f"    value = 0",
            f"    if = {{",
            f"        limit = {{ sol_pp_victuals_compat_is_on = yes }}",
            f"        add = 1",
        ]
        first_adj = True
        for suffix, _t, weight, _d in SHORTAGE_TIERS + SURPLUS_TIERS:
            kw = "if" if first_adj else "else_if"
            first_adj = False
            delta = weight - 1.0
            lines.append(f"        {kw} = {{ limit = {{ {_list_check(good, suffix)} }} add = {delta} }}")
        lines += ["    }", "}"]
    else:
        lines.append(f"sol_weight_indicator_{good} = {{")
        lines.append(f"    value = 1")
        first_adj = True
        for suffix, _t, weight, _d in SHORTAGE_TIERS + SURPLUS_TIERS:
            kw = "if" if first_adj else "else_if"
            first_adj = False
            delta = weight - 1.0
            lines.append(f"    {kw} = {{ limit = {{ {_list_check(good, suffix)} }} add = {delta} }}")
        lines.append("}")

    grp_weight = f"sol_{ind_grp}_base_total_weight"
    n = DEMAND_GROUP_SIZE.get(ind_grp, IND_GROUP_SIZE[ind_grp])
    if is_compat:
        lines += [
            f"sol_demand_share_{good} = {{",
            f"    value = 0",
            f"    if = {{",
            f"        limit = {{ sol_pp_victuals_compat_is_on = yes }}",
            f"        add = 1",
        ]
        first_adj = True
        for suffix, _t, weight, _d in SHORTAGE_TIERS + SURPLUS_TIERS:
            kw = "if" if first_adj else "else_if"
            first_adj = False
            delta = weight - 1.0
            lines.append(f"        {kw} = {{ limit = {{ {_list_check(good, suffix)} }} add = {delta} }}")
        lines += [
            f"    }}",
            f"    divide = {grp_weight}",
            f"    multiply = 100",
            f"}}",
        ]
    else:
        lines.append(f"sol_demand_share_{good} = {{")
        lines.append(f"    value = sol_weight_indicator_{good}")
        lines.append(f"    divide = {grp_weight}")
        lines.append(f"    multiply = 100")
        lines.append("}")

    if is_compat:
        lines += [
            f"sol_demand_share_offset_{good}_compat = {{",
            f"    value = 0",
            f"    if = {{ limit = {{ sol_pp_victuals_compat_is_on = yes }} value = 1 }}",
            f"}}",
            f"sol_demand_share_offset_{good} = {{",
            f"    value = 0",
            f"    if = {{",
            f"        limit = {{ sol_pp_victuals_compat_is_on = yes }}",
            f"        add = 1",
        ]
        first_adj = True
        for suffix, _t, weight, _d in SHORTAGE_TIERS + SURPLUS_TIERS:
            kw = "if" if first_adj else "else_if"
            first_adj = False
            delta = weight - 1.0
            lines.append(f"        {kw} = {{ limit = {{ {_list_check(good, suffix)} }} add = {delta} }}")
        lines += [
            f"    }}",
            f"    multiply = {n}",
            f"    divide = {grp_weight}",
            f"    add = -1",
            f"    multiply = sol_demand_share_offset_{good}_compat",
            f"}}",
        ]
    else:
        lines += [
            f"sol_demand_share_offset_{good} = {{",
            f"    value = sol_weight_indicator_{good}",
            f"    multiply = {n}",
            f"    divide = {grp_weight}",
            f"    add = -1",
            f"}}",
        ]

    return lines


def _gen_group_base_total_weight(grp: str, goods: List[str], prices: dict) -> List[str]:
    avg_price = sum(prices.get(g, 1.0) for g in goods) / len(goods) if goods else 1.0
    lines: List[str] = [f"sol_{grp}_base_total_weight = {{", "    value = 0"]
    for good in goods:
        price = prices.get(good, 1.0)
        price_factor = round(price / avg_price, 5)
        is_compat = good in COMPAT_GOODS
        if is_compat:
            lines.append(f"    if = {{ limit = {{ sol_pp_victuals_compat_is_on = yes }}")
            first = True
            for suffix, _t, weight, _d in SHORTAGE_TIERS:
                kw = "if" if first else "else_if"
                first = False
                contrib = round(weight * price_factor, 5)
                lines.append(f"        {kw} = {{ limit = {{ {_list_check(good, suffix)} }} add = {contrib} }}")
            for suffix, _t, weight, _d in SURPLUS_TIERS:
                contrib = round(weight * price_factor, 5)
                lines.append(f"        else_if = {{ limit = {{ {_list_check(good, suffix)} }} add = {contrib} }}")
            normal_contrib = round(1.0 * price_factor, 5)
            lines.append(f"        else = {{ add = {normal_contrib} }}")
            lines.append(f"    }}")
        else:
            first = True
            for suffix, _t, weight, _d in SHORTAGE_TIERS:
                kw = "if" if first else "else_if"
                first = False
                contrib = round(weight * price_factor, 5)
                lines.append(f"    {kw} = {{ limit = {{ {_list_check(good, suffix)} }} add = {contrib} }}")
            for suffix, _t, weight, _d in SURPLUS_TIERS:
                contrib = round(weight * price_factor, 5)
                lines.append(f"    else_if = {{ limit = {{ {_list_check(good, suffix)} }} add = {contrib} }}")
            normal_contrib = round(1.0 * price_factor, 5)
            lines.append(f"    else = {{ add = {normal_contrib} }}")
    lines += ["    min = 0.001", "}"]
    return lines


def _gen_secondary_offset(good: str, secondary_grp: str) -> List[str]:
    n = DEMAND_GROUP_SIZE[secondary_grp]
    grp_weight = f"sol_{secondary_grp}_base_total_weight"
    return [
        f"sol_demand_share_offset_{good}_in_{secondary_grp} = {{",
        f"    value = sol_weight_indicator_{good}",
        f"    multiply = {n}",
        f"    divide = {grp_weight}",
        f"    add = -1",
        f"}}",
    ]


def gen_indicators_file(prices: dict) -> str:
    demand_dict = {grp: members for grp, members in DEMAND_GROUPS}
    out: List[str] = [INDICATORS_HEADER.rstrip()]
    for grp, goods in INDICATOR_GROUPS:
        demand_members = demand_dict.get(grp, list(goods))
        goods_set = set(goods)
        out.append("")
        out.append(f"###############################################################")
        out.append(f"# {grp.upper()} group: {', '.join(demand_members)}")
        out.append(f"###############################################################")
        out.append("")
        out.extend(_gen_group_base_total_weight(grp, demand_members, prices))
        out.append("")
        for good in goods:
            out.extend(_gen_good_indicators(good))
            out.append("")
        guests = [g for g in demand_members if g not in goods_set]
        for guest in guests:
            out.extend(_gen_secondary_offset(guest, grp))
            out.append("")
    return "\n".join(out) + "\n"


def gen_group_indicators_file() -> str:
    out: List[str] = [GROUP_INDICATORS_HEADER.rstrip()]
    for grp, goods in DEMAND_GROUPS:
        out.append("")
        out.append(f"sol_grp_{grp}_scarce = {{")
        out.append(f"    value = 0")
        out.append(f"    if = {{")
        out.append(f"        limit = {{")
        out.append(f"            OR = {{")
        for good in goods:
            for suffix, _t, _w, _d in SHORTAGE_TIERS:
                lst = _good_list_name(good, suffix)
                out.append(f"                market ?= {{ is_target_in_global_variable_list = {{ name = {lst} target = this }} }}")
        out.append(f"            }}")
        out.append(f"        }}")
        out.append(f"        value = 1")
        out.append(f"    }}")
        out.append(f"}}")
    out.append("")
    return "\n".join(out)
