#!/usr/bin/env python3
"""Generate SOL demand overlays under the original post-resolution INJECT model."""

import argparse
import csv
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation, getcontext
import io
from pathlib import Path
import re
import sys


getcontext().prec = 50
POPS = ("nobles", "clergy", "burghers", "laborers", "peasants", "soldiers", "tribesmen")
GOODS_PATH = Path("in_game/common/goods/z_SOL_pop_goods.txt")
CONSTANTS_PATH = Path("in_game/common/script_values/SOL_market_unit_consumption_values.txt")
MANIFEST_PATH = Path("tools/target_demand.csv")
EXPECTED_GOODS = 55
TOKEN = re.compile(r'\s+|\#[^\n]*|"(?:\\.|[^"\\])*"|[{}]|!=|<=|>=|[=<>?]|[^\s{}=<>?!"#]+')
NUMBER = re.compile(r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?\Z")
HEADER = (
    "# Generated by tools/gen_sol14_demand.py from tools/target_demand.csv.\n"
    "# Uses SOL's post-resolution INJECT model; verify injection order in-game.\n\n"
)


class DemandError(ValueError):
    pass


@dataclass(frozen=True)
class Entry:
    key: str
    operator: str | None
    value: str | tuple


def require(condition, message):
    if not condition:
        raise DemandError(message)


def text(path):
    return path.read_text(encoding="utf-8-sig")


def number(value, label):
    require(isinstance(value, str) and NUMBER.fullmatch(value) is not None,
            f"{label}: expected a finite decimal number, got {value!r}")
    try:
        result = Decimal(value)
    except InvalidOperation as exc:
        raise DemandError(f"{label}: invalid decimal {value!r}") from exc
    parts = result.as_tuple()
    require(result.is_finite() and len(parts.digits) <= 28 and -24 <= parts.exponent <= 24,
            f"{label}: unsupported decimal precision or exponent: {value!r}")
    return result


def fmt(value):
    if value == 0:
        return "0"
    result = format(value, "f")
    return result.rstrip("0").rstrip(".") if "." in result else result


def parse(source, label):
    tokens = []
    position = 0
    for match in TOKEN.finditer(source):
        require(match.start() == position, f"{label}: unsupported syntax at offset {position}")
        position = match.end()
        token = match.group()
        if not token.isspace() and not token.startswith("#"):
            tokens.append(token)
    require(position == len(source), f"{label}: unsupported syntax at offset {position}")
    cursor = 0

    def block(nested=False):
        nonlocal cursor
        entries = []
        while cursor < len(tokens):
            key = tokens[cursor]
            cursor += 1
            if key == "}":
                require(nested, f"{label}: unmatched closing brace")
                return tuple(entries)
            require(key not in ("{", "=", "!=", "<", ">", "<=", ">=", "?"),
                    f"{label}: expected a key, got {key!r}")
            if cursor == len(tokens) or tokens[cursor] not in ("=", "!=", "<", ">", "<=", ">=", "?"):
                entries.append(Entry(key, None, key))
                continue
            operator = tokens[cursor]
            cursor += 1
            require(cursor < len(tokens), f"{label}: missing value for {key}")
            value = tokens[cursor]
            cursor += 1
            if value == "{":
                value = block(True)
            else:
                require(value != "}", f"{label}: missing value for {key}")
            entries.append(Entry(key, operator, value))
        require(not nested, f"{label}: unclosed brace")
        return tuple(entries)

    return block()


def definitions(path):
    result = {}
    for entry in parse(text(path), str(path)):
        require(entry.operator == "=" and isinstance(entry.value, tuple),
                f"{path}: expected a named definition block, got {entry.key}")
        require(entry.key not in result, f"{path}: duplicate definition {entry.key}")
        result[entry.key] = entry.value
    return result


def field(body, key, label, default=None):
    matches = [entry for entry in body if entry.key == key]
    require(len(matches) <= 1, f"{label}: duplicate field {key}")
    if not matches:
        return default
    require(matches[0].operator == "=", f"{label}: unsupported operator on {key}")
    return matches[0].value


def numeric_block(body, key, label, active):
    value = field(body, key, label, ())
    require(isinstance(value, tuple), f"{label}.{key}: expected a numeric pop block")
    result = {}
    for entry in value:
        require(entry.operator == "=" and entry.key in ("all", "upper", *active),
                f"{label}.{key}: unsupported pop selector/operator {entry.key}")
        require(entry.key not in result, f"{label}.{key}: duplicate selector {entry.key}")
        result[entry.key] = number(entry.value, f"{label}.{key}.{entry.key}")
    return result


def expanded(values, pop, upper, multiply=False):
    selectors = ("all", "upper", pop) if pop in upper else ("all", pop)
    result = Decimal(1 if multiply else 0)
    for selector in selectors:
        if selector in values:
            if multiply:
                result *= values[selector]
            else:
                result += values[selector]
    return result


def baseline(body, good, active, upper):
    additions = numeric_block(body, "demand_add", good, active)
    multipliers = numeric_block(body, "demand_multiply", good, active)
    require(all(value >= 0 for value in additions.values()), f"{good}: negative baseline demand_add")
    require(all(value >= 0 for value in multipliers.values()), f"{good}: negative baseline demand_multiply")
    return {pop: expanded(additions, pop, upper) * expanded(multipliers, pop, upper, True)
            for pop in active}


def load_sources(sol_root, game_root):
    source_text = text(sol_root / GOODS_PATH)
    original = definitions(sol_root / GOODS_PATH)
    require(len(original) == EXPECTED_GOODS, f"SOL: expected {EXPECTED_GOODS} INJECT blocks, got {len(original)}")
    goods = []
    policies = {}
    for key, body in original.items():
        require(re.fullmatch(r"INJECT:[a-z][a-z0-9_]*", key), f"SOL: unsupported definition {key}")
        good = key.removeprefix("INJECT:")
        require(all(entry.key in ("demand_add", "development_threshold", "wealth_impact_threshold")
                    for entry in body), f"SOL {good}: unsupported injection fields")
        goods.append(good)
        policies[good] = body
    constants = {}
    for key, body in definitions(sol_root / CONSTANTS_PATH).items():
        match = re.fullmatch(r"sol_unit_consumption_(" + "|".join(POPS) + r")_([a-z][a-z0-9_]*)", key)
        require(match is not None, f"SOL: unsupported consumption constant {key}")
        pop, good = match.groups()
        require(good in goods, f"SOL: constant {key} has no authored goods block")
        require(len(body) == 1 and body[0].key == "value", f"SOL: unsupported constant body {key}")
        value = number(field(body, "value", key), key)
        require(value >= 0, f"SOL: negative consumption constant {key}")
        constants[pop, good] = value
    pops = definitions(game_root / "in_game/common/pop_types/00_default.txt")
    active = tuple(pops)
    require(set(active) == set((*POPS, "slaves")), f"1.4: unsupported active pop types: {active}")
    upper = set()
    for pop, body in pops.items():
        flag = field(body, "upper", pop, "no")
        require(flag in ("yes", "no"), f"{pop}: unsupported upper flag {flag!r}")
        if flag == "yes":
            upper.add(pop)
    require(upper == {"nobles", "clergy", "burghers"}, f"1.4: unsupported upper pop group: {sorted(upper)}")
    vanilla = {}
    goods_dir = game_root / "in_game/common/goods"
    paths = sorted(goods_dir.glob("*.txt"))
    require(paths, f"No goods files in {goods_dir}")
    for path in paths:
        if path.name.lower() == "readme.txt":
            continue
        for good, body in definitions(path).items():
            require(good not in vanilla, f"1.4: duplicate goods definition {good}")
            require(not good.startswith("INJECT:"), f"1.4: unsupported baseline injection {good}")
            vanilla[good] = body
    require(set(goods) <= vanilla.keys(), f"1.4: missing SOL goods: {sorted(set(goods) - vanilla.keys())}")
    return goods, policies, constants, source_text, vanilla, active, upper


def reconstruct(goods, constants, source_text):
    authored = {}
    pending = None
    for line in source_text.splitlines():
        match = re.fullmatch(r"\s*#\s*net:\s*(.*?)\s*", line)
        if match:
            require(pending is None, "SOL: multiple net comments before an INJECT block")
            pending = {}
            for assignment in match[1].split("|"):
                pair = assignment.strip().split("=")
                require(len(pair) == 2 and pair[0] in POPS, f"SOL: unsupported net comment {assignment!r}")
                pop, value = pair
                require(pop not in pending, f"SOL: duplicate pop {pop} in net comment")
                pending[pop] = number(value, f"SOL net {pop}")
        match = re.match(r"\s*INJECT:([a-z][a-z0-9_]*)\s*=", line)
        if match:
            good = match[1]
            require(pending is not None, f"SOL {good}: missing authored net comment")
            require(good not in authored, f"SOL: duplicate authored comment for {good}")
            authored[good] = pending
            pending = None
    require(pending is None and set(authored) == set(goods), "SOL: unmatched authored net comments")
    return {good: {pop: authored[good].get(pop, constants.get((pop, good), Decimal(0)))
                   for pop in POPS} for good in goods}


def manifest_bytes(targets, goods):
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(("good", *POPS))
    for good in goods:
        writer.writerow((good, *(fmt(targets[good][pop]) for pop in POPS)))
    return buffer.getvalue().encode("utf-8")


def load_manifest(path, goods):
    with path.open(encoding="utf-8-sig", newline="") as stream:
        reader = csv.DictReader(stream)
        require(reader.fieldnames == ["good", *POPS], f"{path}: expected CSV header good,{','.join(POPS)}")
        targets = {}
        for row in reader:
            good = row["good"]
            require(None not in row and all(value is not None for value in row.values()),
                    f"{path}:{reader.line_num}: wrong column count")
            require(good in goods, f"{path}:{reader.line_num}: unknown good {good!r}")
            require(good not in targets, f"{path}:{reader.line_num}: duplicate good {good}")
            targets[good] = {pop: number(row[pop], f"{path}:{reader.line_num}:{pop}") for pop in POPS}
    require(set(targets) == set(goods), f"{path}: missing goods {sorted(set(goods) - targets.keys())}")
    return targets


def threshold_policy(policies, vanilla, active):
    for good, body in policies.items():
        if field(body, "development_threshold", good) is not None:
            require(field(vanilla[good], "development_threshold", good) is not None,
                    f"{good}: original SOL development cancellation no longer has a baseline")
        old = numeric_block(body, "wealth_impact_threshold", f"SOL {good}", active)
        current = numeric_block(vanilla[good], "wealth_impact_threshold", good, active)
        require(not old or current, f"{good}: original SOL wealth cancellation no longer has a baseline")


def generate(targets, sources):
    goods, policies, constants, _, vanilla, active, upper = sources
    threshold_policy(policies, vanilla, active)
    lines = [HEADER.rstrip("\n"), ""]
    for good in goods:
        resolved = baseline(vanilla[good], good, active, upper)
        require(set(targets[good]) == set(POPS), f"{good}: incomplete target pop basket")
        require(all(value >= 0 for value in targets[good].values()), f"{good}: negative target quantity")
        deltas = {pop: targets[good][pop] - resolved[pop] for pop in POPS}
        lines.append(f"INJECT:{good} = {{")
        development = field(vanilla[good], "development_threshold", good)
        if development is not None:
            lines.append(f"\tdevelopment_threshold = {fmt(-number(development, good + '.development_threshold'))}")
        lines.append("\tdemand_add = {")
        for pop in POPS:
            if deltas[pop] != 0:
                lines.append(f"\t\t{pop} = {fmt(deltas[pop])}")
        lines.append("\t}")
        wealth = numeric_block(vanilla[good], "wealth_impact_threshold", good, active)
        if wealth:
            lines.append("\twealth_impact_threshold = {")
            for selector, value in wealth.items():
                lines.append(f"\t\t{selector} = {fmt(-value)}")
            lines.append("\t}")
        lines.extend(("}", ""))
    goods_output = ("\n".join(lines) + "\n").encode("utf-8")
    lines = [HEADER.rstrip("\n"), ""]
    for pop in POPS:
        for good in sorted(goods):
            if (pop, good) in constants or targets[good][pop] != 0:
                lines.extend((f"sol_unit_consumption_{pop}_{good} = {{",
                              f"\tvalue = {fmt(targets[good][pop])}", "}", ""))
    constants_output = ("\n".join(lines) + "\n").encode("utf-8")
    validate(goods_output, constants_output, targets, sources)
    return {GOODS_PATH: goods_output, CONSTANTS_PATH: constants_output}


def validate(goods_output, constants_output, targets, sources):
    goods, _, constants, _, vanilla, active, upper = sources
    injections = parse(goods_output.decode("utf-8"), "generated goods")
    require(len(injections) == EXPECTED_GOODS and [entry.key for entry in injections] == [f"INJECT:{good}" for good in goods],
            "Generated injection count, order or uniqueness mismatch")
    for injection in injections:
        good = injection.key.removeprefix("INJECT:")
        body = injection.value
        require(injection.operator == "=" and isinstance(body, tuple), f"{good}: malformed injection")
        require(all(entry.key in ("demand_add", "development_threshold", "wealth_impact_threshold") for entry in body),
                f"{good}: injection modifies a context field or demand_multiply")
        deltas = numeric_block(body, "demand_add", good, active)
        require(set(deltas) <= set(POPS), f"{good}: broad or unmodeled demand selector")
        resolved = baseline(vanilla[good], good, active, upper)
        for pop in POPS:
            effective = resolved[pop] + deltas.get(pop, Decimal(0))
            require(effective >= 0 and effective == targets[good][pop], f"{good}.{pop}: baseline + delta != target")
        require("slaves" not in deltas, f"{good}: slave demand changed")
        development = number(field(vanilla[good], "development_threshold", good, "0"), good)
        cancellation = number(field(body, "development_threshold", good, "0"), good)
        require(development + cancellation == 0, f"{good}: uncancelled development threshold")
        wealth = numeric_block(vanilla[good], "wealth_impact_threshold", good, active)
        cancel = numeric_block(body, "wealth_impact_threshold", good, active)
        require(cancel == {selector: -value for selector, value in wealth.items()}, f"{good}: wealth cancellation mismatch")
        for pop in active:
            require(expanded(wealth, pop, upper) + expanded(cancel, pop, upper) == 0, f"{good}.{pop}: uncancelled wealth threshold")
        untouched = tuple(entry for entry in vanilla[good] if entry.key not in ("demand_add", "development_threshold", "wealth_impact_threshold"))
        effective_fields = (*vanilla[good], *body)
        require(tuple(entry for entry in effective_fields if entry.key not in ("demand_add", "development_threshold", "wealth_impact_threshold")) == untouched,
                f"{good}: contextual fields changed")
    entries = parse(constants_output.decode("utf-8"), "generated constants")
    expected = {f"sol_unit_consumption_{pop}_{good}": targets[good][pop]
                for pop in POPS for good in goods if (pop, good) in constants or targets[good][pop] != 0}
    actual = {}
    for entry in entries:
        require(entry.key not in actual and entry.key in expected, f"Unknown/duplicate generated constant {entry.key}")
        require(entry.operator == "=" and isinstance(entry.value, tuple) and len(entry.value) == 1,
                f"Malformed generated constant {entry.key}")
        actual[entry.key] = number(field(entry.value, "value", entry.key), entry.key)
    require(actual == expected, "Generated consumption constants do not match manifest")


def safe_destination(patch_root, relative, protected):
    destination = (patch_root / relative).resolve()
    require(destination.is_relative_to(patch_root), f"Output escapes patch root: {destination}")
    for root in protected:
        require(not destination.is_relative_to(root), f"Refusing to write inside source root: {destination}")
    return destination


def preflight_destinations(patch_root, protected):
    paths = [(relative, safe_destination(patch_root, relative, protected))
             for relative in (MANIFEST_PATH, GOODS_PATH, CONSTANTS_PATH)]
    for index, (relative, destination) in enumerate(paths):
        for other_relative, other_destination in paths[:index]:
            require(destination != other_destination,
                    f"Destination alias: {relative} and {other_relative} resolve to {destination}")
            require(not (destination.exists() and other_destination.exists()
                         and destination.samefile(other_destination)),
                    f"Destination alias: {relative} ({destination}) and {other_relative} "
                    f"({other_destination}) identify the same existing file")
    return dict(paths)


def run(args):
    sol_root = args.sol_root.resolve()
    game_root = args.game_root.resolve()
    patch_root = args.patch_root.resolve()
    for root in (sol_root, game_root):
        require(not patch_root.is_relative_to(root) and not root.is_relative_to(patch_root),
                f"Patch root overlaps protected source root: {root}")
    paths = preflight_destinations(patch_root, (sol_root, game_root))
    sources = load_sources(sol_root, game_root)
    goods = sources[0]
    manifest = paths[MANIFEST_PATH]
    if args.reconstruct_manifest:
        require(not manifest.exists(), f"Manifest already exists; refusing reconstruction overwrite: {manifest}")
        targets = reconstruct(goods, sources[2], sources[3])
        outputs = generate(targets, sources)
        manifest.parent.mkdir(parents=True, exist_ok=True)
        manifest.write_bytes(manifest_bytes(targets, goods))
        print(f"Reconstructed {len(goods)} target rows: {manifest}")
    else:
        targets = load_manifest(manifest, goods)
        outputs = generate(targets, sources)
    destinations = {paths[relative]: data for relative, data in outputs.items()}
    if args.check:
        errors = []
        for destination, expected in destinations.items():
            if not destination.is_file():
                errors.append(f"Missing artifact: {destination}")
            elif destination.read_bytes() != expected:
                errors.append(f"Artifact drift: {destination}")
        require(not errors, "\n".join(errors))
        print(f"CHECK OK: {len(goods)} INJECT blocks; {len(POPS) * len(goods)} target quantities; synchronized constants and thresholds")
    else:
        for destination, data in destinations.items():
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(data)
            print(f"Generated {destination}")
    print("Static verification only: post-resolution INJECT order and actual loader precedence require in-game verification.")


def main():
    patch_default = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--game-root", type=Path, required=True, help="Explicit current vanilla game directory (containing in_game)")
    parser.add_argument("--sol-root", type=Path, default=patch_default.parent / "3698931463", help="Original SOL root; default: sibling 3698931463")
    parser.add_argument("--patch-root", type=Path, default=patch_default, help="Output root; default: parent of this tools directory")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Validate inputs and artifact bytes without writing anything")
    mode.add_argument("--reconstruct-manifest", action="store_true", help="One-time reconstruction from original SOL net comments; refuses an existing CSV")
    args = parser.parse_args()
    try:
        run(args)
    except (DemandError, OSError, UnicodeError, csv.Error) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
