#!/usr/bin/env python3
"""
Generate src/stable/in_game/common/goods/z_SOL_pop_goods.txt from data/target_demand.csv.

target_demand.csv is the single source of truth for desired net demand per good per pop type.
This script derives the required demand_add injections and emits wealth_impact_threshold
negations for all vanilla goods that have them.

Workflow:
  # One-time bootstrap (reads current inject + vanilla -> writes target_demand.csv)
  conda run -n eu5 python scripts/gen_pop_goods.py --init

  # Design loop (edit CSV -> regenerate inject file)
  conda run -n eu5 python scripts/gen_pop_goods.py
  conda run -n eu5 python scripts/gen_demand_csv.py
  conda run -n eu5 python scripts/validate.py --changed

Idempotency guarantee: given the same target_demand.csv and vanilla files, the output
z_SOL_pop_goods.txt is byte-identical on every run.
"""

import argparse
import csv
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
SIMULATOR_DIR = REPO_ROOT / "tools" / "sol_demand_simulator"
sys.path.insert(0, str(SIMULATOR_DIR))

from parser import (  # noqa: E402  (local import after sys.path manipulation)
    EU5_POP_TYPES,
    INJECT_FILE,
    VANILLA_GOODS_DIR,
    _collect_brace_block,
    _find_sub_block,
    _parse_kv_block,
    _read,
    _split_named_blocks,
    _parse_inject_file,
    load_vanilla_goods,
)

TARGET_CSV = REPO_ROOT / "data" / "target_demand.csv"

POP_TYPE_ORDER: List[str] = list(EU5_POP_TYPES)
# nobles, clergy, burghers, laborers, peasants, soldiers, tribesmen

SECTION_ORDER: List[str] = [
    "raw_materials",
    "plantation_goods",
    "produced_goods",
    "food",
    "special",
]

# Top-level block names in vanilla goods files that are NOT good entries
_VANILLA_SKIP = frozenset(["category", "color", "method"])

FILE_HEADER = """\
# Goods demand adjustments for the SOL mod.
#
# AUTO-GENERATED by scripts/gen_pop_goods.py -- edit data/target_demand.csv instead.
# Workflow: gen_pop_goods.py -> gen_demand_csv.py -> validate.py --changed
#
# Two types of changes per good:
#   1. wealth_impact_threshold negation -- vanilla + inject = 0, gate permanently disabled.
#      Required because gdp_per_capita_scale already drives wealth-based demand variation;
#      the binary income/expense gate causes oscillation and instability.
#   2. demand_add rebalancing only -- demand_multiply is FORBIDDEN in INJECT blocks.
#      EU5 INJECT evaluation order: vanilla demand is fully resolved (add x multiply)
#      first, then inject demand_add is added on top. inject demand_multiply would
#      compound an already-multiplied value and is not permitted in this mod.
#      General theme: reduce noble over-representation on military/luxury goods,
#      spread demand to burghers/clergy, rebalance food multipliers."""


@dataclass
class TargetRow:
    good: str
    section: str
    negate_wit: List[str]            # [] or ["all"] or ["nobles", "burghers"] etc.
    negate_dev_thresh: Optional[float]  # inject value verbatim (e.g. -10.0), or None
    demand: Dict[str, float]         # pop_type -> desired net demand


# ---------------------------------------------------------------------------
# Vanilla file helpers
# ---------------------------------------------------------------------------

def _vanilla_goods_ordered() -> List[Tuple[str, str]]:
    """Return [(good_name, section_label), ...] in canonical vanilla file order."""
    result: List[Tuple[str, str]] = []
    seen: set = set()
    for path in sorted(VANILLA_GOODS_DIR.glob("*.txt")):
        if path.name.lower() == "readme.txt":
            continue
        stem = path.stem  # e.g. "00_raw_materials"
        section = stem.split("_", 1)[1] if "_" in stem else stem  # -> "raw_materials"
        text = _read(path)
        for name, _block in _split_named_blocks(text):
            if name in _VANILLA_SKIP:
                continue
            if name not in seen:
                seen.add(name)
                result.append((name, section))
    return result


def _load_vanilla_thresholds() -> Dict[str, Dict]:
    """
    Return {good_name: {"wit": {pop_or_all: float}, "dev_thresh": float|None}}
    for every good encountered in vanilla files.
    """
    result: Dict[str, Dict] = {}
    for path in sorted(VANILLA_GOODS_DIR.glob("*.txt")):
        if path.name.lower() == "readme.txt":
            continue
        text = _read(path)
        for name, block in _split_named_blocks(text):
            if name in _VANILLA_SKIP:
                continue
            wit_inner = _find_sub_block(block, "wealth_impact_threshold")
            wit: Dict[str, float] = _parse_kv_block(wit_inner) if wit_inner else {}
            dev_m = re.search(r"\bdevelopment_threshold\s*=\s*(-?[\d.]+)", block)
            dev_thresh: Optional[float] = float(dev_m.group(1)) if dev_m else None
            result[name] = {"wit": wit, "dev_thresh": dev_thresh}
    return result


def _compute_vanilla_net() -> Dict[str, Dict[str, float]]:
    """Return {good_name: {pop_type: vanilla_add * vanilla_multiply}}."""
    vanilla = load_vanilla_goods()
    return {
        name: {pt: data["add"][pt] * data["mult"][pt] for pt in POP_TYPE_ORDER}
        for name, data in vanilla.items()
    }


# ---------------------------------------------------------------------------
# Float formatting
# ---------------------------------------------------------------------------

def _fmt_jomini(v: float) -> str:
    """Format float for Jomini output: max 5 decimal places, no scientific notation."""
    rounded = round(v, 5)
    if rounded == 0.0:
        return "0"
    return f"{rounded:.5f}".rstrip("0").rstrip(".")


def _fmt_csv(v: float) -> str:
    """Format float for CSV storage: 6 significant digits to preserve precision."""
    if abs(v) < 1e-9:
        return "0"
    return f"{v:.6g}"


# ---------------------------------------------------------------------------
# CSV I/O
# ---------------------------------------------------------------------------

def _load_target_csv(path: Path) -> List[TargetRow]:
    rows: List[TargetRow] = []
    with path.open(encoding="utf-8-sig") as f:
        for record in csv.DictReader(f):
            negate_wit_raw = record.get("negate_wit", "").strip()
            negate_wit = (
                [x.strip() for x in negate_wit_raw.split(",") if x.strip()]
                if negate_wit_raw else []
            )
            negate_dev_raw = record.get("negate_dev_thresh", "").strip()
            negate_dev_thresh: Optional[float] = float(negate_dev_raw) if negate_dev_raw else None
            demand: Dict[str, float] = {
                pt: float(record.get(pt, "0").strip() or "0")
                for pt in POP_TYPE_ORDER
            }
            rows.append(TargetRow(
                good=record["good"],
                section=record.get("section", ""),
                negate_wit=negate_wit,
                negate_dev_thresh=negate_dev_thresh,
                demand=demand,
            ))
    return rows


def _write_target_csv(rows: List[TargetRow], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["good", "section", "negate_wit", "negate_dev_thresh"] + POP_TYPE_ORDER
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            record: Dict = {
                "good": row.good,
                "section": row.section,
                "negate_wit": ",".join(row.negate_wit),
                "negate_dev_thresh": (
                    "" if row.negate_dev_thresh is None
                    else _fmt_jomini(row.negate_dev_thresh)
                ),
            }
            for pt in POP_TYPE_ORDER:
                record[pt] = _fmt_csv(row.demand.get(pt, 0.0))
            writer.writerow(record)


# ---------------------------------------------------------------------------
# Inject block generation
# ---------------------------------------------------------------------------

def _derive_inject_add(
    row: TargetRow,
    vanilla_net: Dict[str, Dict[str, float]],
) -> Dict[str, float]:
    """
    Compute inject demand_add per pop type (target - vanilla_net).
    Returns only entries with abs >= 1e-7 (filters floating-point noise).
    """
    vnet = vanilla_net.get(row.good, {pt: 0.0 for pt in POP_TYPE_ORDER})
    result: Dict[str, float] = {}
    for pt in POP_TYPE_ORDER:
        raw = round(row.demand.get(pt, 0.0) - vnet.get(pt, 0.0), 5)
        if abs(raw) >= 1e-7:
            result[pt] = raw
    return result


def _render_wit_block(
    negate_wit: List[str],
    vanilla_wit: Dict[str, float],
) -> Optional[str]:
    """
    Render the wealth_impact_threshold = { ... } block.
    Reads vanilla values and negates them. Returns None if nothing to emit
    (negate_wit is empty, or all referenced vanilla values are zero).
    """
    if not negate_wit:
        return None
    lines = ["\twealth_impact_threshold = {"]
    emitted = False
    if negate_wit == ["all"]:
        val = vanilla_wit.get("all", 0.0)
        if abs(val) >= 1e-9:
            lines.append(f"\t\tall = {_fmt_jomini(-val)}")
            emitted = True
    else:
        for key in negate_wit:
            val = vanilla_wit.get(key, 0.0)
            if abs(val) >= 1e-9:
                lines.append(f"\t\t{key} = {_fmt_jomini(-val)}")
                emitted = True
    if not emitted:
        return None
    lines.append("\t}")
    return "\n".join(lines)


def _build_comment(
    good: str,
    inject_add: Dict[str, float],
    vanilla_net: Dict[str, Dict[str, float]],
) -> str:
    """Build the # vanilla net / # inject add / # net comment above an INJECT entry."""
    vnet = vanilla_net.get(good, {pt: 0.0 for pt in POP_TYPE_ORDER})

    def _fmt_vals(vals: Dict[str, float], show_sign: bool = False) -> Optional[str]:
        parts = []
        for pt in POP_TYPE_ORDER:
            v = vals.get(pt, 0.0)
            if abs(v) < 1e-9:
                continue
            parts.append(f"{pt}={v:+.6g}" if show_sign else f"{pt}={v:.6g}")
        return " | ".join(parts) if parts else None

    net = {pt: vnet.get(pt, 0.0) + inject_add.get(pt, 0.0) for pt in POP_TYPE_ORDER}

    comment_lines: List[str] = []
    v_str = _fmt_vals(vnet)
    if v_str:
        comment_lines.append(f"# vanilla net: {v_str}")
    i_str = _fmt_vals(inject_add, show_sign=True)
    if i_str:
        comment_lines.append(f"# inject add:  {i_str}")
    n_str = _fmt_vals(net)
    comment_lines.append(f"# net:         {n_str}" if n_str else "# net:         (all zero)")
    return "\n".join(comment_lines)


def _render_inject_block(
    row: TargetRow,
    inject_add: Dict[str, float],
    vanilla_thresh: Dict[str, Dict],
    vanilla_net: Dict[str, Dict[str, float]],
) -> Optional[str]:
    """
    Render a complete INJECT:good = { ... } entry with comment header.
    Returns None if there is nothing to emit for this good.
    """
    vt = vanilla_thresh.get(row.good, {"wit": {}, "dev_thresh": None})
    wit_block = _render_wit_block(row.negate_wit, vt["wit"])

    if not inject_add and wit_block is None and row.negate_dev_thresh is None:
        return None

    comment = _build_comment(row.good, inject_add, vanilla_net)
    parts = [comment, f"INJECT:{row.good} = {{"]

    if row.negate_dev_thresh is not None:
        parts.append(f"\tdevelopment_threshold = {_fmt_jomini(row.negate_dev_thresh)}")

    if inject_add:
        da_lines = ["\tdemand_add = {"]
        for pt in POP_TYPE_ORDER:
            if pt in inject_add:
                da_lines.append(f"\t\t{pt} = {_fmt_jomini(inject_add[pt])}")
        da_lines.append("\t}")
        parts.append("\n".join(da_lines))

    if wit_block:
        parts.append(wit_block)

    parts.append("}")
    return "\n".join(parts)


def generate_inject_file(
    target_rows: List[TargetRow],
    vanilla_net: Dict[str, Dict[str, float]],
    vanilla_thresh: Dict[str, Dict],
) -> str:
    """Generate the complete z_SOL_pop_goods.txt text (without BOM)."""
    sections: Dict[str, List[TargetRow]] = {s: [] for s in SECTION_ORDER}
    for row in target_rows:
        sec = row.section if row.section in sections else SECTION_ORDER[0]
        sections[sec].append(row)

    output_parts: List[str] = [FILE_HEADER, ""]

    for section in SECTION_ORDER:
        rows_in_section = sections[section]
        if not rows_in_section:
            continue
        blocks = []
        for row in rows_in_section:
            inject_add = _derive_inject_add(row, vanilla_net)
            block = _render_inject_block(row, inject_add, vanilla_thresh, vanilla_net)
            if block:
                blocks.append(block)
        if not blocks:
            continue
        output_parts.append(f"### {section} ###")
        output_parts.append("")
        for block in blocks:
            output_parts.append(block)
            output_parts.append("")

    return "\n".join(output_parts)


# ---------------------------------------------------------------------------
# Bootstrap (--init) mode
# ---------------------------------------------------------------------------

def _read_inject_dev_thresh(good: str, inject_text: str) -> Optional[float]:
    """Read development_threshold inject value for a good from z_SOL_pop_goods.txt."""
    pattern = re.compile(r"\bINJECT\s*:\s*" + re.escape(good) + r"\s*=\s*\{")
    m = pattern.search(inject_text)
    if not m:
        return None
    brace_pos = inject_text.index("{", m.start())
    inner, _ = _collect_brace_block(inject_text, brace_pos)
    dev_m = re.search(r"\bdevelopment_threshold\s*=\s*(-?[\d.]+)", inner)
    return float(dev_m.group(1)) if dev_m else None


def init_target_csv(output_path: Path, force: bool) -> None:
    """
    Bootstrap target_demand.csv from the current inject file and vanilla goods files.

    - negate_wit is populated from vanilla WIT keys (comprehensive threshold removal).
    - negate_dev_thresh is read from the current inject file (preserves intentional
      partial negations like marble's -10.0).
    - demand = vanilla_net + current inject_add (captures the current design intent).
    """
    if output_path.exists() and not force:
        print(
            f"[gen_pop_goods] {output_path.relative_to(REPO_ROOT)} already exists. "
            "Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    vanilla_net = _compute_vanilla_net()
    vanilla_thresh = _load_vanilla_thresholds()
    inject_data = _parse_inject_file(INJECT_FILE)
    inject_text = _read(INJECT_FILE)

    ordered = _vanilla_goods_ordered()
    vanilla_goods_set = {name for name, _ in ordered}

    rows: List[TargetRow] = []
    seen: set = set()

    # Pass 1: vanilla goods in canonical file order
    for name, section in ordered:
        if name in seen:
            continue
        seen.add(name)

        vnet = vanilla_net.get(name, {pt: 0.0 for pt in POP_TYPE_ORDER})
        inj = inject_data.get(name, {})
        inject_add_raw: Dict[str, float] = inj.get(
            "inject_add", {pt: 0.0 for pt in POP_TYPE_ORDER}
        )
        demand = {
            pt: round(vnet.get(pt, 0.0) + inject_add_raw.get(pt, 0.0), 5)
            for pt in POP_TYPE_ORDER
        }

        # negate_wit from vanilla WIT keys (ensures all thresholds are removed)
        vt = vanilla_thresh.get(name, {"wit": {}, "dev_thresh": None})
        negate_wit = list(vt["wit"].keys())

        # negate_dev_thresh from current inject (preserves intentional partial values)
        negate_dev_thresh = _read_inject_dev_thresh(name, inject_text)

        has_demand = any(abs(v) >= 1e-9 for v in demand.values())
        if not has_demand and not negate_wit and negate_dev_thresh is None:
            continue  # nothing to inject for this good

        rows.append(TargetRow(
            good=name,
            section=section,
            negate_wit=negate_wit,
            negate_dev_thresh=negate_dev_thresh,
            demand=demand,
        ))

    # Pass 2: inject-only goods not present in any vanilla file (defensive)
    for name, inj in inject_data.items():
        if name in vanilla_goods_set or name in seen:
            continue
        seen.add(name)
        inject_add_raw = inj.get("inject_add", {pt: 0.0 for pt in POP_TYPE_ORDER})
        demand = {pt: round(inject_add_raw.get(pt, 0.0), 5) for pt in POP_TYPE_ORDER}
        negate_dev_thresh = _read_inject_dev_thresh(name, inject_text)
        if not any(abs(v) >= 1e-9 for v in demand.values()) and negate_dev_thresh is None:
            continue
        rows.append(TargetRow(
            good=name,
            section="produced_goods",
            negate_wit=[],
            negate_dev_thresh=negate_dev_thresh,
            demand=demand,
        ))

    _write_target_csv(rows, output_path)
    print(f"[gen_pop_goods] Wrote {len(rows)} rows -> {output_path.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Generate z_SOL_pop_goods.txt from data/target_demand.csv."
    )
    ap.add_argument(
        "--init", action="store_true",
        help="Bootstrap target_demand.csv from current inject + vanilla files.",
    )
    ap.add_argument(
        "--force", action="store_true",
        help="Allow --init to overwrite an existing target_demand.csv.",
    )
    ap.add_argument(
        "--dry-run", action="store_true",
        help="Print generated inject file to stdout without writing.",
    )
    ap.add_argument(
        "--input", default=str(TARGET_CSV),
        help="Path to target_demand.csv (default: data/target_demand.csv).",
    )
    args = ap.parse_args()

    if args.init:
        init_target_csv(Path(args.input), args.force)
        return

    input_path = Path(args.input)
    if not input_path.exists():
        print(
            f"[gen_pop_goods] ERROR: {input_path} not found. "
            "Run with --init to bootstrap the CSV first.",
            file=sys.stderr,
        )
        sys.exit(1)

    target_rows = _load_target_csv(input_path)
    vanilla_net = _compute_vanilla_net()
    vanilla_thresh = _load_vanilla_thresholds()

    content = generate_inject_file(target_rows, vanilla_net, vanilla_thresh)

    if args.dry_run:
        print(content)
        return

    INJECT_FILE.write_bytes(b"\xef\xbb\xbf" + content.encode("utf-8"))
    print(f"[gen_pop_goods] Wrote -> {INJECT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
