#!/usr/bin/env python3
"""Generate SOL-JTG compact compatibility overrides."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from typing import Dict, List, Tuple

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(REPO_ROOT))

from gen_market_unit_consumption import (  # noqa: E402
    EPSILON,
    POP_TYPES,
    _find_effect_block,
    _format_float,
    _generate_refresh_block,
    _generate_values,
    _load_good_rows,
)
from tools.sol_demand_simulator.parser import (  # noqa: E402
    _collect_brace_block,
    _find_sub_block,
    _parse_kv_block,
    _parse_vanilla_goods_file,
)

TARGET_ROOT = REPO_ROOT / "src" / "sol_jtg_compatibility_submod"
STABLE_ROOT = REPO_ROOT / "src" / "stable"
INPUT_CSV = REPO_ROOT / "data" / "jtg_pop_demand.csv"
STABLE_EFFECTS = STABLE_ROOT / "in_game" / "common" / "scripted_effects" / "A_SOL_economy_effects.txt"
STABLE_LOCATION_GUI = STABLE_ROOT / "in_game" / "gui" / "SOL_economy_local.gui"
STABLE_SITUATION_GUI = STABLE_ROOT / "in_game" / "gui" / "panels" / "situation" / "global_living_standard.gui"

GOODS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "goods" / "zz_SOL_JTG_pop_goods.txt"
VALUES_OUTPUT = TARGET_ROOT / "in_game" / "common" / "script_values" / "zz_SOL_market_unit_consumption_values.txt"
EFFECTS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "scripted_effects" / "zz_A_SOL_economy_effects.txt"
LOCATION_GUI_OUTPUT = TARGET_ROOT / "in_game" / "gui" / "zz_SOL_economy_local.gui"
SITUATION_GUI_OUTPUT = TARGET_ROOT / "in_game" / "gui" / "panels" / "situation" / "global_living_standard.gui"

UTF8_BOM = b"\xef\xbb\xbf"
GENERATED_HEADER = "# @AUTOGENERATED by scripts/gen_sol_jtg_compat.py - do not edit; run script to regenerate.\n"
GOODS_PER_ROW = 10
EXPECTED_BASE_GOODS_COUNT = 55

DEMAND_SCALES = {
    "nobles": 1.05,
    "clergy": 0.45,
    "burghers": 1.75,
    "laborers": 0.02,
    "peasants": 0.10,
    "soldiers": 0.025,
    "tribesmen": 0.0,
}

CLEAN_ROUNDING_STEPS = (
    (0.01, Decimal("0.01")),
    (0.001, Decimal("0.001")),
    (0.0001, Decimal("0.0001")),
    (0.0, Decimal("0.00001")),
)

EXPECTED_DEMAND_GOODS = frozenset({
    "aromatics", "bells", "brassware", "candles", "cardamom", "cheese",
    "cinnamon", "cosmetics", "ginger", "meat", "nutmeg", "ornaments",
    "palmoil", "perfume", "pewterware", "soap", "silverware", "star_anise",
    "tallow", "turmeric", "vanilla", "whaleoil",
})
EXPECTED_EXCLUDED_GOODS = frozenset({
    "antimony", "bisons", "potash", "printing_type", "zinc",
})
EXPECTED_ALL_NEW_GOODS = EXPECTED_DEMAND_GOODS | EXPECTED_EXCLUDED_GOODS

WORKSHOP_GOODS_FILES = {
    "3745661335": Path("in_game/common/goods/brass_produced_goods.txt"),
    "3739246567": Path("in_game/common/goods/meat_produced_goods.txt"),
    "3736761633": Path("in_game/common/goods/soap_goods.txt"),
    "3730619029": Path("in_game/common/goods/spices_produced_goods.txt"),
    "3728969190": Path("in_game/common/goods/cheese_produced_goods.txt"),
}


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def _script_float(value: float) -> float:
    return float(_format_float(value))


def _clean_target(value: float) -> float:
    if value <= EPSILON:
        return 0.0
    for threshold, step in CLEAN_ROUNDING_STEPS:
        if value >= threshold:
            rounded = Decimal(str(value)).quantize(step, rounding=ROUND_HALF_UP)
            return _script_float(float(rounded))
    raise ValueError(f"No clean rounding step for value: {value}")


def _load_rows() -> List[Dict[str, object]]:
    with INPUT_CSV.open(encoding="utf-8-sig", newline="") as handle:
        raw_rows = list(csv.DictReader(handle))

    rows: List[Dict[str, object]] = []
    seen: set[str] = set()
    expected_columns = {
        "workshop_id", "mod_name", "good", "price", *POP_TYPES, "slaves",
    }
    if not raw_rows:
        raise ValueError(f"No JTG rows found in {INPUT_CSV}")
    missing_columns = expected_columns - set(raw_rows[0])
    if missing_columns:
        raise ValueError(f"JTG CSV missing columns: {sorted(missing_columns)}")

    for raw in raw_rows:
        good = raw["good"].strip()
        if good in seen:
            raise ValueError(f"Duplicate JTG good in CSV: {good}")
        seen.add(good)
        price = float(raw["price"])
        if price <= EPSILON:
            raise ValueError(f"{good}: default price must be positive")
        native = {pop_type: float(raw[pop_type] or 0) for pop_type in POP_TYPES}
        if any(value < 0 for value in native.values()):
            raise ValueError(f"{good}: native demand must be non-negative")
        slave_demand = float(raw["slaves"] or 0)
        if slave_demand < 0:
            raise ValueError(f"{good}: slave demand must be non-negative")
        rows.append({
            "workshop_id": raw["workshop_id"].strip(),
            "mod_name": raw["mod_name"].strip(),
            "good": good,
            "price": price,
            "native": native,
            "slaves": slave_demand,
        })

    actual_goods = set(seen)
    if actual_goods != EXPECTED_DEMAND_GOODS:
        missing = sorted(EXPECTED_DEMAND_GOODS - actual_goods)
        extra = sorted(actual_goods - EXPECTED_DEMAND_GOODS)
        raise ValueError(f"Invalid JTG demand-good set; missing={missing}, extra={extra}")
    if set(DEMAND_SCALES) != set(POP_TYPES):
        raise ValueError("JTG demand scales must cover exactly the SOL pop types")
    return sorted(rows, key=lambda row: str(row["good"]))


def _target_quantities(row: Dict[str, object]) -> Dict[str, float]:
    native = row["native"]
    assert isinstance(native, dict)
    return {
        pop_type: _clean_target(float(native[pop_type]) * DEMAND_SCALES[pop_type])
        for pop_type in POP_TYPES
    }


def _corrections(row: Dict[str, object]) -> Dict[str, float]:
    native = row["native"]
    assert isinstance(native, dict)
    targets = _target_quantities(row)
    corrections: Dict[str, float] = {}
    for pop_type in POP_TYPES:
        effective_native = _script_float(float(native[pop_type]))
        correction = _script_float(targets[pop_type] - effective_native)
        final = _script_float(effective_native + correction)
        if abs(final - targets[pop_type]) > EPSILON:
            raise ValueError(
                f"{row['good']}: cannot reach {pop_type} target "
                f"{targets[pop_type]} from {effective_native} with {correction}"
            )
        corrections[pop_type] = correction
    return corrections


def _jtg_good_rows(rows: List[Dict[str, object]]) -> List[Tuple[str, float, Dict[str, float]]]:
    return [
        (str(row["good"]), float(row["price"]), _target_quantities(row))
        for row in rows
    ]


def _combined_good_rows(rows: List[Dict[str, object]]) -> List[Tuple[str, float, Dict[str, float]]]:
    base_rows = _load_good_rows()
    if len(base_rows) != EXPECTED_BASE_GOODS_COUNT:
        raise ValueError(f"Expected {EXPECTED_BASE_GOODS_COUNT} SOL goods, found {len(base_rows)}")
    base_goods = {good for good, _price, _quantities in base_rows}
    overlap = base_goods & EXPECTED_DEMAND_GOODS
    if overlap:
        raise ValueError(f"JTG goods already exist in base SOL rows: {sorted(overlap)}")
    combined = [*base_rows, *_jtg_good_rows(rows)]
    if len(combined) != EXPECTED_BASE_GOODS_COUNT + len(EXPECTED_DEMAND_GOODS):
        raise ValueError("Combined SOL-JTG goods count is invalid")
    return sorted(combined, key=lambda row: row[0])


def _render_goods(rows: List[Dict[str, object]]) -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# Apply SOL's approximate per-stratum scaling to JTG pop demand.",
        "# Targets use clean magnitude-aware steps: 0.01, 0.001, 0.0001, or 0.00001.",
        "# Slave demand is intentionally left unchanged and is never injected here.",
    ]
    for row in rows:
        good = str(row["good"])
        targets = _target_quantities(row)
        corrections = _corrections(row)
        lines.extend(["", f"# Final SOL-JTG targets for {good}:"])
        target_text = " | ".join(
            f"{pop_type}={_format_float(targets[pop_type])}" for pop_type in POP_TYPES
        )
        lines.append(f"# {target_text}")
        lines.extend([f"INJECT:{good} = {{", "\tdemand_add = {"])
        for pop_type in POP_TYPES:
            correction = corrections[pop_type]
            if abs(correction) <= EPSILON:
                continue
            lines.append(f"\t\t{pop_type} = {_format_float(correction)}")
        lines.extend(["\t}", "}"])
    lines.append("")
    return "\n".join(lines)


def _render_values(rows: List[Dict[str, object]]) -> str:
    text = _generate_values(_jtg_good_rows(rows))
    text = text.replace(
        "# @AUTOGENERATED by scripts/gen_market_unit_consumption.py - do not edit; run script to regenerate.\n",
        GENERATED_HEADER,
        1,
    )
    text = text.replace(
        "# Generated from data/demand_price_table.csv. Each value is net\n"
        "# demand_add quantity for one pop type and one good, with duplicate\n"
        "# legacy demand-group rows counted once. Yearly market spending\n"
        "# multiplies these quantities by min(market_price, default_price).\n",
        "# Adds only the 22 JTG demand goods. Existing SOL constants remain owned\n"
        "# by the full SOL mod. Values equal final post-compatibility demand and\n"
        "# yearly spending multiplies them by min(market_price, default_price).\n",
        1,
    )
    return text


def _find_named_block_in_text(text: str, key: str, source: str) -> str:
    match = re.search(
        rf"(?m)^(?:(?:TRY_)?(?:INJECT|REPLACE):)?{re.escape(key)}\s*=\s*\{{",
        text,
    )
    if not match:
        raise ValueError(f"{key} block not found in {source}")
    brace_start = text.index("{", match.start())
    block, _end = _collect_brace_block(text, brace_start)
    return block


def _replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"Expected one {label} anchor, found {count}")
    return text.replace(old, new, 1)


def _country_reset(good: str) -> str:
    return (
        f"\tremove_from_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country }}\n"
        f"\tadd_to_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country value = 0 }}"
    )


def _country_market_check(good: str) -> str:
    return (
        "\t\tif = {\n"
        "\t\t\tlimit = {\n"
        f"\t\t\t\thas_global_variable_map = sol_market_consumes_{good}\n"
        f"\t\t\t\tis_key_in_global_variable_map = {{ name = sol_market_consumes_{good} target = scope:gls_panel_market }}\n"
        f"\t\t\t\t\"global_variable_map(sol_market_consumes_{good}|scope:gls_panel_market)\" > 0\n"
        "\t\t\t}\n"
        f"\t\t\tremove_from_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country }}\n"
        f"\t\t\tadd_to_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country value = 1 }}\n"
        "\t\t}"
    )


def _country_count(good: str) -> str:
    return (
        f"\tif = {{ limit = {{ \"global_variable_map(gls_country_consumes_{good}|scope:gls_panel_country)\" > 0 }} "
        "change_local_variable = { name = gls_country_consumed_goods_count add = 1 } }"
    )


def _render_effects(rows: List[Dict[str, object]]) -> str:
    text = _read(STABLE_EFFECTS)
    combined_rows = _combined_good_rows(rows)
    refresh = _generate_refresh_block(combined_rows)
    block_start, block_end = _find_effect_block(text)
    text = text[:block_start] + refresh + text[block_end:]

    goods = sorted(EXPECTED_DEMAND_GOODS)
    reset_anchor = _country_reset("lumber")
    resets = "\n".join(_country_reset(good) for good in goods)
    text = _replace_once(text, reset_anchor, reset_anchor + "\n" + resets, "country goods reset")

    check_anchor = _country_market_check("lumber")
    checks = "\n".join(_country_market_check(good) for good in goods)
    text = _replace_once(text, check_anchor, check_anchor + "\n" + checks, "country market aggregation")

    count_anchor = _country_count("lumber")
    counts = "\n".join(_country_count(good) for good in goods)
    text = _replace_once(text, count_anchor, count_anchor + "\n" + counts, "country goods count")

    lines = [
        GENERATED_HEADER.rstrip(),
        "# Replace only the two SOL effects whose bodies differ in the JTG stack.",
    ]
    for key in ("sol_refresh_market_pop_demand_maps", "gls_accumulate_panel_stats"):
        block = _find_named_block_in_text(text, key, str(STABLE_EFFECTS))
        lines.extend(["", f"REPLACE:{key} = {{", block, "}"])
    lines.append("")
    rendered = "\n".join(lines)
    for good in goods:
        if f"sol_market_consumes_{good}" not in rendered:
            raise ValueError(f"Missing market effect coverage for JTG good: {good}")
        if f"gls_country_consumes_{good}" not in rendered:
            raise ValueError(f"Missing country effect coverage for JTG good: {good}")
    return rendered


def _goods_widget(good: str, variable_map: str, scope: str, indent: str) -> str:
    overlay = (
        f'text_single = {{ size = {{ 100% 100% }} align = center raw_text = "@trigger_no!" fontsize = 23 '
        f"visible = \"[Not(GreaterThan_CFixedPoint(GetVariableFromGlobalVariableMap('{variable_map}_{good}', {scope}).GetValue,'(CFixedPoint)0'))]\" }}"
    )
    if good in EXPECTED_DEMAND_GOODS:
        icon = (
            f'icon = {{ size = {{ 24 24 }} parentanchor = center '
            f'texture = "gfx/interface/icons/trade_goods/icon_goods_{good}.dds" }}'
        )
        return f'{indent}widget = {{ size = {{ 34 30 }} tooltip = "{good}" {icon} {overlay} }}'
    return (
        f'{indent}widget = {{ size = {{ 34 30 }} tooltip = "{good}" '
        f'text_single = {{ size = {{ 100% 100% }} align = center raw_text = "@{good}!" }} {overlay} }}'
    )


def _render_goods_vbox(
    goods: List[str], variable_map: str, scope: str, indent: str,
) -> str:
    lines = [
        f"{indent}vbox = {{",
        f"{indent}\tlayoutpolicy_horizontal = expanding",
        f"{indent}\tmargin = {{ 10 4 }}",
        f"{indent}\tspacing = 4",
    ]
    for start in range(0, len(goods), GOODS_PER_ROW):
        chunk = goods[start : start + GOODS_PER_ROW]
        lines.extend([
            f"{indent}\thbox = {{",
            f"{indent}\t\tlayoutpolicy_horizontal = expanding",
            f"{indent}\t\tspacing = 4",
        ])
        for good in chunk:
            lines.append(_goods_widget(good, variable_map, scope, indent + "\t\t"))
        for _unused in range(GOODS_PER_ROW - len(chunk)):
            lines.append(f"{indent}\t\twidget = {{ size = {{ 34 30 }} }}")
        lines.append(f"{indent}\t}}")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def _render_gui(
    source: Path, section_marker: str, variable_map: str, scope: str,
    rows: List[Dict[str, object]],
) -> str:
    text = _read(source)
    marker_index = text.find(section_marker)
    if marker_index < 0:
        raise ValueError(f"Section marker not found in {source}: {section_marker}")
    line_end = text.find("\n", marker_index)
    match = re.search(r"(?m)^(?P<indent>[\t ]*)vbox\s*=\s*\{", text[line_end + 1 :])
    if not match:
        raise ValueError(f"Goods vbox not found after {section_marker} in {source}")
    vbox_start = line_end + 1 + match.start()
    brace_start = text.index("{", vbox_start)
    _inner, vbox_end = _collect_brace_block(text, brace_start)
    indent = match.group("indent")
    goods = [good for good, _price, _quantities in _combined_good_rows(rows)]
    rendered_vbox = _render_goods_vbox(goods, variable_map, scope, indent)
    if len(goods) != 77:
        raise ValueError(f"Expected 77 GUI goods, found {len(goods)}")
    if rendered_vbox.count('widget = { size = { 34 30 } tooltip = "') != 77:
        raise ValueError("Generated GUI does not contain 77 goods widgets")
    if rendered_vbox.count("widget = { size = { 34 30 } }") != 3:
        raise ValueError("Generated GUI does not contain three final-row spacers")
    for good in EXPECTED_DEMAND_GOODS:
        if rendered_vbox.count(f'tooltip = "{good}"') != 1:
            raise ValueError(f"Generated GUI does not contain exactly one {good} widget")
        if f"icon_goods_{good}.dds" not in rendered_vbox:
            raise ValueError(f"Generated GUI does not use the JTG DDS icon for {good}")
    return GENERATED_HEADER + text[:vbox_start] + rendered_vbox + text[vbox_end + 1 :]


def _raw_slave_demand(path: Path, good: str) -> float:
    text = _read(path)
    match = re.search(rf"(?m)^(?:INJECT:)?{re.escape(good)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"{good} block not found in {path}")
    brace_start = text.index("{", match.start())
    block, _end = _collect_brace_block(text, brace_start)
    demand_add = _find_sub_block(block, "demand_add")
    if demand_add is None:
        return 0.0
    return float(_parse_kv_block(demand_add).get("slaves", 0.0))


def _audit_workshop(workshop_root: Path, rows: List[Dict[str, object]]) -> None:
    source_goods: set[str] = set()
    parsed_by_mod: Dict[str, Tuple[Path, Dict[str, Dict[str, object]]]] = {}
    for workshop_id, relative_path in WORKSHOP_GOODS_FILES.items():
        path = workshop_root / workshop_id / relative_path
        if not path.exists():
            raise ValueError(f"Workshop goods file not found: {path}")
        parsed = _parse_vanilla_goods_file(path)
        parsed_by_mod[workshop_id] = (path, parsed)
        source_goods.update(set(parsed) & EXPECTED_ALL_NEW_GOODS)

    if source_goods != EXPECTED_ALL_NEW_GOODS:
        missing = sorted(EXPECTED_ALL_NEW_GOODS - source_goods)
        extra = sorted(source_goods - EXPECTED_ALL_NEW_GOODS)
        raise ValueError(f"Workshop new-good set changed; missing={missing}, extra={extra}")

    for row in rows:
        workshop_id = str(row["workshop_id"])
        path, parsed = parsed_by_mod[workshop_id]
        good = str(row["good"])
        if good not in parsed:
            raise ValueError(f"{good} not found in {path}")
        source = parsed[good]
        if abs(float(source["price"]) - float(row["price"])) > EPSILON:
            raise ValueError(f"{good}: Workshop price differs from CSV")
        native = row["native"]
        assert isinstance(native, dict)
        for pop_type in POP_TYPES:
            source_value = float(source["add"][pop_type]) * float(source["mult"][pop_type])
            if abs(source_value - float(native[pop_type])) > EPSILON:
                raise ValueError(f"{good}: Workshop {pop_type} demand differs from CSV")
        if abs(_raw_slave_demand(path, good) - float(row["slaves"])) > EPSILON:
            raise ValueError(f"{good}: Workshop slave demand differs from CSV")

    for good in EXPECTED_EXCLUDED_GOODS:
        matches = [parsed[good] for _path, parsed in parsed_by_mod.values() if good in parsed]
        if len(matches) != 1:
            raise ValueError(f"Expected one Workshop definition for excluded good {good}")
        source = matches[0]
        if any(
            abs(float(source["add"][pop_type]) * float(source["mult"][pop_type])) > EPSILON
            for pop_type in POP_TYPES
        ):
            raise ValueError(f"Excluded Workshop good unexpectedly has pop demand: {good}")
    print("[OK] Workshop audit: 27 new goods, 22 demand goods, 5 excluded goods")


def _render_outputs(rows: List[Dict[str, object]]) -> Dict[Path, str]:
    return {
        GOODS_OUTPUT: _render_goods(rows),
        VALUES_OUTPUT: _render_values(rows),
        EFFECTS_OUTPUT: _render_effects(rows),
        LOCATION_GUI_OUTPUT: _render_gui(
            STABLE_LOCATION_GUI,
            "SOL_GUI_SECTION_LOCAL_GOODS",
            "sol_market_consumes",
            "Location.GetMarket.MakeScope",
            rows,
        ),
        SITUATION_GUI_OUTPUT: _render_gui(
            STABLE_SITUATION_GUI,
            "SOL_GUI_SECTION_COUNTRY_GOODS",
            "gls_country_consumes",
            "Player.MakeScope",
            rows,
        ),
    }


def _check(outputs: Dict[Path, str]) -> bool:
    ok = True
    for path, expected in outputs.items():
        relative = path.relative_to(REPO_ROOT)
        if not path.exists():
            print(f"[FAIL] Missing generated target: {relative}")
            ok = False
            continue
        if path.read_bytes()[:3] != UTF8_BOM:
            print(f"[FAIL] Missing UTF-8 BOM: {relative}")
            ok = False
            continue
        if _read(path) != expected:
            print(f"[FAIL] Out of date: {relative}")
            ok = False
            continue
        print(f"[OK] Up to date: {relative}")
    return ok


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SOL-JTG compatibility overrides.")
    parser.add_argument("--check", action="store_true", help="Check outputs without writing files.")
    parser.add_argument(
        "--audit-workshop-root",
        type=Path,
        help="Optionally verify the CSV against an installed EU5 Workshop content root.",
    )
    args = parser.parse_args()

    rows = _load_rows()
    if args.audit_workshop_root is not None:
        _audit_workshop(args.audit_workshop_root, rows)
    outputs = _render_outputs(rows)
    if args.check:
        raise SystemExit(0 if _check(outputs) else 1)

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(UTF8_BOM + content.encode("utf-8"))
        print(f"[gen_sol_jtg_compat] Wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
