#!/usr/bin/env python3
"""
Generate docs/knowledge/BRIEF.md from docs/knowledge/*.yaml.
Run after editing anti_patterns.yaml or valid_enums.yaml.

Usage:
  python scripts/gen_brief.py
"""

from datetime import date
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

try:
    import yaml
except ImportError:
    print("[ERROR] PyYAML not installed. Run: pip install pyyaml")
    raise SystemExit(1)

REPO_ROOT = Path(__file__).parent.parent
KNOWLEDGE_DIR = REPO_ROOT / "docs" / "knowledge"
OUTPUT = KNOWLEDGE_DIR / "BRIEF.md"
OVERVIEW = KNOWLEDGE_DIR / "PROJECT_OVERVIEW.md"


def load(filename: str):
    path = KNOWLEDGE_DIR / filename
    if not path.exists():
        return None
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def md_row(*cols: str) -> str:
    return "| " + " | ".join(str(c) for c in cols) + " |"


def main():
    anti_patterns = load("anti_patterns.yaml") or []
    enums = load("valid_enums.yaml") or {}

    lines: list[str] = []
    lines.append("# EU5 Knowledge Brief")
    lines.append("")
    lines.append(
        "> **Auto-generated** — do not edit this file directly.  "
    )
    lines.append(
        "> Edit `docs/knowledge/anti_patterns.yaml`, `valid_enums.yaml`, or `PROJECT_OVERVIEW.md`, "
        "then run `python scripts/gen_brief.py`.  "
    )
    lines.append(f"> Last updated: {date.today()}")
    lines.append("")

    # ── Project overview ──────────────────────────────────────────────────────
    if OVERVIEW.exists():
        overview_text = OVERVIEW.read_text(encoding="utf-8")
        # Skip the H1 title line and the blank line after it; keep everything else.
        body_lines = overview_text.splitlines()
        start = next((i for i, ln in enumerate(body_lines) if ln.startswith("## ")), 0)
        lines.append("\n".join(body_lines[start:]).strip())
        lines.append("")

    # ── Anti-patterns ────────────────────────────────────────────────────────
    lines.append("## Known Anti-Patterns")
    lines.append("")
    lines.append(md_row("Category", "Scope", "Bad Form", "Correct Form", "Notes"))
    lines.append(md_row("---", "---", "---", "---", "---"))
    for p in anti_patterns:
        lines.append(
            md_row(
                p.get("category", ""),
                p.get("scope", ""),
                p.get("bad", ""),
                p.get("correction", ""),
                p.get("notes", ""),
            )
        )
    lines.append("")

    # ── Valid enums ───────────────────────────────────────────────────────────
    lines.append("## Valid Enum Values")
    lines.append("")
    lines.append(md_row("Enum", "Valid Values", "Notes"))
    lines.append(md_row("---", "---", "---"))
    for enum_name, enum_data in enums.items():
        values = ", ".join(enum_data.get("values", []))
        notes = enum_data.get("notes", "")
        lines.append(md_row(enum_name, values, notes))
    lines.append("")

    # ── Quick-ref rules ───────────────────────────────────────────────────────
    lines.append("## Quick Reference Rules")
    lines.append("")
    lines.append("- **3-Step Rule**: Direct edit only if 100% certain → `reference_official_defines/` → `reference_game_files/` + `reference_mods/`")
    lines.append("- **Mandatory Step 2/3** for: `blockoverride` names, `custom_tooltip` keys, `situation_card_common` structure, `location_rank:*`, modifier names, scripted triggers/effects, localization YAML encoding, GUI expressions")
    lines.append("- **Verification format**: output `**Verification** — Step [2/3], Reference: file:line, Quote: \"exact text\"` before any code")
    lines.append("- **Bug fix rule**: Replace syntax with verified form; do NOT remove the feature")
    lines.append("- **Pre-test**: Run `python scripts/validate.py --changed` before launching game")
    lines.append("- **Float precision**: EU5 truncates all floats at 5 decimal places; never emit 6+ dp in mod files")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    overview_status = "with overview" if OVERVIEW.exists() else "no overview"
    print(f"[OK] Generated {OUTPUT.relative_to(REPO_ROOT)} ({len(anti_patterns)} patterns, {len(enums)} enums, {overview_status})")


if __name__ == "__main__":
    main()
