#!/usr/bin/env python3
"""
Generate SOL market unit-consumption constants and the yearly market spending
refresh block.

Inputs:
  data/demand_price_table.csv

Outputs:
  src/stable/in_game/common/script_values/SOL_market_unit_consumption_values.txt
  sol_refresh_market_pop_demand_maps block in A_SOL_economy_effects.txt
"""

import csv
import re
import sys
from pathlib import Path
from typing import Dict, List, Tuple

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parent.parent
INPUT_CSV = REPO_ROOT / "data" / "demand_price_table.csv"
VALUES_OUTPUT = REPO_ROOT / "src/stable/in_game/common/script_values/SOL_market_unit_consumption_values.txt"
EFFECTS_FILE = REPO_ROOT / "src/stable/in_game/common/scripted_effects/A_SOL_economy_effects.txt"

POP_TYPES: List[str] = ["nobles", "clergy", "burghers", "laborers", "peasants", "soldiers", "tribesmen"]
EPSILON = 1e-9


def _format_float(value: float) -> str:
    """EU5 reads at most five decimal places, so emit no extra precision."""
    rounded = round(value, 5)
    if abs(rounded) < 0.000005:
        return "0"
    text = f"{rounded:.5f}".rstrip("0").rstrip(".")
    return text or "0"


def _read_rows() -> List[Dict[str, str]]:
    with INPUT_CSV.open(encoding="utf-8-sig", newline="") as fh:
        return list(csv.DictReader(fh))


def _load_good_rows() -> List[Tuple[str, float, Dict[str, float]]]:
    """Return one row per good; duplicate legacy demand-group rows count once."""
    rows = _read_rows()
    seen: Dict[str, Tuple[float, Dict[str, float]]] = {}
    order: List[str] = []

    for row in rows:
        good = row["good"]
        price = float(row["price"])
        quantities = {pop_type: float(row.get(pop_type, "0") or 0) for pop_type in POP_TYPES}
        if good not in seen:
            seen[good] = (price, quantities)
            order.append(good)
            continue

        old_price, old_quantities = seen[good]
        if abs(old_price - price) > EPSILON:
            raise ValueError(f"{good}: duplicate rows disagree on price ({old_price} vs {price})")
        for pop_type in POP_TYPES:
            if abs(old_quantities[pop_type] - quantities[pop_type]) > EPSILON:
                raise ValueError(f"{good}: duplicate rows disagree on {pop_type} demand")

    return [(good, seen[good][0], seen[good][1]) for good in sorted(order)]


def _generate_values(good_rows: List[Tuple[str, float, Dict[str, float]]]) -> str:
    lines: List[str] = [
        "# @AUTOGENERATED by scripts/gen_market_unit_consumption.py - do not edit; run script to regenerate.",
        "### ============================================================",
        "### SECTION: SOL Market Unit Consumption Constants",
        "### ============================================================",
        "# Generated from data/demand_price_table.csv. Each value is net",
        "# demand_add quantity for one pop type and one good, with duplicate",
        "# legacy demand-group rows counted once. Yearly market spending",
        "# multiplies these quantities by min(market_price, default_price).",
        "",
    ]

    for pop_type in POP_TYPES:
        lines.append(f"### {pop_type}")
        wrote_any = False
        for good, _price, quantities in good_rows:
            quantity = quantities[pop_type]
            formatted = _format_float(quantity)
            if quantity <= EPSILON or formatted == "0":
                continue
            wrote_any = True
            lines.extend(
                [
                    f"sol_unit_consumption_{pop_type}_{good} = {{",
                    f"\tvalue = {formatted}",
                    "}",
                    "",
                ]
            )
        if not wrote_any:
            lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _consuming_pop_types(quantities: Dict[str, float]) -> List[str]:
    return [pop_type for pop_type in POP_TYPES if quantities[pop_type] > EPSILON and _format_float(quantities[pop_type]) != "0"]


def _generate_refresh_block(good_rows: List[Tuple[str, float, Dict[str, float]]]) -> str:
    lines: List[str] = [
        "sol_refresh_market_pop_demand_maps = {",
        "\t# Global scope. Refresh per-market unit spending and market-keyed goods counters.",
        "\t# Unit spending is hardcoded consumption quantity times min(market price, base price).",
        "\tevery_market_in_world = {",
        "\t\tsave_scope_as = sol_market_cache",
    ]

    for pop_type in POP_TYPES:
        lines.append(f"\t\tset_local_variable = {{ name = sol_market_{pop_type}_unit_spending value = 0 }}")
    lines.append("")

    for good, _price, quantities in good_rows:
        pop_types = _consuming_pop_types(quantities)
        if not pop_types:
            continue

        lines.extend(
            [
                f"\t\tset_local_variable = {{",
                f"\t\t\tname = sol_market_effective_price_{good}",
                f"\t\t\tvalue = {{",
                f"\t\t\t\tvalue = \"market_price(goods:{good})\"",
                f"\t\t\t\tmax = \"default_price(goods:{good})\"",
                f"\t\t\t}}",
                f"\t\t}}",
                f"\t\tset_local_variable = {{ name = sol_market_consumes_{good}_count value = \"goods_supply_in_market(goods:{good})\" }}",
                f"\t\tremove_from_global_variable_map = {{ name = sol_market_consumes_{good} key = scope:sol_market_cache }}",
                f"\t\tadd_to_global_variable_map = {{ name = sol_market_consumes_{good} key = scope:sol_market_cache value = local_var:sol_market_consumes_{good}_count }}",
                "\t\tif = {",
                f"\t\t\tlimit = {{ local_var:sol_market_consumes_{good}_count > 0 }}",
            ]
        )
        for pop_type in pop_types:
            lines.extend(
                [
                    "\t\t\tchange_local_variable = {",
                    f"\t\t\t\tname = sol_market_{pop_type}_unit_spending",
                    "\t\t\t\tadd = {",
                    f"\t\t\t\t\tvalue = sol_unit_consumption_{pop_type}_{good}",
                    f"\t\t\t\t\tmultiply = local_var:sol_market_effective_price_{good}",
                    "\t\t\t\t}",
                    "\t\t\t}",
                ]
            )
        lines.extend(["\t\t}", ""])

    for pop_type in POP_TYPES:
        lines.extend(
            [
                f"\t\tremove_from_global_variable_map = {{ name = sol_market_unit_spending_{pop_type} key = scope:sol_market_cache }}",
                f"\t\tadd_to_global_variable_map = {{ name = sol_market_unit_spending_{pop_type} key = scope:sol_market_cache value = local_var:sol_market_{pop_type}_unit_spending }}",
            ]
        )
    lines.extend(
        [
            "\t}",
            "\tset_global_variable = { name = sol_market_pop_demand_maps_initialized value = 1 }",
            "}",
        ]
    )
    return "\n".join(lines)


def _collect_brace_block(text: str, start: int) -> int:
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError("Unclosed brace block")


def _replace_effect_block(new_block: str) -> None:
    text = EFFECTS_FILE.read_text(encoding="utf-8-sig")
    match = re.search(r"\bsol_refresh_market_pop_demand_maps\s*=\s*\{", text)
    if not match:
        raise ValueError("Could not find sol_refresh_market_pop_demand_maps block")

    block_start = match.start()
    brace_start = text.index("{", match.start())
    block_end = _collect_brace_block(text, brace_start) + 1
    updated = text[:block_start] + new_block + text[block_end:]
    EFFECTS_FILE.write_text(updated, encoding="utf-8")


def main() -> None:
    good_rows = _load_good_rows()
    VALUES_OUTPUT.write_text(_generate_values(good_rows), encoding="utf-8")
    _replace_effect_block(_generate_refresh_block(good_rows))
    print(f"[gen_market_unit_consumption] Wrote {VALUES_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"[gen_market_unit_consumption] Updated sol_refresh_market_pop_demand_maps in {EFFECTS_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
