#!/usr/bin/env python3
"""Generate the stable/standalone SOL economy effects and country solver.

The output is emitted by Python code in :mod:`sol_economy_effects_source`.
Only data-dependent repetitions (currently the market refresh block) are
expanded from project data; the generator reads no external effect-source
text files at runtime.  The country linear solver is written separately so
the location-level aggregation file stays small and responsibility-focused.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

from gen_market_unit_consumption import (  # noqa: E402
    _generate_refresh_block,
    _load_good_rows,
)
from sol_country_demand_solver_source import (  # noqa: E402
    render_country_demand_aggregation,
    render_country_demand_solver,
)
from sol_economy_effects_source import render_static_sections  # noqa: E402

TARGET_NAMES = ("stable", "sol_standalone")
OUTPUT_RELATIVE = (
    "in_game",
    "common",
    "scripted_effects",
    "A_SOL_economy_effects.txt",
)
SOLVER_OUTPUT_RELATIVE = (
    "in_game",
    "common",
    "scripted_effects",
    "B_SOL_country_demand_solver.txt",
)
UTF8_BOM = b"\xef\xbb\xbf"

GENERATED_HEADER = (
    "# @AUTOGENERATED by scripts/gen_sol_economy_effects.py - "
    "do not edit; edit scripts/sol_economy_effects_source.py or "
    "scripts/sol_country_demand_solver_source.py and rerun "
    "gen_sol_chain.py.\n"
)


def _resolve_targets(target: str) -> list[str]:
    if target == "all":
        return list(TARGET_NAMES)
    if target in TARGET_NAMES:
        return [target]
    raise ValueError(f"Unknown target: {target}")


def _output_path(target: str) -> Path:
    return REPO_ROOT / "src" / target / Path(*OUTPUT_RELATIVE)


def _solver_output_path(target: str) -> Path:
    return REPO_ROOT / "src" / target / Path(*SOLVER_OUTPUT_RELATIVE)


def _write_utf8_bom(path: Path, text: str) -> None:
    path.write_bytes(UTF8_BOM + text.encode("utf-8"))


def _has_utf8_bom(path: Path) -> bool:
    try:
        return path.read_bytes().startswith(UTF8_BOM)
    except FileNotFoundError:
        return False


def _render_target(target: str) -> tuple[str, str]:
    good_rows = _load_good_rows()
    refresh_block = _generate_refresh_block(good_rows)
    aggregation = render_country_demand_aggregation()
    economy = GENERATED_HEADER + render_static_sections(
        target,
        refresh_block,
        aggregation,
    )
    solver = GENERATED_HEADER + render_country_demand_solver()
    return economy, solver


def _check_target(target: str) -> bool:
    output_path = _output_path(target)
    solver_output_path = _solver_output_path(target)
    if not output_path.exists():
        print(f"[FAIL] Missing generated target: {output_path.relative_to(REPO_ROOT)}")
        return False
    if not solver_output_path.exists():
        print(
            f"[FAIL] Missing generated target: "
            f"{solver_output_path.relative_to(REPO_ROOT)}"
        )
        return False

    ok = True
    if not _has_utf8_bom(output_path):
        print(f"[FAIL] Missing UTF-8 BOM: {output_path.relative_to(REPO_ROOT)}")
        ok = False
    if not _has_utf8_bom(solver_output_path):
        print(
            f"[FAIL] Missing UTF-8 BOM: "
            f"{solver_output_path.relative_to(REPO_ROOT)}"
        )
        ok = False

    expected_economy, expected_solver = _render_target(target)
    actual_economy = output_path.read_text(encoding="utf-8-sig")
    actual_solver = solver_output_path.read_text(encoding="utf-8-sig")
    if actual_economy != expected_economy:
        print(f"[FAIL] Out of date: {output_path.relative_to(REPO_ROOT)}")
        ok = False
    if actual_solver != expected_solver:
        print(
            f"[FAIL] Out of date: "
            f"{solver_output_path.relative_to(REPO_ROOT)}"
        )
        ok = False

    if ok:
        print(
            f"[OK] Up to date: {output_path.relative_to(REPO_ROOT)} and "
            f"{solver_output_path.relative_to(REPO_ROOT)}"
        )
    return ok


def _write_target(target: str) -> None:
    output_path = _output_path(target)
    solver_output_path = _solver_output_path(target)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    solver_output_path.parent.mkdir(parents=True, exist_ok=True)
    economy, solver = _render_target(target)
    _write_utf8_bom(output_path, economy)
    _write_utf8_bom(solver_output_path, solver)
    print(
        "[gen_sol_economy_effects] Wrote "
        f"{output_path.relative_to(REPO_ROOT)} and "
        f"{solver_output_path.relative_to(REPO_ROOT)}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate stable/standalone SOL economy scripted effects."
    )
    parser.add_argument(
        "--target",
        choices=[*TARGET_NAMES, "all"],
        default="all",
        help="Output target to update/check (default: all).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Return non-zero if generated target files are out of date.",
    )
    args = parser.parse_args()

    targets = _resolve_targets(args.target)
    if args.check:
        ok = all(_check_target(target) for target in targets)
        raise SystemExit(0 if ok else 1)

    for target in targets:
        _write_target(target)


if __name__ == "__main__":
    main()
