#!/usr/bin/env python3
"""Generate SOL-PP compatibility overrides from stable SOL and PP sources."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(REPO_ROOT))

from gen_market_unit_consumption import (  # noqa: E402
    EPSILON,
    POP_TYPES,
    _find_effect_block,
    _format_float,
    _generate_refresh_block,
    _generate_values,
    _load_good_rows,
)
from tools.sol_demand_simulator.parser import (  # noqa: E402
    _collect_brace_block,
    _expand_demand_add,
    _find_sub_block,
    _parse_kv_block,
    _parse_inject_file,
    _parse_vanilla_goods_file,
    load_vanilla_goods,
)

TARGET_ROOT = REPO_ROOT / "src" / "sol_pp_compatibility_submod"
STABLE_ROOT = REPO_ROOT / "src" / "stable"
PP_ROOT = REPO_ROOT / "reference_mods" / "3613232232"

PP_VICTUALS_FILE = PP_ROOT / "in_game" / "common" / "goods" / "pp_goods_victuals.txt"
PP_LUMBER_FILE = PP_ROOT / "in_game" / "common" / "goods" / "pp_goods_adjustments.txt"
PP_ROAD_PRICES = PP_ROOT / "in_game" / "common" / "prices" / "pp_road_gold_adjustments.txt"
STABLE_POP_GOODS = STABLE_ROOT / "in_game" / "common" / "goods" / "z_SOL_pop_goods.txt"
STABLE_EFFECTS = STABLE_ROOT / "in_game" / "common" / "scripted_effects" / "A_SOL_economy_effects.txt"
STABLE_CMM_EFFECTS = STABLE_ROOT / "in_game" / "common" / "scripted_effects" / "SOL_cmm_effects.txt"
STABLE_AUTO_MODIFIERS = STABLE_ROOT / "in_game" / "common" / "auto_modifiers" / "SOL_economy_auto_modifiers.txt"
STABLE_STATIC_MODIFIERS = STABLE_ROOT / "main_menu" / "common" / "static_modifiers" / "A_SOL_economy_modifiers.txt"
STABLE_WAR_STATIC_MODIFIERS = STABLE_ROOT / "main_menu" / "common" / "static_modifiers" / "A_SOL_war_modifiers.txt"
STABLE_PRICES = STABLE_ROOT / "in_game" / "common" / "prices" / "A_SOL_economy_prices.txt"
STABLE_LOCATION_GUI = STABLE_ROOT / "in_game" / "gui" / "SOL_economy_local.gui"
STABLE_SITUATION_GUI = STABLE_ROOT / "in_game" / "gui" / "panels" / "situation" / "global_living_standard.gui"

VALUES_OUTPUT = TARGET_ROOT / "in_game" / "common" / "script_values" / "zz_SOL_market_unit_consumption_values.txt"
EFFECTS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "scripted_effects" / "zz_A_SOL_economy_effects.txt"
LUMBER_OUTPUT = TARGET_ROOT / "in_game" / "common" / "goods" / "zz_SOL_PP_lumber_demand.txt"
LOCATION_GUI_OUTPUT = TARGET_ROOT / "in_game" / "gui" / "zz_SOL_economy_local.gui"
SITUATION_GUI_OUTPUT = TARGET_ROOT / "in_game" / "gui" / "panels" / "situation" / "global_living_standard.gui"
AUTO_MODIFIERS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "auto_modifiers" / "zz_SOL_PP_compact_economy_auto_modifiers.txt"
CMM_EFFECTS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "scripted_effects" / "zz_SOL_PP_compact_cmm_effects.txt"
CMM_TRIGGERS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "scripted_triggers" / "zz_SOL_PP_compact_disabled_triggers.txt"
PRICE_CLEANUP_OUTPUT = TARGET_ROOT / "in_game" / "common" / "prices" / "zz_SOL_PP_compact_price_cleanup.txt"
STATIC_CLEANUP_OUTPUT = TARGET_ROOT / "main_menu" / "common" / "static_modifiers" / "zz_SOL_PP_compact_static_cleanup.txt"
WAR_OVERLAP_CLEANUP_OUTPUT = TARGET_ROOT / "main_menu" / "common" / "static_modifiers" / "zz_SOL_PP_compact_war_overlap_cleanup.txt"
WEATHER_OUTPUT = TARGET_ROOT / "in_game" / "common" / "static_modifiers" / "zz_SOL_PP_weather_modifiers.txt"
LIA_OUTPUT = TARGET_ROOT / "main_menu" / "common" / "static_modifiers" / "zz_SOL_PP_lia_modifiers.txt"

UTF8_BOM = b"\xef\xbb\xbf"
GENERATED_HEADER = "# @AUTOGENERATED by scripts/gen_sol_pp_compat.py - do not edit; run script to regenerate.\n"

AGE_FIELDS = (
    "global_build_buildings_efficiency",
    "city_upgrade_cost_modifier",
    "town_upgrade_cost_modifier",
)
AGE_NAMES = (
    (1, "age_1_traditions"),
    (2, "age_2_renaissance"),
    (3, "age_3_discovery"),
    (4, "age_4_reformation"),
    (5, "age_5_absolutism"),
    (6, "age_6_revolutions"),
)
ROAD_PRICE_KEYS = (
    "build_gravel_road",
    "build_paved_road",
    "build_modern_road",
    "build_railroad",
)
LIA_KEYS = (
    "harsh_winters_modifier",
    "reduced_wool_production_modifier",
    "fewer_fisheries_modifier",
    "livestock_suffers_modifier",
    "wineries_suffering_modifier",
    "great_frost_modifier",
    "short_harvest_modifier",
    "recent_white_storm_modifier",
)
WEATHER_KEYS = ("winter_mild", "winter_normal")
PP_OWNED_WAR_LOCATION_KEYS = (
    "is_blockaded_by_enemies",
    "under_siege",
    "is_occupied",
    "looted",
)
VISIBLE_CMM_SETTINGS = (
    "sol_on",
    "sol_map",
    "as_on",
    "bte",
    "ae",
    "cts",
    "ds",
    "difficulty",
    "ai_pr",
    "hw_on",
    "iwe",
    "hwe",
    "rwe",
)
HIDDEN_CMM_SETTINGS = ("gdp_dev",)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def _find_named_block(path: Path, key: str) -> str:
    text = _read(path)
    match = re.search(
        rf"(?m)^(?:(?:TRY_)?(?:INJECT|REPLACE):)?{re.escape(key)}\s*=\s*\{{",
        text,
    )
    if not match:
        raise ValueError(f"{key} block not found in {path}")
    brace_start = text.index("{", match.start())
    block, _end = _collect_brace_block(text, brace_start)
    return block


def _numeric_fields(path: Path, key: str) -> List[Tuple[str, float]]:
    block = _find_named_block(path, key)
    fields: List[Tuple[str, float]] = []
    for match in re.finditer(
        r"(?m)^\s*([A-Za-z0-9_]+)\s*=\s*(-?(?:\d+(?:\.\d*)?|\.\d+))\s*(?:#.*)?$",
        block,
    ):
        fields.append((match.group(1), float(match.group(2))))
    if not fields:
        raise ValueError(f"No numeric fields found in {key} block from {path}")
    return fields


def _field_value(path: Path, key: str, field: str) -> Optional[float]:
    values = dict(_numeric_fields(path, key))
    return values.get(field)


def _render_inverse_injections(path: Path, keys: Tuple[str, ...], purpose: str) -> str:
    lines = [GENERATED_HEADER.rstrip(), purpose]
    for key in keys:
        lines.extend(["", f"TRY_INJECT:{key} = {{"])
        for field, value in _numeric_fields(path, key):
            lines.append(f"\t{field} = {_format_float(-value)}")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _victuals_row() -> Tuple[str, float, Dict[str, float]]:
    parsed = _parse_vanilla_goods_file(PP_VICTUALS_FILE)
    try:
        victuals = parsed["victuals"]
    except KeyError as exc:
        raise ValueError(f"victuals definition not found in {PP_VICTUALS_FILE}") from exc

    quantities = {
        pop_type: victuals["add"][pop_type] * victuals["mult"][pop_type]
        for pop_type in POP_TYPES
    }
    return "victuals", float(victuals["price"]), quantities


def _compat_good_rows() -> List[Tuple[str, float, Dict[str, float]]]:
    rows: List[Tuple[str, float, Dict[str, float]]] = []
    found_lumber = False
    for good, price, quantities in _load_good_rows():
        if good == "victuals":
            raise ValueError("Base SOL demand table must not contain PP-only victuals")
        if good == "lumber":
            found_lumber = True
            quantities = {pop_type: 0.0 for pop_type in POP_TYPES}
        rows.append((good, price, quantities))

    if not found_lumber:
        raise ValueError("Base SOL demand table does not contain lumber")
    rows.append(_victuals_row())
    return sorted(rows, key=lambda row: row[0])


def _render_values(rows: List[Tuple[str, float, Dict[str, float]]]) -> str:
    text = _generate_values(rows)
    text = text.replace(
        "# @AUTOGENERATED by scripts/gen_market_unit_consumption.py - do not edit; run script to regenerate.\n",
        GENERATED_HEADER,
        1,
    )
    text = text.replace(
        "# Generated from data/demand_price_table.csv. Each value is net\n",
        "# Generated from the SOL demand table plus PP victuals demand. Lumber is\n"
        "# intentionally omitted because the compatibility stack sets it to zero.\n"
        "# Each value is net\n",
        1,
    )
    return text


def _parse_injected_demand_add(path: Path, good: str) -> Dict[str, float]:
    text = _read(path)
    match = re.search(rf"\b(?:TRY_)?INJECT:{re.escape(good)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"{good} injection not found in {path}")
    brace_start = text.index("{", match.start())
    block, _end = _collect_brace_block(text, brace_start)
    demand_add = _find_sub_block(block, "demand_add")
    if demand_add is None:
        raise ValueError(f"{good} demand_add not found in {path}")
    return _expand_demand_add(_parse_kv_block(demand_add))


def _parse_development_threshold(path: Path, good: str) -> Optional[float]:
    text = _read(path)
    match = re.search(rf"(?m)^{re.escape(good)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"{good} definition not found in {path}")
    brace_start = text.index("{", match.start())
    block, _end = _collect_brace_block(text, brace_start)
    threshold = re.search(r"\bdevelopment_threshold\s*=\s*(-?[\d.]+)", block)
    return float(threshold.group(1)) if threshold else None


def _render_goods_injections() -> str:
    inject = _parse_inject_file(STABLE_POP_GOODS).get("lumber")
    if not inject:
        raise ValueError(f"SOL lumber injection not found in {STABLE_POP_GOODS}")

    vanilla = load_vanilla_goods()["lumber"]
    pp_add = _parse_injected_demand_add(PP_LUMBER_FILE, "lumber")
    pre_compat = {
        pop_type: (
            vanilla["add"][pop_type] * vanilla["mult"][pop_type]
            + inject["inject_add"].get(pop_type, 0.0)
            + pp_add.get(pop_type, 0.0)
        )
        for pop_type in POP_TYPES
    }
    corrections = {pop_type: -value for pop_type, value in pre_compat.items()}
    for pop_type in POP_TYPES:
        final = pre_compat[pop_type] + corrections[pop_type]
        if abs(final) > EPSILON:
            raise ValueError(f"lumber demand correction failed for {pop_type}: {final}")
    lines = [
        GENERATED_HEADER.rstrip(),
        "# PP cancels vanilla lumber pop demand after SOL has added its calibrated",
        "# adjustment. This third demand_add cancels the remaining SOL adjustment,",
        "# leaving final lumber pop demand at exactly zero.",
        "INJECT:lumber = {",
        "\tdemand_add = {",
    ]
    for pop_type in POP_TYPES:
        value = corrections[pop_type]
        if abs(value) <= EPSILON:
            continue
        lines.append(f"\t\t{pop_type} = {_format_float(value)}")
    lines.extend(["\t}", "}", ""])

    victuals_threshold = _parse_development_threshold(PP_VICTUALS_FILE, "victuals")
    if victuals_threshold is not None:
        lines.extend([
            "# PP adds its own development gate to victuals. Negate it so every",
            "# pop-demand good remains independent of location development.",
            "INJECT:victuals = {",
            f"\tdevelopment_threshold = {_format_float(-victuals_threshold)}",
            "}",
            "",
        ])
    return "\n".join(lines)


def _market_reset(good: str, value: int) -> str:
    return (
        f"\t\tremove_from_global_variable_map = {{ name = sol_market_consumes_{good} key = scope:sol_market_cache }}\n"
        f"\t\tadd_to_global_variable_map = {{ name = sol_market_consumes_{good} key = scope:sol_market_cache value = {value} }}"
    )


def _country_market_check(good: str) -> str:
    return (
        "\t\tif = {\n"
        "\t\t\tlimit = {\n"
        f"\t\t\t\thas_global_variable_map = sol_market_consumes_{good}\n"
        f"\t\t\t\tis_key_in_global_variable_map = {{ name = sol_market_consumes_{good} target = scope:gls_panel_market }}\n"
        f"\t\t\t\t\"global_variable_map(sol_market_consumes_{good}|scope:gls_panel_market)\" > 0\n"
        "\t\t\t}\n"
        f"\t\t\tremove_from_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country }}\n"
        f"\t\t\tadd_to_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country value = 1 }}\n"
        "\t\t}"
    )


def _replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"Expected one {label} anchor, found {count}")
    return text.replace(old, new, 1)


def _render_effects(rows: List[Tuple[str, float, Dict[str, float]]]) -> str:
    text = _read(STABLE_EFFECTS)
    refresh = _generate_refresh_block(rows)
    save_scope = "\t\tsave_scope_as = sol_market_cache"
    refresh = _replace_once(
        refresh,
        save_scope,
        save_scope + "\n\n\t\t# PP requires final lumber pop demand to be zero. Clear saved-map residue.\n" + _market_reset("lumber", 0),
        "market cache scope",
    )
    block_start, block_end = _find_effect_block(text)
    text = text[:block_start] + refresh + text[block_end:]

    lumber_init = (
        "\tremove_from_global_variable_map = { name = gls_country_consumes_lumber key = scope:gls_panel_country }\n"
        "\tadd_to_global_variable_map = { name = gls_country_consumes_lumber key = scope:gls_panel_country value = 0 }"
    )
    victuals_init = (
        "\tremove_from_global_variable_map = { name = gls_country_consumes_victuals key = scope:gls_panel_country }\n"
        "\tadd_to_global_variable_map = { name = gls_country_consumes_victuals key = scope:gls_panel_country value = 0 }"
    )
    text = _replace_once(text, lumber_init, lumber_init + "\n" + victuals_init, "country goods reset")

    lumber_check = _country_market_check("lumber")
    text = _replace_once(
        text,
        lumber_check,
        lumber_check + "\n" + _country_market_check("victuals"),
        "country market aggregation",
    )

    lumber_count = (
        "\tif = { limit = { \"global_variable_map(gls_country_consumes_lumber|scope:gls_panel_country)\" > 0 } "
        "change_local_variable = { name = gls_country_consumed_goods_count add = 1 } }"
    )
    victuals_count = lumber_count.replace("lumber", "victuals")
    text = _replace_once(text, lumber_count, lumber_count + "\n" + victuals_count, "country goods count")
    return GENERATED_HEADER + text


def _victuals_widget(variable_map: str, scope: str, indent: str) -> str:
    return (
        f'{indent}widget = {{ size = {{ 34 30 }} tooltip = "victuals" '
        'icon = { size = { 24 24 } parentanchor = center texture = "gfx/interface/icons/trade_goods/icon_goods_victuals.dds" } '
        f'text_single = {{ size = {{ 100% 100% }} align = center raw_text = "@trigger_no!" fontsize = 23 '
        f'visible = "[Not(GreaterThan_CFixedPoint(GetVariableFromGlobalVariableMap(\'{variable_map}\', {scope}).GetValue,\'(CFixedPoint)0\'))]" }} }}'
    )


def _render_gui(source: Path, variable_map: str, scope: str) -> str:
    text = _read(source)
    weaponry_lines = [line for line in text.splitlines() if 'tooltip = "weaponry"' in line]
    if len(weaponry_lines) != 1:
        raise ValueError(f"Expected one weaponry widget in {source}, found {len(weaponry_lines)}")
    weaponry = weaponry_lines[0]
    indent = weaponry[: len(weaponry) - len(weaponry.lstrip())]
    victuals = _victuals_widget(variable_map, scope, indent)
    return GENERATED_HEADER + _replace_once(text, weaponry, victuals + "\n" + weaponry, "weaponry widget")


def _render_auto_modifiers() -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# Compact SOL keeps only construction efficiency and city/town upgrade",
        "# costs from age escalation. Difficulty tax adjustments and AI devastation",
        "# recovery continue to use the full SOL definitions.",
    ]

    for age, age_key in AGE_NAMES:
        source_key = f"sol_ae_age_{age}_mod"
        lines.extend([
            "",
            f"REPLACE:{source_key} = {{",
            "\tpotential_trigger = {",
            "\t\texists = yes",
            "\t\tsol_as_is_on = yes",
            "\t\tsol_ae_is_on = yes",
            f"\t\tcurrent_age = {age_key}",
            "\t}",
        ])
        for field in AGE_FIELDS:
            value = _field_value(STABLE_AUTO_MODIFIERS, source_key, field)
            if value is not None:
                lines.append(f"\t{field} = {_format_float(value)}")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _render_static_cleanup() -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# Remove SOL's location-base rebalance while preserving PP's independently",
        "# injected location values. The low-control construction penalty is kept.",
        "",
        "TRY_INJECT:location_base_values = {",
    ]
    for field, value in _numeric_fields(STABLE_STATIC_MODIFIERS, "location_base_values"):
        lines.append(f"\t{field} = {_format_float(-value)}")
    lines.append("}")

    lines.extend([
        "",
        "# Compact tooltip objects used by the retained age notifications.",
    ])
    for age, _age_key in AGE_NAMES:
        source_key = f"sol_ae_age_{age}_modifier"
        lines.extend([
            "",
            f"REPLACE:{source_key} = {{",
            "\tgame_data = {",
            "\t\tcategory = country",
            "\t}",
        ])
        for field in AGE_FIELDS:
            value = _field_value(STABLE_STATIC_MODIFIERS, source_key, field)
            if value is not None:
                lines.append(f"\t{field} = {_format_float(value)}")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _render_price_cleanup() -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# PP owns shared road prices in the compact stack. Cancel only SOL's",
        "# additive road deltas, leaving vanilla plus PP's deltas as the final values.",
    ]
    for key in ROAD_PRICE_KEYS:
        pp_fields = dict(_numeric_fields(PP_ROAD_PRICES, key))
        if "gold" not in pp_fields:
            raise ValueError(f"PP gold delta missing for {key} in {PP_ROAD_PRICES}")
        sol_gold = _field_value(STABLE_PRICES, key, "gold")
        if sol_gold is None:
            raise ValueError(f"SOL gold delta missing for {key} in {STABLE_PRICES}")
        lines.extend([
            "",
            f"TRY_INJECT:{key} = {{",
            f"\tgold = {_format_float(-sol_gold)}",
            "}",
        ])
    lines.append("")
    return "\n".join(lines)


def _append_bool_setting(
    lines: List[str], setting_id: str, tab_id: str, group_id: str,
    alias: str, add_scripted_gui: bool = True,
) -> None:
    lines.extend([
        "\tcmm_register_global_bool_setting = {",
        "\t\tmod_id = sol",
        f"\t\tsetting_id = {setting_id}",
        f"\t\ttab_id = {tab_id}",
        f"\t\tgroup_id = {group_id}",
        "\t\tdefault_value = 1",
        "\t}",
        "\tcmm_sync_bool_alias = {",
        f"\t\tsetting = sol__{setting_id}",
        f"\t\talias = {alias}",
        "\t}",
    ])
    if add_scripted_gui:
        lines.extend([
            "\tcmm_add_scripted_gui = {",
            "\t\tmod_id = sol",
            f"\t\tsetting_id = {setting_id}",
            "\t}",
        ])
    lines.append("")


def _append_slider_setting(
    lines: List[str], setting_id: str, alias: str, default: str,
    minimum: str, maximum: str, step: str,
) -> None:
    lines.extend([
        "\tcmm_register_global_slider_setting = {",
        "\t\tmod_id = sol",
        f"\t\tsetting_id = {setting_id}",
        "\t\ttab_id = feat",
        "\t\tgroup_id = as",
        f"\t\tdefault_value = {default}",
        f"\t\tmin_value = {minimum}",
        f"\t\tmax_value = {maximum}",
        f"\t\tstep_value = {step}",
        "\t}",
        "\tcmm_sync_setting_alias = {",
        f"\t\tsetting = sol__{setting_id}",
        f"\t\talias = {alias}",
        "\t}",
        "\tcmm_add_scripted_gui = {",
        "\t\tmod_id = sol",
        f"\t\tsetting_id = {setting_id}",
        "\t}",
        "",
    ])


def _append_callback(lines: List[str], setting_id: str, alias: str, numeric: bool = False) -> None:
    sync_effect = "cmm_sync_setting_alias" if numeric else "cmm_sync_bool_alias"
    lines.extend([
        f"\t\tflag:sol__{setting_id} = {{",
        f"\t\t\t{sync_effect} = {{",
        f"\t\t\t\tsetting = sol__{setting_id}",
        f"\t\t\t\talias = {alias}",
        "\t\t\t}",
    ])
    if setting_id == "sol_on":
        lines.extend([
            "\t\t\tif = {",
            "\t\t\t\tlimit = { has_global_variable = sol_sol_on_enabled }",
            "\t\t\t\tgls_recalculate_global_living_standard = yes",
            "\t\t\t}",
        ])
    lines.append("\t\t}")


def _render_cmm_effects() -> str:
    source = _read(STABLE_CMM_EFFECTS)
    for setting_id in ("difficulty", "gdp_dev", "ai_pr"):
        if f"setting_id = {setting_id}" not in source:
            raise ValueError(f"Source CMM setting {setting_id} missing from {STABLE_CMM_EFFECTS}")

    lines = [
        GENERATED_HEADER.rstrip(),
        "# Replace full SOL registration with the compact PP-compatible feature set.",
        "REPLACE:sol_register_cmf_mod = {",
    ]
    _append_bool_setting(lines, "sol_on", "feat", "sol", "sol_sol_on_enabled", False)
    _append_bool_setting(lines, "sol_map", "feat", "sol", "sol_sol_map_enabled")
    _append_bool_setting(lines, "as_on", "feat", "as", "sol_as_enabled", False)
    _append_slider_setting(lines, "bte", "sol_bte", "-15", "-30", "30", "1")
    _append_bool_setting(lines, "ae", "feat", "as", "sol_ae_enabled")
    _append_slider_setting(lines, "cts", "sol_cts", "-5", "-20", "0", "1")
    _append_slider_setting(lines, "ds", "sol_ds", "-5", "-20", "0", "1")
    _append_bool_setting(lines, "difficulty", "feat", "as", "sol_difficulty_enabled")
    _append_slider_setting(lines, "ai_pr", "sol_ai_pr", "0.5", "0", "2", "0.1")
    _append_bool_setting(lines, "hw_on", "feat", "hw", "sol_hw_enabled", False)
    _append_bool_setting(lines, "iwe", "feat", "hw", "sol_iwe_enabled")
    _append_bool_setting(lines, "hwe", "feat", "hw", "sol_hwe_enabled")
    _append_bool_setting(lines, "rwe", "feat", "hw", "sol_rwe_enabled")
    if lines[-1] == "":
        lines.pop()
    lines.extend(["}", "", "REPLACE:sol_handle_cmf_callback = {", "\tswitch = {", "\t\ttrigger = var:cmf_callback"])
    for setting_id, alias, numeric in (
        ("sol_on", "sol_sol_on_enabled", False),
        ("sol_map", "sol_sol_map_enabled", False),
        ("as_on", "sol_as_enabled", False),
        ("bte", "sol_bte", True),
        ("ae", "sol_ae_enabled", False),
        ("cts", "sol_cts", True),
        ("ds", "sol_ds", True),
        ("difficulty", "sol_difficulty_enabled", False),
        ("ai_pr", "sol_ai_pr", True),
        ("hw_on", "sol_hw_enabled", False),
        ("iwe", "sol_iwe_enabled", False),
        ("hwe", "sol_hwe_enabled", False),
        ("rwe", "sol_rwe_enabled", False),
    ):
        _append_callback(lines, setting_id, alias, numeric)
    lines.extend(["\t}", "}", ""])
    rendered = "\n".join(lines)
    for setting_id in VISIBLE_CMM_SETTINGS:
        if f"setting_id = {setting_id}" not in rendered:
            raise ValueError(f"Active compact CMM setting is not registered: {setting_id}")
    for setting_id in HIDDEN_CMM_SETTINGS:
        if f"setting_id = {setting_id}" in rendered or f"flag:sol__{setting_id}" in rendered:
            raise ValueError(f"Disabled compact CMM setting is still visible: {setting_id}")
    return rendered


def _render_disabled_triggers() -> str:
    return GENERATED_HEADER + """# Removed compact features remain hard-disabled even for old saves that still
# contain their former CMF alias variables.
REPLACE:sol_gdp_dev_is_on = {
\talways = no
}
"""


def _render_outputs() -> Dict[Path, str]:
    rows = _compat_good_rows()
    return {
        VALUES_OUTPUT: _render_values(rows),
        EFFECTS_OUTPUT: _render_effects(rows),
        LUMBER_OUTPUT: _render_goods_injections(),
        LOCATION_GUI_OUTPUT: _render_gui(
            STABLE_LOCATION_GUI,
            "sol_market_consumes_victuals",
            "Location.GetMarket.MakeScope",
        ),
        SITUATION_GUI_OUTPUT: _render_gui(
            STABLE_SITUATION_GUI,
            "gls_country_consumes_victuals",
            "Player.MakeScope",
        ),
        AUTO_MODIFIERS_OUTPUT: _render_auto_modifiers(),
        CMM_EFFECTS_OUTPUT: _render_cmm_effects(),
        CMM_TRIGGERS_OUTPUT: _render_disabled_triggers(),
        PRICE_CLEANUP_OUTPUT: _render_price_cleanup(),
        STATIC_CLEANUP_OUTPUT: _render_static_cleanup(),
        WAR_OVERLAP_CLEANUP_OUTPUT: _render_inverse_injections(
            STABLE_WAR_STATIC_MODIFIERS,
            PP_OWNED_WAR_LOCATION_KEYS,
            "# PP owns these shared local war-state modifiers in the compact stack.",
        ),
        WEATHER_OUTPUT: _render_inverse_injections(
            STABLE_STATIC_MODIFIERS,
            WEATHER_KEYS,
            "# Restore PP's weather values by removing only SOL's winter deltas.",
        ),
        LIA_OUTPUT: _render_inverse_injections(
            STABLE_STATIC_MODIFIERS,
            LIA_KEYS,
            "# Restore PP's Little Ice Age values by removing only SOL's deltas.",
        ),
    }


def _check(outputs: Dict[Path, str]) -> bool:
    ok = True
    for path, expected in outputs.items():
        relative = path.relative_to(REPO_ROOT)
        if not path.exists():
            print(f"[FAIL] Missing generated target: {relative}")
            ok = False
            continue
        if path.read_bytes()[:3] != UTF8_BOM:
            print(f"[FAIL] Missing UTF-8 BOM: {relative}")
            ok = False
            continue
        if _read(path) != expected:
            print(f"[FAIL] Out of date: {relative}")
            ok = False
            continue
        print(f"[OK] Up to date: {relative}")
    return ok


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SOL-PP compatibility overrides.")
    parser.add_argument("--check", action="store_true", help="Check outputs without writing files.")
    args = parser.parse_args()

    outputs = _render_outputs()
    if args.check:
        raise SystemExit(0 if _check(outputs) else 1)

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(UTF8_BOM + content.encode("utf-8"))
        print(f"[gen_sol_pp_compat] Wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
