#!/usr/bin/env python3
"""Generate SOL-PP compatibility overrides from stable SOL and PP sources."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(REPO_ROOT))

from gen_market_unit_consumption import (  # noqa: E402
    EPSILON,
    POP_TYPES,
    _find_effect_block,
    _format_float,
    _generate_refresh_block,
    _generate_values,
    _load_good_rows,
)
from tools.sol_demand_simulator.parser import (  # noqa: E402
    _collect_brace_block,
    _expand_demand_add,
    _find_sub_block,
    _parse_kv_block,
    _parse_inject_file,
    _parse_vanilla_goods_file,
    load_vanilla_goods,
)

TARGET_ROOT = REPO_ROOT / "src" / "sol_pp_compatibility_submod"
STABLE_ROOT = REPO_ROOT / "src" / "stable"
PP_ROOT = REPO_ROOT / "reference_mods" / "3613232232"

PP_VICTUALS_FILE = PP_ROOT / "in_game" / "common" / "goods" / "pp_goods_victuals.txt"
PP_LUMBER_FILE = PP_ROOT / "in_game" / "common" / "goods" / "pp_goods_adjustments.txt"
STABLE_POP_GOODS = STABLE_ROOT / "in_game" / "common" / "goods" / "z_SOL_pop_goods.txt"
STABLE_EFFECTS = STABLE_ROOT / "in_game" / "common" / "scripted_effects" / "A_SOL_economy_effects.txt"
STABLE_LOCATION_GUI = STABLE_ROOT / "in_game" / "gui" / "SOL_economy_local.gui"
STABLE_SITUATION_GUI = STABLE_ROOT / "in_game" / "gui" / "panels" / "situation" / "global_living_standard.gui"

VALUES_OUTPUT = TARGET_ROOT / "in_game" / "common" / "script_values" / "zz_SOL_market_unit_consumption_values.txt"
EFFECTS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "scripted_effects" / "zz_A_SOL_economy_effects.txt"
LUMBER_OUTPUT = TARGET_ROOT / "in_game" / "common" / "goods" / "zz_SOL_PP_lumber_demand.txt"
LOCATION_GUI_OUTPUT = TARGET_ROOT / "in_game" / "gui" / "zz_SOL_economy_local.gui"
SITUATION_GUI_OUTPUT = TARGET_ROOT / "in_game" / "gui" / "panels" / "situation" / "global_living_standard.gui"

UTF8_BOM = b"\xef\xbb\xbf"
GENERATED_HEADER = "# @AUTOGENERATED by scripts/gen_sol_pp_compat.py - do not edit; run script to regenerate.\n"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def _victuals_row() -> Tuple[str, float, Dict[str, float]]:
    parsed = _parse_vanilla_goods_file(PP_VICTUALS_FILE)
    try:
        victuals = parsed["victuals"]
    except KeyError as exc:
        raise ValueError(f"victuals definition not found in {PP_VICTUALS_FILE}") from exc

    quantities = {
        pop_type: victuals["add"][pop_type] * victuals["mult"][pop_type]
        for pop_type in POP_TYPES
    }
    return "victuals", float(victuals["price"]), quantities


def _compat_good_rows() -> List[Tuple[str, float, Dict[str, float]]]:
    rows: List[Tuple[str, float, Dict[str, float]]] = []
    found_lumber = False
    for good, price, quantities in _load_good_rows():
        if good == "victuals":
            raise ValueError("Base SOL demand table must not contain PP-only victuals")
        if good == "lumber":
            found_lumber = True
            quantities = {pop_type: 0.0 for pop_type in POP_TYPES}
        rows.append((good, price, quantities))

    if not found_lumber:
        raise ValueError("Base SOL demand table does not contain lumber")
    rows.append(_victuals_row())
    return sorted(rows, key=lambda row: row[0])


def _render_values(rows: List[Tuple[str, float, Dict[str, float]]]) -> str:
    text = _generate_values(rows)
    text = text.replace(
        "# @AUTOGENERATED by scripts/gen_market_unit_consumption.py - do not edit; run script to regenerate.\n",
        GENERATED_HEADER,
        1,
    )
    text = text.replace(
        "# Generated from data/demand_price_table.csv. Each value is net\n",
        "# Generated from the SOL demand table plus PP victuals demand. Lumber is\n"
        "# intentionally omitted because the compatibility stack sets it to zero.\n"
        "# Each value is net\n",
        1,
    )
    return text


def _parse_injected_demand_add(path: Path, good: str) -> Dict[str, float]:
    text = _read(path)
    match = re.search(rf"\b(?:TRY_)?INJECT:{re.escape(good)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"{good} injection not found in {path}")
    brace_start = text.index("{", match.start())
    block, _end = _collect_brace_block(text, brace_start)
    demand_add = _find_sub_block(block, "demand_add")
    if demand_add is None:
        raise ValueError(f"{good} demand_add not found in {path}")
    return _expand_demand_add(_parse_kv_block(demand_add))


def _parse_development_threshold(path: Path, good: str) -> Optional[float]:
    text = _read(path)
    match = re.search(rf"(?m)^{re.escape(good)}\s*=\s*\{{", text)
    if not match:
        raise ValueError(f"{good} definition not found in {path}")
    brace_start = text.index("{", match.start())
    block, _end = _collect_brace_block(text, brace_start)
    threshold = re.search(r"\bdevelopment_threshold\s*=\s*(-?[\d.]+)", block)
    return float(threshold.group(1)) if threshold else None


def _render_goods_injections() -> str:
    inject = _parse_inject_file(STABLE_POP_GOODS).get("lumber")
    if not inject:
        raise ValueError(f"SOL lumber injection not found in {STABLE_POP_GOODS}")

    vanilla = load_vanilla_goods()["lumber"]
    pp_add = _parse_injected_demand_add(PP_LUMBER_FILE, "lumber")
    pre_compat = {
        pop_type: (
            vanilla["add"][pop_type] * vanilla["mult"][pop_type]
            + inject["inject_add"].get(pop_type, 0.0)
            + pp_add.get(pop_type, 0.0)
        )
        for pop_type in POP_TYPES
    }
    corrections = {pop_type: -value for pop_type, value in pre_compat.items()}
    for pop_type in POP_TYPES:
        final = pre_compat[pop_type] + corrections[pop_type]
        if abs(final) > EPSILON:
            raise ValueError(f"lumber demand correction failed for {pop_type}: {final}")
    lines = [
        GENERATED_HEADER.rstrip(),
        "# PP cancels vanilla lumber pop demand after SOL has added its calibrated",
        "# adjustment. This third demand_add cancels the remaining SOL adjustment,",
        "# leaving final lumber pop demand at exactly zero.",
        "INJECT:lumber = {",
        "\tdemand_add = {",
    ]
    for pop_type in POP_TYPES:
        value = corrections[pop_type]
        if abs(value) <= EPSILON:
            continue
        lines.append(f"\t\t{pop_type} = {_format_float(value)}")
    lines.extend(["\t}", "}", ""])

    victuals_threshold = _parse_development_threshold(PP_VICTUALS_FILE, "victuals")
    if victuals_threshold is not None:
        lines.extend([
            "# PP adds its own development gate to victuals. Negate it so every",
            "# pop-demand good remains independent of location development.",
            "INJECT:victuals = {",
            f"\tdevelopment_threshold = {_format_float(-victuals_threshold)}",
            "}",
            "",
        ])
    return "\n".join(lines)


def _market_reset(good: str, value: int) -> str:
    return (
        f"\t\tremove_from_global_variable_map = {{ name = sol_market_consumes_{good} key = scope:sol_market_cache }}\n"
        f"\t\tadd_to_global_variable_map = {{ name = sol_market_consumes_{good} key = scope:sol_market_cache value = {value} }}"
    )


def _country_market_check(good: str) -> str:
    return (
        "\t\tif = {\n"
        "\t\t\tlimit = {\n"
        f"\t\t\t\thas_global_variable_map = sol_market_consumes_{good}\n"
        f"\t\t\t\tis_key_in_global_variable_map = {{ name = sol_market_consumes_{good} target = scope:gls_panel_market }}\n"
        f"\t\t\t\t\"global_variable_map(sol_market_consumes_{good}|scope:gls_panel_market)\" > 0\n"
        "\t\t\t}\n"
        f"\t\t\tremove_from_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country }}\n"
        f"\t\t\tadd_to_global_variable_map = {{ name = gls_country_consumes_{good} key = scope:gls_panel_country value = 1 }}\n"
        "\t\t}"
    )


def _replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"Expected one {label} anchor, found {count}")
    return text.replace(old, new, 1)


def _render_effects(rows: List[Tuple[str, float, Dict[str, float]]]) -> str:
    text = _read(STABLE_EFFECTS)
    refresh = _generate_refresh_block(rows)
    save_scope = "\t\tsave_scope_as = sol_market_cache"
    refresh = _replace_once(
        refresh,
        save_scope,
        save_scope + "\n\n\t\t# PP requires final lumber pop demand to be zero. Clear saved-map residue.\n" + _market_reset("lumber", 0),
        "market cache scope",
    )
    block_start, block_end = _find_effect_block(text)
    text = text[:block_start] + refresh + text[block_end:]

    lumber_init = (
        "\tremove_from_global_variable_map = { name = gls_country_consumes_lumber key = scope:gls_panel_country }\n"
        "\tadd_to_global_variable_map = { name = gls_country_consumes_lumber key = scope:gls_panel_country value = 0 }"
    )
    victuals_init = (
        "\tremove_from_global_variable_map = { name = gls_country_consumes_victuals key = scope:gls_panel_country }\n"
        "\tadd_to_global_variable_map = { name = gls_country_consumes_victuals key = scope:gls_panel_country value = 0 }"
    )
    text = _replace_once(text, lumber_init, lumber_init + "\n" + victuals_init, "country goods reset")

    lumber_check = _country_market_check("lumber")
    text = _replace_once(
        text,
        lumber_check,
        lumber_check + "\n" + _country_market_check("victuals"),
        "country market aggregation",
    )

    lumber_count = (
        "\tif = { limit = { \"global_variable_map(gls_country_consumes_lumber|scope:gls_panel_country)\" > 0 } "
        "change_local_variable = { name = gls_country_consumed_goods_count add = 1 } }"
    )
    victuals_count = lumber_count.replace("lumber", "victuals")
    text = _replace_once(text, lumber_count, lumber_count + "\n" + victuals_count, "country goods count")
    return GENERATED_HEADER + text


def _victuals_widget(variable_map: str, scope: str, indent: str) -> str:
    return (
        f'{indent}widget = {{ size = {{ 34 30 }} tooltip = "victuals" '
        'icon = { size = { 24 24 } parentanchor = center texture = "gfx/interface/icons/trade_goods/icon_goods_victuals.dds" } '
        f'text_single = {{ size = {{ 100% 100% }} align = center raw_text = "@trigger_no!" fontsize = 23 '
        f'visible = "[Not(GreaterThan_CFixedPoint(GetVariableFromGlobalVariableMap(\'{variable_map}\', {scope}).GetValue,\'(CFixedPoint)0\'))]" }} }}'
    )


def _render_gui(source: Path, variable_map: str, scope: str) -> str:
    text = _read(source)
    weaponry_lines = [line for line in text.splitlines() if 'tooltip = "weaponry"' in line]
    if len(weaponry_lines) != 1:
        raise ValueError(f"Expected one weaponry widget in {source}, found {len(weaponry_lines)}")
    weaponry = weaponry_lines[0]
    indent = weaponry[: len(weaponry) - len(weaponry.lstrip())]
    victuals = _victuals_widget(variable_map, scope, indent)
    return GENERATED_HEADER + _replace_once(text, weaponry, victuals + "\n" + weaponry, "weaponry widget")


def _render_outputs() -> Dict[Path, str]:
    rows = _compat_good_rows()
    return {
        VALUES_OUTPUT: _render_values(rows),
        EFFECTS_OUTPUT: _render_effects(rows),
        LUMBER_OUTPUT: _render_goods_injections(),
        LOCATION_GUI_OUTPUT: _render_gui(
            STABLE_LOCATION_GUI,
            "sol_market_consumes_victuals",
            "Location.GetMarket.MakeScope",
        ),
        SITUATION_GUI_OUTPUT: _render_gui(
            STABLE_SITUATION_GUI,
            "gls_country_consumes_victuals",
            "Player.MakeScope",
        ),
    }


def _check(outputs: Dict[Path, str]) -> bool:
    ok = True
    for path, expected in outputs.items():
        relative = path.relative_to(REPO_ROOT)
        if not path.exists():
            print(f"[FAIL] Missing generated target: {relative}")
            ok = False
            continue
        if path.read_bytes()[:3] != UTF8_BOM:
            print(f"[FAIL] Missing UTF-8 BOM: {relative}")
            ok = False
            continue
        if _read(path) != expected:
            print(f"[FAIL] Out of date: {relative}")
            ok = False
            continue
        print(f"[OK] Up to date: {relative}")
    return ok


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SOL-PP compatibility overrides.")
    parser.add_argument("--check", action="store_true", help="Check outputs without writing files.")
    args = parser.parse_args()

    outputs = _render_outputs()
    if args.check:
        raise SystemExit(0 if _check(outputs) else 1)

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(UTF8_BOM + content.encode("utf-8"))
        print(f"[gen_sol_pp_compat] Wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
