#!/usr/bin/env python3
"""
gen_goods_demand_overrides.py — strip vanilla goods_demand_modifier and
clergy_goods_demand_modifier blocks, then write REPLACE: override files so
that SOL_goods_weight_values.txt Part 2 is the sole authority.

Usage:
    conda run -n eu5 --no-capture-output python scripts/gen_goods_demand_overrides.py [--dry-run]

Note: --no-capture-output is required to avoid conda's GBK re-encoding error on
Chinese Windows when the output contains non-ASCII characters from vanilla files.

Phase A: For each vanilla source listed in FILES, emit only the definitions
         that carry demand modifier blocks, with those blocks removed, prefixed
         with REPLACE: so the engine replaces the full definition.

Phase B: Print a weight-system audit listing every stripped modifier entry so
         SOL_goods_weight_values.txt Part 2 can be cross-checked.
"""

import argparse
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = Path(__file__).parent.parent
REF  = ROOT / "reference_game_files" / "game" / "in_game" / "common"
SRC  = ROOT / "src" / "stable" / "in_game" / "common"

# (vanilla relative path, output relative path)
FILES = [
    ("culture_groups/00_culture_groups.txt",
     "culture_groups/z_SOL_reset_culture_group_demand.txt"),
    ("cultures/turkic.txt",
     "cultures/z_SOL_reset_culture_demand_turkic.txt"),
    ("cultures/egypt.txt",
     "cultures/z_SOL_reset_culture_demand_egypt.txt"),
    ("cultures/south_slavic.txt",
     "cultures/z_SOL_reset_culture_demand_south_slavic.txt"),
    ("cultures/french.txt",
     "cultures/z_SOL_reset_culture_demand_french.txt"),
    ("religion_groups/00_default.txt",
     "religion_groups/z_SOL_reset_religion_group_demand.txt"),
    ("religions/christian.txt",
     "religions/z_SOL_reset_religion_demand_christian.txt"),
    ("religions/dharmic.txt",
     "religions/z_SOL_reset_religion_demand_dharmic.txt"),
    ("religions/buddhist.txt",
     "religions/z_SOL_reset_religion_demand_buddhist.txt"),
]

MODIFIER_KEYS = ("goods_demand_modifier", "clergy_goods_demand_modifier")

FILE_HEADER = """\
# AUTO-GENERATED by scripts/gen_goods_demand_overrides.py
# Uses REPLACE: to strip goods_demand_modifier blocks from vanilla definitions.
# SOL weight system (SOL_goods_weight_values.txt Part 2) encodes these modifiers.
# Do not edit by hand — re-run the script after any vanilla update.
"""


# ── Jomini text parser ────────────────────────────────────────────────────────

def _find_matching_close(text: str, open_idx: int) -> int:
    """Return the index of '}' that matches '{' at open_idx, or -1."""
    depth = 0
    i = open_idx
    n = len(text)
    while i < n:
        c = text[i]
        if c == '#':
            while i < n and text[i] != '\n':
                i += 1
        elif c == '"':
            i += 1
            while i < n and text[i] != '"':
                i += 1
        elif c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return -1


# Matches a word at the start of a line followed by ' = {'
# The ^ + MULTILINE ensures we only match things starting at column 0,
# i.e. truly top-level definitions (sub-blocks are always indented).
_TOPLEVEL_RE = re.compile(r'^(\w+)\s*=\s*\{', re.MULTILINE)


def iter_toplevel(text: str):
    """Yield (name, full_block_text) for each top-level 'name = { ... }' block."""
    consumed_up_to = 0
    for m in _TOPLEVEL_RE.finditer(text):
        if m.start() < consumed_up_to:
            continue  # inside an already-consumed outer block
        open_brace = text.index('{', m.start())
        close_brace = _find_matching_close(text, open_brace)
        if close_brace < 0:
            continue
        yield m.group(1), text[m.start(): close_brace + 1]
        consumed_up_to = close_brace + 1


def _strip_subblocks(body: str):
    """
    Remove all goods_demand_modifier / clergy_goods_demand_modifier sub-blocks
    from *body* (the text inside the outer { }).
    Returns (cleaned_body, audit) where audit is a list of (key, {good: float}).
    """
    audit = []
    result = body

    for key in MODIFIER_KEYS:
        # Match optional leading whitespace + the key keyword
        pattern = re.compile(r'[ \t]*\b' + re.escape(key) + r'\s*=\s*\{')
        while True:
            m = pattern.search(result)
            if not m:
                break
            open_brace = result.index('{', m.start())
            close_brace = _find_matching_close(result, open_brace)
            if close_brace < 0:
                break

            # Collect goods for the audit report
            inner = result[open_brace + 1: close_brace]
            goods: dict[str, float] = {}
            for gm in re.finditer(r'(\w+)\s*=\s*([0-9.]+)', inner):
                goods[gm.group(1)] = float(gm.group(2))
            if goods:
                audit.append((key, goods))

            # Remove the block; also eat the trailing newline if present
            end = close_brace + 1
            if end < len(result) and result[end] == '\n':
                end += 1
            result = result[:m.start()] + result[end:]

    return result, audit


# ── Per-file processing ───────────────────────────────────────────────────────

def process_file(ref_path: Path, dst_path: Path, dry_run: bool) -> list:
    """
    Parse ref_path, strip demand modifier blocks from definitions that carry
    them, write REPLACE: entries to dst_path.
    Returns audit entries: list of (def_name, modifier_key, {good: value}).
    """
    text = ref_path.read_text(encoding="utf-8-sig")

    blocks_out: list[str] = []
    all_audit: list[tuple] = []

    for name, full_block in iter_toplevel(text):
        open_brace = full_block.index('{')
        close_brace = _find_matching_close(full_block, open_brace)
        body = full_block[open_brace + 1: close_brace]

        cleaned_body, audit = _strip_subblocks(body)
        if not audit:
            continue  # no demand modifiers — skip

        for key, goods in audit:
            all_audit.append((name, key, goods))

        blocks_out.append(f"REPLACE:{name} = {{{cleaned_body}}}")

    if not blocks_out:
        return all_audit

    content = FILE_HEADER + "\n".join(blocks_out) + "\n"

    if dry_run:
        print(f"  [DRY-RUN] Would write {dst_path.relative_to(ROOT)}")
        print(f"            ({len(blocks_out)} definition(s))")
    else:
        dst_path.parent.mkdir(parents=True, exist_ok=True)
        dst_path.write_text(content, encoding="utf-8-sig")
        print(f"  Wrote {dst_path.relative_to(ROOT)}  ({len(blocks_out)} definition(s))")

    return all_audit


# ── Audit report ─────────────────────────────────────────────────────────────

def print_audit(all_audit: list) -> None:
    if not all_audit:
        print("(no demand modifiers found)")
        return

    print("\n" + "=" * 70)
    print("WEIGHT SYSTEM AUDIT")
    print("Cross-check each entry in SOL_goods_weight_values.txt Part 2.")
    print("=" * 70)

    for def_name, mod_key, goods in all_audit:
        tag = "clergy" if mod_key == "clergy_goods_demand_modifier" else "all"
        print(f"\n[{def_name}]  ({tag} pops)")
        for good, value in sorted(goods.items()):
            sv = f"SOL_{good}_weight"
            print(f"  {good:<28} vanilla={value:<6}  → {sv} Part2")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate REPLACE: override files to neutralise vanilla "
                    "goods_demand_modifier blocks."
    )
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be written without writing")
    args = parser.parse_args()

    all_audit: list[tuple] = []

    for ref_rel, dst_rel in FILES:
        ref_path = REF / ref_rel
        dst_path = SRC / dst_rel
        if not ref_path.exists():
            print(f"  MISSING  {ref_path}")
            continue
        entries = process_file(ref_path, dst_path, args.dry_run)
        all_audit.extend(entries)

    print_audit(all_audit)
    print("\nDone.")


if __name__ == "__main__":
    main()
