#!/usr/bin/env python3
"""Generate the late-loading SOL / MEIOU and Taxes compatibility layer."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from dataclasses import dataclass
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))
sys.path.insert(0, str(REPO_ROOT))

from gen_market_unit_consumption import (  # noqa: E402
    _generate_refresh_block,
    _generate_values,
)
from tools.sol_demand_simulator.parser import (  # noqa: E402
    _collect_brace_block,
    load_vanilla_goods,
)

TARGET_ROOT = REPO_ROOT / "src" / "sol_mnt_compatibility_submod"
STABLE_ROOT = REPO_ROOT / "src" / "stable"
MNT_ROOT = REPO_ROOT / "reference_mods" / "3735059838"
VANILLA_ROOT = REPO_ROOT / "reference_game_files" / "game"

TARGET_DEMAND_CSV = REPO_ROOT / "data" / "target_demand.csv"
STABLE_PRICES = STABLE_ROOT / "in_game" / "common" / "prices" / "A_SOL_economy_prices.txt"
STABLE_STATIC_MODIFIERS = (
    STABLE_ROOT / "main_menu" / "common" / "static_modifiers" / "A_SOL_economy_modifiers.txt"
)
STABLE_CABINET = (
    STABLE_ROOT / "in_game" / "common" / "cabinet_actions" / "A_SOL_war_cabinet_actions.txt"
)
STABLE_COLONIAL = (
    STABLE_ROOT / "in_game" / "common" / "generic_actions" / "A_SOL_economy_generic_actions.txt"
)
STABLE_CMM_SCRIPTED_GUI = (
    STABLE_ROOT / "in_game" / "common" / "scripted_guis" / "SOL_cmm_scripted_gui.txt"
)
STABLE_CMM_VALUES = (
    STABLE_ROOT / "in_game" / "common" / "script_values" / "SOL_cmm_values.txt"
)

MNT_GOODS_ROOT = MNT_ROOT / "in_game" / "common" / "goods"
MNT_PRICES_ROOT = MNT_ROOT / "in_game" / "common" / "prices"
MNT_STATIC_ROOT = MNT_ROOT / "main_menu" / "common" / "static_modifiers"
MNT_EPBM = MNT_ROOT / "in_game" / "common" / "scripted_effects" / "epbm_calculate.txt"
MNT_EPBM_EFFECTS = MNT_ROOT / "in_game" / "common" / "scripted_effects" / "epbm_effects.txt"
MNT_LOCATION_GUI = MNT_ROOT / "in_game" / "gui" / "location_window.gui"

VANILLA_PRICES_ROOT = VANILLA_ROOT / "in_game" / "common" / "prices"
VANILLA_STATIC_ROOT = VANILLA_ROOT / "main_menu" / "common" / "static_modifiers"
VANILLA_EFFECTS_ROOT = VANILLA_ROOT / "in_game" / "common" / "scripted_effects"

GOODS_OUTPUT = TARGET_ROOT / "in_game" / "common" / "goods" / "zz_SOL_MnT_pop_goods.txt"
VALUES_OUTPUT = (
    TARGET_ROOT
    / "in_game"
    / "common"
    / "script_values"
    / "zz_SOL_MnT_market_unit_consumption_values.txt"
)
EFFECTS_OUTPUT = (
    TARGET_ROOT / "in_game" / "common" / "scripted_effects" / "zz_SOL_MnT_compat_effects.txt"
)
CMM_OUTPUT = (
    TARGET_ROOT / "in_game" / "common" / "scripted_effects" / "zz_SOL_MnT_cmm_effects.txt"
)
CMM_VALUES_OUTPUT = (
    TARGET_ROOT / "in_game" / "common" / "script_values" / "SOL_cmm_values.txt"
)
CMM_SCRIPTED_GUI_OUTPUT = (
    TARGET_ROOT / "in_game" / "common" / "scripted_guis" / "SOL_cmm_scripted_gui.txt"
)
TRIGGERS_OUTPUT = (
    TARGET_ROOT / "in_game" / "common" / "scripted_triggers" / "zz_SOL_MnT_disabled_triggers.txt"
)
ENGLISH_CMM_LOC_OUTPUT = (
    TARGET_ROOT / "main_menu" / "localization" / "english" / "SOL_MnT_cmm_l_english.yml"
)
CHINESE_CMM_LOC_OUTPUT = (
    TARGET_ROOT
    / "main_menu"
    / "localization"
    / "simp_chinese"
    / "SOL_MnT_cmm_l_simp_chinese.yml"
)
PRICES_OUTPUT = TARGET_ROOT / "in_game" / "common" / "prices" / "zz_SOL_MnT_price_authority.txt"
STATIC_OUTPUT = (
    TARGET_ROOT
    / "main_menu"
    / "common"
    / "static_modifiers"
    / "zz_SOL_MnT_economic_static_authority.txt"
)
CABINET_OUTPUT = (
    TARGET_ROOT / "in_game" / "common" / "cabinet_actions" / "zz_SOL_MnT_war_cabinet.txt"
)
COLONIAL_OUTPUT = (
    TARGET_ROOT / "in_game" / "common" / "generic_actions" / "zz_SOL_MnT_colonial_actions.txt"
)
LOCATION_GUI_OUTPUT = TARGET_ROOT / "in_game" / "gui" / "location_window.gui"

UTF8_BOM = b"\xef\xbb\xbf"
GENERATED_HEADER = (
    "# @AUTOGENERATED by scripts/gen_sol_mnt_compat.py - do not edit; "
    "run the generator.\n"
)
QUANTUM = Decimal("0.00001")
POP_TYPES = ("nobles", "clergy", "burghers", "laborers", "peasants", "soldiers", "tribesmen")
ALL_POP_TYPES = (*POP_TYPES, "slaves")
UPPER_TYPES = frozenset(("nobles", "clergy", "burghers", "laborers", "soldiers"))
COMMONER_TYPES = frozenset(("laborers", "peasants", "soldiers"))
GRAINS = ("maize", "millet", "rice")


@dataclass(frozen=True)
class Block:
    key: str
    body: str
    operation: str
    source: Path


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def _decimal(value: str | float | Decimal) -> Decimal:
    if isinstance(value, Decimal):
        return value
    return Decimal(str(value))


def _round_quantity(value: Decimal) -> Decimal:
    return value.quantize(QUANTUM, rounding=ROUND_HALF_UP)


def _format_decimal(value: Decimal) -> str:
    rounded = _round_quantity(value)
    if rounded == 0:
        return "0"
    return format(rounded, "f").rstrip("0").rstrip(".")


def _parse_top_level_blocks(text: str, source: Path) -> List[Block]:
    blocks: List[Block] = []
    index = 0
    while index < len(text):
        while index < len(text) and text[index] in " \t\r\n":
            index += 1
        if index >= len(text):
            break
        if text[index] == "#":
            newline = text.find("\n", index)
            index = len(text) if newline < 0 else newline + 1
            continue
        match = re.match(
            r"(?:(?P<operation>(?:TRY_)?(?:INJECT|REPLACE)):)?"
            r"(?P<key>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*\{",
            text[index:],
        )
        if not match:
            newline = text.find("\n", index)
            index = len(text) if newline < 0 else newline + 1
            continue
        brace_start = index + match.end() - 1
        body, brace_end = _collect_brace_block(text, brace_start)
        blocks.append(
            Block(
                key=match.group("key"),
                body=body,
                operation=match.group("operation") or "",
                source=source,
            )
        )
        index = brace_end + 1
    return blocks


def _blocks_in_file(path: Path) -> List[Block]:
    return _parse_top_level_blocks(_read(path), path)


def _blocks_in_tree(root: Path) -> List[Block]:
    blocks: List[Block] = []
    for path in sorted(root.rglob("*.txt")):
        if path.name.lower() == "readme.txt":
            continue
        blocks.extend(_blocks_in_file(path))
    return blocks


def _unique_block(blocks: Iterable[Block], key: str, label: str) -> Block:
    matches = [block for block in blocks if block.key == key]
    if len(matches) != 1:
        locations = [str(block.source.relative_to(REPO_ROOT)) for block in matches]
        raise ValueError(f"Expected one {label} block for {key}, found {len(matches)}: {locations}")
    return matches[0]


def _optional_unique_block(blocks: Iterable[Block], key: str, label: str) -> Optional[Block]:
    matches = [block for block in blocks if block.key == key]
    if len(matches) > 1:
        locations = [str(block.source.relative_to(REPO_ROOT)) for block in matches]
        raise ValueError(f"Expected at most one {label} block for {key}, found {len(matches)}: {locations}")
    return matches[0] if matches else None


def _field_spans(body: str, field: str, block: bool) -> List[Tuple[int, int]]:
    suffix = r"\s*=\s*\{" if block else r"\s*=\s*[^\r\n#}]+(?:\s*#.*)?"
    pattern = re.compile(rf"(?m)^[ \t]*{re.escape(field)}{suffix}[ \t]*(?:\r?\n|$)")
    spans: List[Tuple[int, int]] = []
    for match in pattern.finditer(body):
        depth = body[: match.start()].count("{") - body[: match.start()].count("}")
        if depth != 0:
            continue
        if block:
            brace_start = body.index("{", match.start())
            _inner, brace_end = _collect_brace_block(body, brace_start)
            end = brace_end + 1
            while end < len(body) and body[end] in " \t":
                end += 1
            if end < len(body) and body[end] == "#":
                newline = body.find("\n", end)
                end = len(body) if newline < 0 else newline + 1
            elif end < len(body) and body[end] == "\r":
                end += 1
                if end < len(body) and body[end] == "\n":
                    end += 1
            elif end < len(body) and body[end] == "\n":
                end += 1
            spans.append((match.start(), end))
        else:
            spans.append((match.start(), match.end()))
    return spans


def _remove_fields(body: str, fields: Sequence[Tuple[str, bool]]) -> str:
    spans: List[Tuple[int, int]] = []
    for field, is_block in fields:
        spans.extend(_field_spans(body, field, is_block))
    for start, end in sorted(spans, reverse=True):
        body = body[:start] + body[end:]
    return body


DEMAND_FIELDS = (
    ("demand_add", True),
    ("demand_multiply", True),
    ("development_threshold", False),
    ("wealth_impact_threshold", True),
)


def _simple_block_values(body: str, field: str) -> Dict[str, Decimal]:
    spans = _field_spans(body, field, True)
    if not spans:
        return {}
    if len(spans) != 1:
        raise ValueError(f"Expected one {field} block")
    start, _end = spans[0]
    brace_start = body.index("{", start)
    inner, _brace_end = _collect_brace_block(body, brace_start)
    result: Dict[str, Decimal] = {}
    for match in re.finditer(
        r"(?m)^[ \t]*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(-?(?:\d+(?:\.\d*)?|\.\d+))",
        inner,
    ):
        result[match.group(1)] = Decimal(match.group(2))
    return result


def _expand_group_values(values: Dict[str, Decimal], multiply: bool) -> Dict[str, Decimal]:
    result = {pop_type: Decimal("1") if multiply else Decimal("0") for pop_type in ALL_POP_TYPES}
    ordered_keys = ["all", "upper", "commoners"] + [
        key for key in values if key not in {"all", "upper", "commoners"}
    ]
    for key in ordered_keys:
        if key not in values:
            continue
        if key == "all":
            targets = ALL_POP_TYPES
        elif key == "upper":
            targets = UPPER_TYPES
        elif key == "commoners":
            targets = COMMONER_TYPES
        elif key in ALL_POP_TYPES:
            targets = (key,)
        else:
            raise ValueError(f"Unsupported M&T demand group: {key}")
        for pop_type in targets:
            if multiply:
                result[pop_type] *= values[key]
            else:
                result[pop_type] += values[key]
    return result


def _final_pop_demand(body: str) -> Dict[str, Decimal]:
    additions = _expand_group_values(_simple_block_values(body, "demand_add"), multiply=False)
    multipliers = _expand_group_values(_simple_block_values(body, "demand_multiply"), multiply=True)
    return {pop_type: additions[pop_type] * multipliers[pop_type] for pop_type in ALL_POP_TYPES}


def _default_price(body: str, key: str) -> Decimal:
    match = re.search(
        r"(?m)^[ \t]*default_market_price\s*=\s*(-?(?:\d+(?:\.\d*)?|\.\d+))",
        body,
    )
    if not match:
        raise ValueError(f"default_market_price missing for {key}")
    price = Decimal(match.group(1))
    if price <= 0:
        raise ValueError(f"default_market_price must be positive for {key}")
    return price


def _load_sol_targets() -> Dict[str, Dict[str, Decimal]]:
    result: Dict[str, Dict[str, Decimal]] = {}
    with TARGET_DEMAND_CSV.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle):
            result[row["good"]] = {
                pop_type: Decimal(row.get(pop_type, "0") or "0") for pop_type in POP_TYPES
            }
    return result


def _compat_quantities(
    sol_targets: Dict[str, Dict[str, Decimal]],
    vanilla_prices: Dict[str, Decimal],
    mnt_blocks: Dict[str, Block],
) -> Dict[str, Dict[str, Decimal]]:
    quantities: Dict[str, Dict[str, Decimal]] = {}
    for good, target in sol_targets.items():
        if good not in mnt_blocks:
            raise ValueError(f"M&T goods definition missing for SOL good: {good}")
        mnt_price = _default_price(mnt_blocks[good].body, good)
        vanilla_price = vanilla_prices[good]
        quantities[good] = {
            pop_type: _round_quantity(target[pop_type] * vanilla_price / mnt_price)
            for pop_type in POP_TYPES
        }

    grain_prices = {good: _default_price(mnt_blocks[good].body, good) for good in GRAINS}
    for pop_type in POP_TYPES:
        sol_spending = sum(
            sol_targets[good][pop_type] * vanilla_prices[good] for good in GRAINS
        )
        equal_quantity = _round_quantity(sol_spending / sum(grain_prices.values()))
        for good in GRAINS:
            quantities[good][pop_type] = equal_quantity

    if quantities["tools"]["laborers"] != Decimal("0.00050"):
        raise ValueError(
            "tools laborer compatibility quantity must be 0.0005, got "
            f"{quantities['tools']['laborers']}"
        )
    return quantities


def _render_demand_block(
    quantities: Dict[str, Decimal],
    slave_quantity: Decimal,
) -> str:
    lines = ["\tdemand_add = {"]
    for pop_type in ALL_POP_TYPES:
        value = slave_quantity if pop_type == "slaves" else quantities[pop_type]
        if value == 0:
            continue
        lines.append(f"\t\t{pop_type} = {_format_decimal(value)}")
    lines.append("\t}")
    return "\n".join(lines)


def _insert_after_default_price(body: str, demand_block: str, key: str) -> str:
    matches = list(
        re.finditer(
            r"(?m)^[ \t]*default_market_price\s*=\s*[^\r\n]+(?:\r?\n|$)",
            body,
        )
    )
    matches = [
        match
        for match in matches
        if body[: match.start()].count("{") - body[: match.start()].count("}") == 0
    ]
    if len(matches) != 1:
        raise ValueError(f"Expected one default price line for {key}, found {len(matches)}")
    insert_at = matches[0].end()
    prefix = "" if body[insert_at:insert_at + 1] in {"", "\n", "\r"} else "\n"
    return body[:insert_at] + prefix + demand_block + "\n" + body[insert_at:]


def _normalize_without_demand(body: str) -> str:
    stripped = _remove_fields(body, DEMAND_FIELDS)
    return "\n".join(line.rstrip() for line in stripped.splitlines() if line.strip()).strip()


def _render_goods(
    sol_targets: Dict[str, Dict[str, Decimal]],
    quantities: Dict[str, Dict[str, Decimal]],
    mnt_blocks: Dict[str, Block],
) -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# M&T owns every non-demand field. SOL owns the seven calibrated pop quantities.",
        "# Wealth and development demand gates remain removed for SOL's continuous scaling.",
    ]
    for good in sol_targets:
        original = mnt_blocks[good].body
        mnt_pop_demand = _final_pop_demand(original)
        base = _remove_fields(original, DEMAND_FIELDS)
        demand_block = _render_demand_block(quantities[good], mnt_pop_demand["slaves"])
        rendered = _insert_after_default_price(base, demand_block, good)
        if _normalize_without_demand(rendered) != _normalize_without_demand(original):
            raise ValueError(f"Non-demand M&T fields changed while rendering {good}")
        if re.search(r"\b(?:development_threshold|wealth_impact_threshold)\s*=", rendered):
            raise ValueError(f"Demand threshold survived compatibility rendering for {good}")
        lines.extend(["", f"REPLACE:{good} = {{{rendered}}}"])
    lines.append("")
    return "\n".join(lines)


def _validate_demand_invariants(
    sol_targets: Dict[str, Dict[str, Decimal]],
    quantities: Dict[str, Dict[str, Decimal]],
    vanilla_prices: Dict[str, Decimal],
    mnt_blocks: Dict[str, Block],
) -> None:
    for good, target in sol_targets.items():
        if good in GRAINS:
            continue
        mnt_price = _default_price(mnt_blocks[good].body, good)
        for pop_type in POP_TYPES:
            ideal = target[pop_type] * vanilla_prices[good] / mnt_price
            if abs(quantities[good][pop_type] - ideal) > QUANTUM / 2:
                raise ValueError(f"Rounded compatibility quantity is out of range: {good}/{pop_type}")

    grain_prices = {good: _default_price(mnt_blocks[good].body, good) for good in GRAINS}
    for pop_type in POP_TYPES:
        grain_values = {quantities[good][pop_type] for good in GRAINS}
        if len(grain_values) != 1:
            raise ValueError(f"Grain quantities are not equal for {pop_type}: {grain_values}")
        sol_spending = sum(
            sol_targets[good][pop_type] * vanilla_prices[good] for good in GRAINS
        )
        compat_spending = sum(
            quantities[good][pop_type] * grain_prices[good] for good in GRAINS
        )
        max_rounding_drift = sum(grain_prices.values()) * QUANTUM / 2
        if abs(sol_spending - compat_spending) > max_rounding_drift:
            raise ValueError(f"Grain spending drift exceeds fixed-point rounding for {pop_type}")


def _render_values_and_refresh(
    quantities: Dict[str, Dict[str, Decimal]],
    mnt_blocks: Dict[str, Block],
) -> Tuple[str, str]:
    rows = [
        (
            good,
            float(_default_price(mnt_blocks[good].body, good)),
            {pop_type: float(quantities[good][pop_type]) for pop_type in POP_TYPES},
        )
        for good in sorted(quantities)
    ]
    values = _generate_values(rows)
    values = values.replace(
        "# @AUTOGENERATED by scripts/gen_market_unit_consumption.py - do not edit; run script to regenerate.\n",
        GENERATED_HEADER,
        1,
    )
    values = values.replace(
        "# Generated from data/demand_price_table.csv. Each value is net\n"
        "# demand_add quantity for one pop type and one good, with duplicate\n"
        "# legacy demand-group rows counted once. Yearly market spending\n"
        "# multiplies these quantities by min(market_price, default_price).\n",
        "# Replaces full-SOL unit quantities with the final M&T-price-scaled matrix.\n"
        "# Yearly market spending multiplies them by min(market_price, default_price).\n",
        1,
    )
    values = re.sub(
        r"(?m)^(sol_unit_consumption_[A-Za-z0-9_]+)\s*=",
        r"REPLACE:\1 =",
        values,
    )

    refresh = _generate_refresh_block(rows)
    refresh = refresh.replace(
        "sol_refresh_market_pop_demand_maps = {",
        "REPLACE:sol_refresh_market_pop_demand_maps = {",
        1,
    )
    return values, refresh


def _render_authority_objects(
    sol_source: Path,
    vanilla_root: Path,
    mnt_root: Path,
    purpose: str,
) -> str:
    sol_blocks = [block for block in _blocks_in_file(sol_source) if block.operation]
    vanilla_blocks = _blocks_in_tree(vanilla_root)
    mnt_blocks = _blocks_in_tree(mnt_root)
    lines = [GENERATED_HEADER.rstrip(), purpose]
    seen: set[str] = set()
    for sol_block in sol_blocks:
        if sol_block.key in seen:
            raise ValueError(f"Duplicate SOL authority key in {sol_source}: {sol_block.key}")
        seen.add(sol_block.key)
        mnt_block = _optional_unique_block(mnt_blocks, sol_block.key, "M&T authority")
        vanilla_block = _optional_unique_block(vanilla_blocks, sol_block.key, "vanilla authority")
        authority = mnt_block or vanilla_block
        if authority is None:
            lines.extend(
                [
                    "",
                    f"# {sol_block.key}: absent from checked vanilla and M&T references; SOL TRY operation is inert.",
                ]
            )
            continue
        source_label = "M&T" if mnt_block else "vanilla"
        lines.extend(
            [
                "",
                f"# {source_label} authority: {authority.source.relative_to(REPO_ROOT)}",
                f"REPLACE:{sol_block.key} = {{{authority.body}}}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def _replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise ValueError(f"Expected one {label} anchor, found {count}")
    return text.replace(old, new, 1)


def _strip_epbm_instrumentation(body: str) -> str:
    lines = body.splitlines(keepends=True)
    stripped: List[str] = []
    skipping = False
    for line in lines:
        if "# SOL_MNT_BEGIN" in line:
            if skipping:
                raise ValueError("Nested SOL_MNT instrumentation markers")
            skipping = True
            continue
        if "# SOL_MNT_END" in line:
            if not skipping:
                raise ValueError("Unmatched SOL_MNT instrumentation end marker")
            skipping = False
            continue
        if not skipping:
            stripped.append(line)
    if skipping:
        raise ValueError("Unclosed SOL_MNT instrumentation marker")
    return "".join(stripped)


EPBM_INIT = """
	# SOL_MNT_BEGIN location_cache_init
	save_temporary_scope_as = sol_mnt_maintenance_country
	if = {
		limit = { num_locations > 0 }
		every_owned_location = {
			limit = { is_land = yes }
			set_variable = { name = sol_mnt_raw_shared_cost value = 0 }
			set_variable = { name = sol_mnt_raw_assigned_nobles value = 0 }
			set_variable = { name = sol_mnt_raw_assigned_clergy value = 0 }
			set_variable = { name = sol_mnt_raw_assigned_burghers value = 0 }
			set_variable = { name = sol_mnt_raw_assigned_peasants value = 0 }
			set_variable = { name = sol_mnt_raw_assigned_tribes value = 0 }
			set_variable = { name = sol_mnt_raw_assigned_dhimmi value = 0 }
			set_variable = { name = sol_mnt_raw_assigned_cossacks value = 0 }
		}
	}
	# SOL_MNT_END location_cache_init
"""

EPBM_SHARED_CACHE = """
		# SOL_MNT_BEGIN shared_building_cache
		if = {
			limit = {
				local_var:epbm_bldg_cost > 0
				NOT = { building_category = government_category }
			}
			location = {
				if = {
					limit = { owner = scope:sol_mnt_maintenance_country }
					change_variable = { name = sol_mnt_raw_shared_cost add = local_var:epbm_bldg_cost }
				}
			}
		}
		# SOL_MNT_END shared_building_cache
"""

EPBM_FINALIZE = """
	# SOL_MNT_BEGIN location_cache_finalize
	set_local_variable = { name = sol_mnt_charge_factor value = var:epbm_charge_factor }
	set_local_variable = { name = sol_mnt_power_nobles value = 0 }
	set_local_variable = { name = sol_mnt_power_clergy value = 0 }
	set_local_variable = { name = sol_mnt_power_burghers value = 0 }
	set_local_variable = { name = sol_mnt_power_peasants value = 0 }
	set_local_variable = { name = sol_mnt_power_tribes value = 0 }
	set_local_variable = { name = sol_mnt_power_cossacks value = 0 }
	set_local_variable = { name = sol_mnt_include_tribes value = 0 }
	if = { limit = { country_has_estate = estate_type:nobles_estate } set_local_variable = { name = sol_mnt_power_nobles value = "estate_power(estate_type:nobles_estate)" } }
	if = { limit = { country_has_estate = estate_type:clergy_estate } set_local_variable = { name = sol_mnt_power_clergy value = "estate_power(estate_type:clergy_estate)" } }
	if = { limit = { country_has_estate = estate_type:burghers_estate } set_local_variable = { name = sol_mnt_power_burghers value = "estate_power(estate_type:burghers_estate)" } }
	if = { limit = { country_has_estate = estate_type:peasants_estate } set_local_variable = { name = sol_mnt_power_peasants value = "estate_power(estate_type:peasants_estate)" } }
	if = { limit = { country_has_estate = estate_type:cossacks_estate } set_local_variable = { name = sol_mnt_power_cossacks value = "estate_power(estate_type:cossacks_estate)" } }
	if = {
		limit = {
			country_has_estate = estate_type:tribes_estate
			NOT = {
				OR = {
					has_estate_privilege = estate_privilege:tribes_scotland_gaelic_heritage
					has_estate_privilege = estate_privilege:autonomous_tribes_scotland_gaelic_heritage
				}
			}
		}
		set_local_variable = { name = sol_mnt_include_tribes value = 1 }
		set_local_variable = { name = sol_mnt_power_tribes value = "estate_power(estate_type:tribes_estate)" }
	}

	if = {
		limit = { num_locations > 0 }
		every_owned_location = {
			limit = { is_land = yes }
			set_variable = { name = sol_location_estate_building_maintenance_nobles value = 0 }
			change_variable = { name = sol_location_estate_building_maintenance_nobles add = { value = var:sol_mnt_raw_assigned_nobles multiply = local_var:sol_mnt_charge_factor } }
			change_variable = { name = sol_location_estate_building_maintenance_nobles add = { value = var:sol_mnt_raw_shared_cost multiply = local_var:sol_mnt_power_nobles multiply = local_var:sol_mnt_charge_factor } }

			set_variable = { name = sol_location_estate_building_maintenance_clergy value = 0 }
			change_variable = { name = sol_location_estate_building_maintenance_clergy add = { value = var:sol_mnt_raw_assigned_clergy multiply = local_var:sol_mnt_charge_factor } }
			change_variable = { name = sol_location_estate_building_maintenance_clergy add = { value = var:sol_mnt_raw_shared_cost multiply = local_var:sol_mnt_power_clergy multiply = local_var:sol_mnt_charge_factor } }

			set_variable = { name = sol_location_estate_building_maintenance_burghers value = 0 }
			change_variable = { name = sol_location_estate_building_maintenance_burghers add = { value = var:sol_mnt_raw_assigned_burghers multiply = local_var:sol_mnt_charge_factor } }
			change_variable = { name = sol_location_estate_building_maintenance_burghers add = { value = var:sol_mnt_raw_shared_cost multiply = local_var:sol_mnt_power_burghers multiply = local_var:sol_mnt_charge_factor } }

			set_variable = { name = sol_location_estate_building_maintenance_commoners value = 0 }
			change_variable = { name = sol_location_estate_building_maintenance_commoners add = { value = var:sol_mnt_raw_assigned_peasants multiply = local_var:sol_mnt_charge_factor } }
			change_variable = { name = sol_location_estate_building_maintenance_commoners add = { value = var:sol_mnt_raw_shared_cost multiply = local_var:sol_mnt_power_peasants multiply = local_var:sol_mnt_charge_factor } }

			set_variable = { name = sol_location_estate_building_maintenance_tribesmen value = 0 }
			change_variable = { name = sol_location_estate_building_maintenance_tribesmen add = { value = var:sol_mnt_raw_assigned_cossacks multiply = local_var:sol_mnt_charge_factor } }
			change_variable = { name = sol_location_estate_building_maintenance_tribesmen add = { value = var:sol_mnt_raw_shared_cost multiply = local_var:sol_mnt_power_cossacks multiply = local_var:sol_mnt_charge_factor } }
			if = {
				limit = { local_var:sol_mnt_include_tribes > 0 }
				change_variable = { name = sol_location_estate_building_maintenance_tribesmen add = { value = var:sol_mnt_raw_assigned_tribes multiply = local_var:sol_mnt_charge_factor } }
				change_variable = { name = sol_location_estate_building_maintenance_tribesmen add = { value = var:sol_mnt_raw_shared_cost multiply = local_var:sol_mnt_power_tribes multiply = local_var:sol_mnt_charge_factor } }
			}
		}
	}
	# SOL_MNT_END location_cache_finalize
"""

EPBM_CLEANUP = """
	# SOL_MNT_BEGIN local_variable_cleanup
	epbm_for_each_estate = { effect = sol_mnt_cleanup_epbm_estate_local_variable }
	remove_local_variable = epbm_total_cost
	remove_local_variable = epbm_crown_total_cost
	remove_local_variable = epbm_shared_fraction
	remove_local_variable = epbm_bldg_cost
	remove_local_variable = sol_mnt_charge_factor
	remove_local_variable = sol_mnt_power_nobles
	remove_local_variable = sol_mnt_power_clergy
	remove_local_variable = sol_mnt_power_burghers
	remove_local_variable = sol_mnt_power_peasants
	remove_local_variable = sol_mnt_power_tribes
	remove_local_variable = sol_mnt_power_cossacks
	remove_local_variable = sol_mnt_include_tribes
	# SOL_MNT_END local_variable_cleanup
"""


def _render_epbm_body() -> str:
    original = _unique_block(_blocks_in_file(MNT_EPBM), "epbm_calculate_maintenance", "M&T EPBM").body
    rendered = _replace_once(
        original,
        "\tset_local_variable = { name = epbm_crown_total_cost value = 0 }\n",
        "\tset_local_variable = { name = epbm_crown_total_cost value = 0 }\n"
        + EPBM_INIT.lstrip("\n"),
        "EPBM initialization",
    )
    domestic_anchor = (
        "\t\tif = { limit = { local_var:epbm_bldg_cost > 0 } "
        "epbm_route_building_cost = yes }\n"
    )
    if rendered.count(domestic_anchor) != 2:
        raise ValueError(
            "Expected matching domestic and foreign EPBM routing anchors, found "
            f"{rendered.count(domestic_anchor)}"
        )
    rendered = rendered.replace(
        domestic_anchor,
        domestic_anchor + EPBM_SHARED_CACHE.lstrip("\n"),
        1,
    )
    rendered = _replace_once(
        rendered,
        "\tepbm_add_estate_building_costs = yes\n",
        "\tepbm_add_estate_building_costs = yes\n" + EPBM_FINALIZE.lstrip("\n"),
        "EPBM finalization",
    )
    rendered = rendered.rstrip() + EPBM_CLEANUP + "\n"
    if _strip_epbm_instrumentation(rendered).rstrip() != original.rstrip():
        raise ValueError("EPBM compatibility rendering changed M&T logic outside instrumentation markers")
    if re.search(r"\bbuilding_category\s*!=", rendered):
        raise ValueError("building_category is a simple-assign trigger; negate it with NOT")
    if re.search(r"\bis_gaelic_clans\b", rendered):
        raise ValueError("is_gaelic_clans is pop-scoped; EPBM runs in country scope")
    return rendered


def _with_local_cleanup(body: str, names: Sequence[str]) -> str:
    lines = [body.rstrip(), ""]
    lines.extend(f"\tremove_local_variable = {name}" for name in names)
    return "\n".join(lines) + "\n"


def _render_epbm_helper_with_cleanup(
    source: Path,
    key: str,
    names: Sequence[str],
) -> str:
    original = _unique_block(_blocks_in_file(source), key, "M&T EPBM helper").body
    return _with_local_cleanup(original, names)


def _render_estate_route_body() -> str:
    original = _unique_block(
        _blocks_in_file(MNT_EPBM),
        "epbm_route_to_cur_estate",
        "M&T estate route",
    ).body
    anchor = (
        "\t\tchange_local_variable = { name = epbm_estate_$estate$ "
        "add = local_var:epbm_bldg_cost }\n"
    )
    cache = """		# SOL_MNT_BEGIN assigned_location_cache
		if = {
			limit = { location = { owner = scope:sol_mnt_maintenance_country } }
			location = {
				change_variable = { name = sol_mnt_raw_assigned_$estate$ add = local_var:epbm_bldg_cost }
			}
		}
		# SOL_MNT_END assigned_location_cache
"""
    rendered = _replace_once(
        original,
        anchor,
        anchor + cache,
        "M&T estate route cost",
    )
    if _strip_epbm_instrumentation(rendered) != original:
        raise ValueError("Estate route rendering changed M&T logic outside instrumentation markers")
    return rendered


def _render_effects(refresh: str) -> str:
    vanilla_effects = _blocks_in_tree(VANILLA_EFFECTS_ROOT)
    change_gold = _unique_block(vanilla_effects, "change_gold_effect", "vanilla scripted effect")
    change_estate_gold = _unique_block(
        vanilla_effects, "change_estate_gold_effect", "vanilla scripted effect"
    )
    epbm_body = _render_epbm_body()
    estate_route_body = _render_estate_route_body()
    price_body = _render_epbm_helper_with_cleanup(
        MNT_EPBM,
        "epbm_price_building",
        ("epbm_per_level", "epbm_price", "epbm_qty", "epbm_loc_access", "epbm_bldg_eff"),
    )
    set_pay_body = _render_epbm_helper_with_cleanup(
        MNT_EPBM_EFFECTS,
        "epbm_set_pay_from_power",
        ("est",),
    )
    compute_scale_body = _render_epbm_helper_with_cleanup(
        MNT_EPBM_EFFECTS,
        "epbm_compute_modifier_scale",
        ("est",),
    )
    return "\n".join(
        [
            GENERATED_HEADER.rstrip(),
            "# Restore vanilla gold-transfer scaling; M&T does not replace these effects.",
            f"REPLACE:change_gold_effect = {{{change_gold.body}}}",
            "",
            f"REPLACE:change_estate_gold_effect = {{{change_estate_gold.body}}}",
            "",
            "# M&T now owns the location maintenance cache; disable SOL's one-gold scan.",
            "REPLACE:sol_update_estate_building_maintenance = {",
            "}",
            "",
            refresh,
            "",
            "# M&T calculation preserved byte-for-byte outside SOL_MNT marker sections.",
            f"REPLACE:epbm_calculate_maintenance = {{{epbm_body}}}",
            "",
            "# Clear helper-local calculations while retaining epbm_bldg_cost for the parent pass.",
            f"REPLACE:epbm_price_building = {{{price_body}}}",
            "",
            f"REPLACE:epbm_set_pay_from_power = {{{set_pay_body}}}",
            "",
            f"REPLACE:epbm_compute_modifier_scale = {{{compute_scale_body}}}",
            "",
            "sol_mnt_cleanup_epbm_estate_local_variable = {",
            "\tremove_local_variable = epbm_estate_$estate$",
            "}",
            "",
            "# Reuse M&T's existing seven-estate dispatch instead of running a second pass.",
            f"REPLACE:epbm_route_to_cur_estate = {{{estate_route_body}}}",
            "",
        ]
    )


def _append_bool_setting(
    lines: List[str],
    setting_id: str,
    group_id: str,
    alias: str,
    add_scripted_gui: bool = True,
    default_value: int = 1,
    tab_id: str = "feat",
) -> None:
    lines.extend(
        [
            "\tcmm_register_global_bool_setting = {",
            "\t\tmod_id = sol",
            f"\t\tsetting_id = {setting_id}",
            f"\t\ttab_id = {tab_id}",
            f"\t\tgroup_id = {group_id}",
            f"\t\tdefault_value = {default_value}",
            "\t}",
        ]
    )
    lines.extend(
        [
            "\tcmm_sync_bool_alias = {",
            f"\t\tsetting = sol__{setting_id}",
            f"\t\talias = {alias}",
            "\t}",
        ]
    )
    if add_scripted_gui:
        lines.extend(
            [
                "\tcmm_add_scripted_gui = {",
                "\t\tmod_id = sol",
                f"\t\tsetting_id = {setting_id}",
                "\t}",
            ]
        )
    lines.append("")


def _append_slider_setting(
    lines: List[str],
    setting_id: str,
    alias: str,
    default: str,
    minimum: str,
    maximum: str,
    step: str,
) -> None:
    lines.extend(
        [
            "\tcmm_register_global_slider_setting = {",
            "\t\tmod_id = sol",
            f"\t\tsetting_id = {setting_id}",
            "\t\ttab_id = feat",
            "\t\tgroup_id = as",
            f"\t\tdefault_value = {default}",
            f"\t\tmin_value = {minimum}",
            f"\t\tmax_value = {maximum}",
            f"\t\tstep_value = {step}",
            "\t}",
            "\tcmm_sync_setting_alias = {",
            f"\t\tsetting = sol__{setting_id}",
            f"\t\talias = {alias}",
            "\t}",
            "\tcmm_add_scripted_gui = {",
            "\t\tmod_id = sol",
            f"\t\tsetting_id = {setting_id}",
            "\t}",
            "",
        ]
    )


def _append_callback(
    lines: List[str], setting_id: str, alias: str, numeric: bool = False
) -> None:
    sync_effect = "cmm_sync_setting_alias" if numeric else "cmm_sync_bool_alias"
    lines.extend(
        [
            f"\t\tflag:sol__{setting_id} = {{",
            f"\t\t\t{sync_effect} = {{",
            f"\t\t\t\tsetting = sol__{setting_id}",
            f"\t\t\t\talias = {alias}",
            "\t\t\t}",
        ]
    )
    if setting_id == "sol_on":
        lines.extend(
            [
                "\t\t\tif = {",
                "\t\t\t\tlimit = { has_global_variable = sol_sol_on_enabled }",
                "\t\t\t\tgls_recalculate_global_living_standard = yes",
                "\t\t\t}",
            ]
        )
    lines.append("\t\t}")


def _render_cmm() -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# Keep M&T economic authority by default while allowing explicit CMF opt-in",
        "# to SOL's trigger-gated economic balance systems.",
        "REPLACE:sol_initialize_cmm_bool_alias_defaults = {",
        "\tset_global_variable = { name = sol_sol_on_enabled value = yes }",
        "\tset_global_variable = { name = sol_sol_map_enabled value = yes }",
        "\tremove_global_variable = sol_as_enabled",
        "\tset_global_variable = { name = sol_ae_enabled value = yes }",
        "\tset_global_variable = { name = sol_difficulty_enabled value = yes }",
        "\tset_global_variable = { name = sol_gdp_dev_enabled value = yes }",
        "\tset_global_variable = { name = sol_hw_enabled value = yes }",
        "\tset_global_variable = { name = sol_iwe_enabled value = yes }",
        "\tset_global_variable = { name = sol_hwe_enabled value = yes }",
        "\tset_global_variable = { name = sol_rwe_enabled value = yes }",
        "\tremove_global_variable = sol_solver_ai_prepare_enabled",
        "\tremove_global_variable = sol_solver_ai_exact_enabled",
        "\tremove_global_variable = sol_solver_ai_l2_enabled",
        "\tremove_global_variable = sol_solver_ai_minimax_enabled",
        "\tset_global_variable = { name = sol_solver_human_prepare_enabled value = yes }",
        "\tset_global_variable = { name = sol_solver_human_exact_enabled value = yes }",
        "\tset_global_variable = { name = sol_solver_human_l2_enabled value = yes }",
        "\tset_global_variable = { name = sol_solver_human_minimax_enabled value = yes }",
        "}",
        "",
        "REPLACE:sol_register_cmf_mod = {",
    ]
    _append_bool_setting(lines, "sol_on", "sol", "sol_sol_on_enabled", False)
    _append_bool_setting(lines, "sol_map", "sol", "sol_sol_map_enabled")
    _append_bool_setting(
        lines,
        "mnt_as_on",
        "as",
        "sol_as_enabled",
        False,
        default_value=0,
    )
    _append_slider_setting(lines, "bte", "sol_bte", "-15", "-30", "30", "1")
    _append_bool_setting(lines, "ae", "as", "sol_ae_enabled")
    _append_slider_setting(lines, "cts", "sol_cts", "-5", "-20", "0", "1")
    _append_slider_setting(lines, "ds", "sol_ds", "-5", "-20", "0", "1")
    _append_bool_setting(lines, "difficulty", "as", "sol_difficulty_enabled")
    _append_bool_setting(lines, "gdp_dev", "as", "sol_gdp_dev_enabled")
    _append_slider_setting(lines, "ai_pr", "sol_ai_pr", "0.5", "0", "2", "0.1")
    _append_bool_setting(lines, "hw_on", "hw", "sol_hw_enabled", False)
    _append_bool_setting(lines, "iwe", "hw", "sol_iwe_enabled")
    _append_bool_setting(lines, "hwe", "hw", "sol_hwe_enabled")
    _append_bool_setting(lines, "rwe", "hw", "sol_rwe_enabled")
    _append_bool_setting(lines, "solver_ai_prepare", "country_solver", "sol_solver_ai_prepare_enabled", False, default_value=0, tab_id="solver")
    _append_bool_setting(lines, "solver_ai_exact", "country_solver", "sol_solver_ai_exact_enabled", False, default_value=0, tab_id="solver")
    _append_bool_setting(lines, "solver_ai_l2", "country_solver", "sol_solver_ai_l2_enabled", False, default_value=0, tab_id="solver")
    _append_bool_setting(lines, "solver_ai_minimax", "country_solver", "sol_solver_ai_minimax_enabled", False, default_value=0, tab_id="solver")
    _append_bool_setting(lines, "solver_human_prepare", "country_solver", "sol_solver_human_prepare_enabled", False, tab_id="solver")
    _append_bool_setting(lines, "solver_human_exact", "country_solver", "sol_solver_human_exact_enabled", False, tab_id="solver")
    _append_bool_setting(lines, "solver_human_l2", "country_solver", "sol_solver_human_l2_enabled", False, tab_id="solver")
    _append_bool_setting(lines, "solver_human_minimax", "country_solver", "sol_solver_human_minimax_enabled", False, default_value=1, tab_id="solver")
    if lines[-1] == "":
        lines.pop()
    lines.extend(
        [
            "}",
            "",
            "REPLACE:sol_handle_cmf_callback = {",
            "\tswitch = {",
            "\t\ttrigger = var:cmf_callback",
        ]
    )
    for setting_id, alias, numeric in (
        ("sol_on", "sol_sol_on_enabled", False),
        ("sol_map", "sol_sol_map_enabled", False),
        ("mnt_as_on", "sol_as_enabled", False),
        ("bte", "sol_bte", True),
        ("ae", "sol_ae_enabled", False),
        ("cts", "sol_cts", True),
        ("ds", "sol_ds", True),
        ("difficulty", "sol_difficulty_enabled", False),
        ("gdp_dev", "sol_gdp_dev_enabled", False),
        ("ai_pr", "sol_ai_pr", True),
        ("hw_on", "sol_hw_enabled", False),
        ("iwe", "sol_iwe_enabled", False),
        ("hwe", "sol_hwe_enabled", False),
        ("rwe", "sol_rwe_enabled", False),
        ("solver_ai_prepare", "sol_solver_ai_prepare_enabled", False),
        ("solver_ai_exact", "sol_solver_ai_exact_enabled", False),
        ("solver_ai_l2", "sol_solver_ai_l2_enabled", False),
        ("solver_ai_minimax", "sol_solver_ai_minimax_enabled", False),
        ("solver_human_prepare", "sol_solver_human_prepare_enabled", False),
        ("solver_human_exact", "sol_solver_human_exact_enabled", False),
        ("solver_human_l2", "sol_solver_human_l2_enabled", False),
        ("solver_human_minimax", "sol_solver_human_minimax_enabled", False),
    ):
        _append_callback(lines, setting_id, alias, numeric)
    lines.extend(["\t}", "}", ""])
    rendered = "\n".join(lines)
    for required in (
        "mnt_as_on", "bte", "ae", "cts", "ds", "difficulty", "gdp_dev", "ai_pr"
    ):
        if f"setting_id = {required}" not in rendered:
            raise ValueError(f"Opt-in M&T CMF setting is not registered: {required}")
    if "setting_id = as_on" in rendered or "flag:sol__as_on" in rendered:
        raise ValueError("Legacy M&T economic master setting is still registered")
    return rendered


def _render_cmm_values() -> str:
    return "\n".join(
        [
            GENERATED_HEADER.rstrip(),
            "# Exact-path override: restore CMF-adjustable SOL economic values for opt-in use.",
            _read(STABLE_CMM_VALUES).rstrip(),
            "",
        ]
    )


def _render_cmm_scripted_guis() -> str:
    return "\n".join(
        [
            GENERATED_HEADER.rstrip(),
            "# Exact-path override: restore callbacks for the opt-in SOL economic settings.",
            _read(STABLE_CMM_SCRIPTED_GUI).rstrip(),
            "",
        ]
    )


def _render_disabled_triggers() -> str:
    lines = [
        GENERATED_HEADER.rstrip(),
        "# SOL economic balance remains off without CMF and defaults off in CMF.",
        "# Once the player enables the master setting, the original subfeature gates apply.",
        "",
        "REPLACE:sol_as_is_on = {",
        "\tAND = {",
        "\t\thas_global_variable_map = cmm",
        "\t\thas_global_variable = sol_as_enabled",
        "\t}",
        "}",
    ]
    for trigger, alias in (
        ("sol_ae_is_on", "sol_ae_enabled"),
        ("sol_difficulty_is_on", "sol_difficulty_enabled"),
        ("sol_gdp_dev_is_on", "sol_gdp_dev_enabled"),
    ):
        lines.extend(
            [
                "",
                f"REPLACE:{trigger} = {{",
                "\tAND = {",
                "\t\tsol_as_is_on = yes",
                f"\t\thas_global_variable = {alias}",
                "\t}",
                "}",
            ]
        )
    lines.append("")
    return "\n".join(lines)


def _render_cmm_localization(language: str) -> str:
    if language == "english":
        name = "Enable SOL Economic Balance with M&T?"
        description = (
            "Off by default. Enables SOL's trigger-gated economic settings on top of "
            "MEIOU and Taxes; M&T still owns generated goods, prices, and static modifiers."
        )
    elif language == "simp_chinese":
        name = "启用SOL经济平衡（M&T兼容）？"
        description = (
            "默认关闭。开启后会在MEIOU and Taxes之上启用SOL中由开关控制的经济功能；"
            "生成商品、价格和静态修正仍由M&T负责。"
        )
    else:
        raise ValueError(f"Unsupported localization language: {language}")
    return "\n".join(
        [
            f"l_{language}:",
            f' sol__mnt_as_on_name: "{name}"',
            f' sol__mnt_as_on_desc: "{description}"',
            ' sol__mnt_as_on: "sol__mnt_as_on"',
            "",
        ]
    )


def _render_decoupled_action(path: Path, key: str, purpose: str) -> str:
    block = _unique_block(_blocks_in_file(path), key, "SOL retained action")
    body, count = re.subn(r"(?m)^[ \t]*sol_as_is_on\s*=\s*no[^\r\n]*(?:\r?\n|$)", "", block.body)
    if count != 1:
        raise ValueError(f"Expected one sol_as_is_on bypass in {key}, found {count}")
    return "\n".join(
        [
            GENERATED_HEADER.rstrip(),
            purpose,
            f"REPLACE:{key} = {{{body}}}",
            "",
        ]
    )


BUTTON_ANCHOR_RE = re.compile(
    r"(?m)^\s*expand = \{\}\s*\n\s*subheader_unified_icon = \{\s*\n"
    r'\s*visible = "\[HasPopBreakdownIntelOn\(Location\.Self\)\]"'
)

SOL_BUTTON = """\t\t\t\t\t\t\t\t\t# SOL-M&T compatibility insertion: living-standard tooltip.
\t\t\t\t\t\t\t\t\tnavigational_button_alt = {
\t\t\t\t\t\t\t\t\t\tsize = {38 38}

\t\t\t\t\t\t\t\t\t\tblockoverride "icon_texture" {
\t\t\t\t\t\t\t\t\t\t\tpiechart = {
\t\t\t\t\t\t\t\t\t\t\t\tparentanchor = center
\t\t\t\t\t\t\t\t\t\t\t\tsize = { 70% 70% }
\t\t\t\t\t\t\t\t\t\t\t\talwaystransparent = yes

\t\t\t\t\t\t\t\t\t\t\t\thbox = {
\t\t\t\t\t\t\t\t\t\t\t\t\twidget = {
\t\t\t\t\t\t\t\t\t\t\t\t\t\tusing = layoutpolicy_expanding
\t\t\t\t\t\t\t\t\t\t\t\t\t\ticon = {
\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsize = { 100% 100% }
\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tparentanchor = center
\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname = "stat_sol_living_standard"
\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttexture = "gfx/interface/icons/sol/sol_living_standard.dds"
\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttexture_density = 2
\t\t\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t\tusing = bg_circle_piechart
\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t}

\t\t\t\t\t\t\t\t\t\ttooltipwidget = {
\t\t\t\t\t\t\t\t\t\t\tusing = StandardofLiving_tooltip
\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t}

"""


def _render_location_gui() -> str:
    text = _read(MNT_LOCATION_GUI)
    text = _replace_once(
        text,
        'raw_text = "[Location.GetTotalIncome|g2]@income!"',
        'raw_text = "[Location.MakeScope.ScriptValue(\'local_sol_total_income\')|g2]@income!"',
        "M&T location income",
    )
    matches = list(BUTTON_ANCHOR_RE.finditer(text))
    if len(matches) != 1:
        raise ValueError(f"Expected one M&T location button anchor, found {len(matches)}")
    text = text[: matches[0].start()] + SOL_BUTTON + text[matches[0].start() :]
    return GENERATED_HEADER + text


def _render_outputs() -> Dict[Path, str]:
    sol_targets = _load_sol_targets()
    vanilla_goods = load_vanilla_goods()
    vanilla_prices = {good: _decimal(data["price"]) for good, data in vanilla_goods.items()}
    mnt_goods_blocks_list = _blocks_in_tree(MNT_GOODS_ROOT)
    mnt_goods_blocks: Dict[str, Block] = {}
    for good in sol_targets:
        mnt_goods_blocks[good] = _unique_block(mnt_goods_blocks_list, good, "M&T good")
    if len(sol_targets) != 55:
        raise ValueError(f"Expected 55 SOL demand goods, found {len(sol_targets)}")
    quantities = _compat_quantities(sol_targets, vanilla_prices, mnt_goods_blocks)
    _validate_demand_invariants(sol_targets, quantities, vanilla_prices, mnt_goods_blocks)
    values, refresh = _render_values_and_refresh(quantities, mnt_goods_blocks)

    return {
        GOODS_OUTPUT: _render_goods(sol_targets, quantities, mnt_goods_blocks),
        VALUES_OUTPUT: values,
        EFFECTS_OUTPUT: _render_effects(refresh),
        CMM_OUTPUT: _render_cmm(),
        CMM_VALUES_OUTPUT: _render_cmm_values(),
        CMM_SCRIPTED_GUI_OUTPUT: _render_cmm_scripted_guis(),
        TRIGGERS_OUTPUT: _render_disabled_triggers(),
        ENGLISH_CMM_LOC_OUTPUT: _render_cmm_localization("english"),
        CHINESE_CMM_LOC_OUTPUT: _render_cmm_localization("simp_chinese"),
        PRICES_OUTPUT: _render_authority_objects(
            STABLE_PRICES,
            VANILLA_PRICES_ROOT,
            MNT_PRICES_ROOT,
            "# Remove every SOL price rebalance; M&T wins shared keys and vanilla wins the rest.",
        ),
        STATIC_OUTPUT: _render_authority_objects(
            STABLE_STATIC_MODIFIERS,
            VANILLA_STATIC_ROOT,
            MNT_STATIC_ROOT,
            "# Remove every SOL economic static delta; M&T wins shared keys and vanilla wins the rest.",
        ),
        CABINET_OUTPUT: _render_decoupled_action(
            STABLE_CABINET,
            "reduce_war_exhaustion",
            "# Retain SOL's wartime restriction without the removed economic master switch.",
        ),
        COLONIAL_OUTPUT: _render_decoupled_action(
            STABLE_COLONIAL,
            "create_colonial_charter",
            "# Retain SOL's colonial restrictions without the removed economic master switch.",
        ),
        LOCATION_GUI_OUTPUT: _render_location_gui(),
    }


def _check(outputs: Dict[Path, str]) -> bool:
    ok = True
    for path, expected in outputs.items():
        relative = path.relative_to(REPO_ROOT)
        if not path.exists():
            print(f"[FAIL] Missing generated target: {relative}")
            ok = False
            continue
        if path.read_bytes()[:3] != UTF8_BOM:
            print(f"[FAIL] Missing UTF-8 BOM: {relative}")
            ok = False
            continue
        if _read(path) != expected:
            print(f"[FAIL] Out of date: {relative}")
            ok = False
            continue
        print(f"[OK] Up to date: {relative}")
    return ok


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SOL-M&T compatibility overrides.")
    parser.add_argument("--check", action="store_true", help="Check outputs without writing files.")
    args = parser.parse_args()

    outputs = _render_outputs()
    if args.check:
        raise SystemExit(0 if _check(outputs) else 1)

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(UTF8_BOM + content.encode("utf-8"))
        print(f"[gen_sol_mnt_compat] Wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
