#!/usr/bin/env python3
"""Copy Glorp UI's location window into stable SOL and insert one SOL tooltip button."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[1]
GLORP_ROOT = REPO_ROOT / "reference_mods" / "3601047146"
SOURCE_PATH = GLORP_ROOT / "in_game" / "gui" / "location_window.gui"
SOURCE_METADATA_PATH = GLORP_ROOT / ".metadata" / "metadata.json"
SOURCE_TYPES_PATH = (
    GLORP_ROOT / "in_game" / "gui" / "vanilla" / "cmfg_location_window_vanilla_types.gui"
)
TARGET_PATH = REPO_ROOT / "src" / "stable" / "in_game" / "gui" / "location_window.gui"
TARGET_TYPES_PATH = (
    REPO_ROOT
    / "src"
    / "stable"
    / "in_game"
    / "gui"
    / "vanilla"
    / "cmfg_location_window_vanilla_types.gui"
)

AUTOGENERATED_HEADER = (
    "# @AUTOGENERATED by scripts/sync_location_window.py - do not edit; "
    "source is Glorp UI location_window.gui with only the SOL tooltip button inserted.\n"
)
AUTOGENERATED_TYPES_HEADER = (
    "# @AUTOGENERATED by scripts/sync_location_window.py - do not edit; "
    "copied from Glorp UI without code changes.\n"
)

BUTTON_ANCHOR_RE = re.compile(
    r"(?m)^\s*expand = \{\}\s*\n\s*subheader_unified_icon = \{\s*\n"
    r'\s*visible = "\[HasPopBreakdownIntelOn\(Location\.Self\)\]"'
)

SOL_BUTTON = """\t\t\t\t\t\t\t# SOL insertion: location living-standard tooltip in the Glorp UI row.
\t\t\t\t\t\t\tnavigational_button_alt = {
\t\t\t\t\t\t\t\tsize = {38 38}

\t\t\t\t\t\t\t\tblockoverride "icon_texture" {
\t\t\t\t\t\t\t\t\tpiechart = {
\t\t\t\t\t\t\t\t\t\tparentanchor = center
\t\t\t\t\t\t\t\t\t\tsize = { 70% 70% }
\t\t\t\t\t\t\t\t\t\talwaystransparent = yes

\t\t\t\t\t\t\t\t\t\thbox = {
\t\t\t\t\t\t\t\t\t\t\twidget = {
\t\t\t\t\t\t\t\t\t\t\t\tusing = layoutpolicy_expanding
\t\t\t\t\t\t\t\t\t\t\t\ticon = {
\t\t\t\t\t\t\t\t\t\t\t\t\tsize = { 100% 100% }
\t\t\t\t\t\t\t\t\t\t\t\t\tparentanchor = center
\t\t\t\t\t\t\t\t\t\t\t\t\tname = "stat_sol_living_standard"
\t\t\t\t\t\t\t\t\t\t\t\t\ttexture = "gfx/interface/icons/sol/sol_living_standard.dds"
\t\t\t\t\t\t\t\t\t\t\t\t\ttexture_density = 2
\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\tusing = bg_circle_piechart
\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t}

\t\t\t\t\t\t\t\ttooltipwidget = {
\t\t\t\t\t\t\t\t\tusing = StandardofLiving_tooltip
\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t}

"""


def verify_glorp_reference() -> str:
    if not SOURCE_PATH.exists():
        raise FileNotFoundError(f"Glorp UI reference file not found: {SOURCE_PATH}")
    if not SOURCE_METADATA_PATH.exists():
        raise FileNotFoundError(f"Glorp UI metadata not found: {SOURCE_METADATA_PATH}")
    if not SOURCE_TYPES_PATH.exists():
        raise FileNotFoundError(f"Glorp UI extracted location types not found: {SOURCE_TYPES_PATH}")

    metadata = json.loads(SOURCE_METADATA_PATH.read_text(encoding="utf-8-sig"))
    if metadata.get("id") != "glorp.ui":
        raise RuntimeError(
            f"Expected Glorp UI metadata id 'glorp.ui', found {metadata.get('id')!r}."
        )

    return str(metadata.get("version", "unknown"))


def generate_location_window(glorp_version: str) -> str:
    source = SOURCE_PATH.read_text(encoding="utf-8-sig")

    anchor_matches = list(BUTTON_ANCHOR_RE.finditer(source))
    if len(anchor_matches) != 1:
        raise RuntimeError(
            "Expected exactly one SOL button insertion anchor in the Glorp UI demography row, "
            f"found {len(anchor_matches)}."
        )
    insert_at = anchor_matches[0].start()
    text = source[:insert_at] + SOL_BUTTON + source[insert_at:]

    if text.replace(SOL_BUTTON, "", 1) != source:
        raise RuntimeError("Generated location window differs from Glorp UI beyond the SOL button.")

    return AUTOGENERATED_HEADER + f"# Glorp UI reference version: {glorp_version}\n" + text


def generate_location_types(glorp_version: str) -> str:
    text = SOURCE_TYPES_PATH.read_text(encoding="utf-8-sig")
    return (
        AUTOGENERATED_TYPES_HEADER
        + f"# Glorp UI reference version: {glorp_version}\n"
        + text
    )


def generate_outputs() -> dict[Path, str]:
    glorp_version = verify_glorp_reference()
    return {
        TARGET_PATH: generate_location_window(glorp_version),
        TARGET_TYPES_PATH: generate_location_types(glorp_version),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Return non-zero if stable SOL's location window is out of date.",
    )
    args = parser.parse_args()

    generated_outputs = generate_outputs()

    if args.check:
        failed = False
        for path, generated in generated_outputs.items():
            if not path.exists():
                print(f"[FAIL] Missing generated target: {path.relative_to(REPO_ROOT)}")
                failed = True
                continue
            current = path.read_text(encoding="utf-8-sig")
            if current != generated:
                print(f"[FAIL] Out of date: {path.relative_to(REPO_ROOT)}")
                failed = True
                continue
            print(f"[OK] Up to date: {path.relative_to(REPO_ROOT)}")
        if failed:
            print(
                "       Run: $env:PYTHONUTF8='1'; & $env:EU5_PYTHON "
                "scripts/sync_location_window.py"
            )
            return 1
        return 0

    for path, generated in generated_outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated, encoding="utf-8")
        print(f"[OK] Generated {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
