#!/usr/bin/env python3
"""Generate stable SOL's self-contained Glorp UI-based location-window override."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO_ROOT = Path(__file__).resolve().parents[1]
GLORP_ROOT = REPO_ROOT / "reference_mods" / "3601047146"
SOURCE_PATH = GLORP_ROOT / "in_game" / "gui" / "location_window.gui"
SOURCE_METADATA_PATH = GLORP_ROOT / ".metadata" / "metadata.json"
SOURCE_TYPES_PATH = (
    GLORP_ROOT / "in_game" / "gui" / "vanilla" / "cmfg_location_window_vanilla_types.gui"
)
TARGET_PATH = REPO_ROOT / "src" / "stable" / "in_game" / "gui" / "location_window.gui"
TARGET_TYPES_PATH = (
    REPO_ROOT
    / "src"
    / "stable"
    / "in_game"
    / "gui"
    / "vanilla"
    / "cmfg_location_window_vanilla_types.gui"
)

AUTOGENERATED_HEADER = (
    "# @AUTOGENERATED by scripts/sync_location_window.py - do not edit; "
    "source is Glorp UI location_window.gui with external integrations removed "
    "and SOL insertions applied.\n"
)
AUTOGENERATED_TYPES_HEADER = (
    "# @AUTOGENERATED by scripts/sync_location_window.py - do not edit; "
    "built-in vanilla location-window types extracted by Glorp UI.\n"
)

GLORP_INCOME = 'raw_text = "[Location.GetTotalIncome|g2]@income!"'
SOL_INCOME = 'raw_text = "[Location.MakeScope.ScriptValue(\'local_sol_total_income\')|g2]@income!"'

BUTTON_ANCHOR_RE = re.compile(
    r"(?m)^\s*expand = \{\}\s*\n\s*subheader_unified_icon = \{\s*\n"
    r'\s*visible = "\[HasPopBreakdownIntelOn\(Location\.Self\)\]"'
)

EXTERNAL_CM_MARKERS = (
    "cm_auto_food_widget_location_window = {}",
    "cm_auto_expand_rgo_widget_location_window = {}",
    "cm_check_for_auto_expand_when_upgrading_building",
    "cm_best_town_right",
)

CM_TOWN_HOVER_RE = re.compile(
    r'(?m)^[ \t]*# GlorpUI: Construction Manager best urban rights map mode hover\n'
    r'[ \t]*blockoverride "location_town_rights_sort_highlight" \{\n'
    r"[ \t]*onmousehierarchyenter = \"\[PdxGuiWidget\.PushMapModeOverride\('cm_best_town_right'\)\]\"\n"
    r"[ \t]*\}\n"
)

CM_RGO_WIDGETS_RE = re.compile(
    r"(?m)^[ \t]*# GlorpUI: Construction Manager auto-food widget, food RGO locations only\n"
    r"[ \t]*cm_auto_food_widget_location_window = \{\}\n\n"
    r"[ \t]*# GlorpUI: Construction Manager RGO auto-expand widget\n"
    r"[ \t]*cm_auto_expand_rgo_widget_location_window = \{\}\n\n"
)

CM_AUTO_EXPAND_VISIBILITY = (
    "\t\t\t\t\t\t# GlorpUI: hidden when Construction Manager is active\n"
    "\t\t\t\t\t\tvisible = \"[And(IsAutoExpand(LocationBuildingItem.GetBuilding.Self), "
    "Not(GetScriptedGui('glorpui_is_cm_active').IsShown(GuiScope.SetRoot(GetPlayer.MakeScope).End)))]\""
)
VANILLA_AUTO_EXPAND_VISIBILITY = (
    "\t\t\t\t\t\tvisible = \"[IsAutoExpand(LocationBuildingItem.GetBuilding.Self)]\""
)

CM_AUTO_EXPAND_ICON = (
    "\t\t\t\t\t# GlorpUI: Construction Manager auto-expand status icon\n"
    "\t\t\t\t\tcm_is_auto_expand_on_icon = {}\n\n"
)

GLORP_ZOOM_BUTTON = "zoom_to_button = { # GlorpUI: Zoom To"
SOL_ZOOM_BUTTON = "sol_zoom_to_button = { # SOL built-in Glorp-style Zoom To"

SOL_BUTTON = """\t\t\t\t\t\t\t# SOL insertion: location living-standard tooltip in the Glorp UI row.
\t\t\t\t\t\t\tnavigational_button_alt = {
\t\t\t\t\t\t\t\tsize = {38 38}

\t\t\t\t\t\t\t\tblockoverride "icon_texture" {
\t\t\t\t\t\t\t\t\tpiechart = {
\t\t\t\t\t\t\t\t\t\tparentanchor = center
\t\t\t\t\t\t\t\t\t\tsize = { 70% 70% }
\t\t\t\t\t\t\t\t\t\talwaystransparent = yes

\t\t\t\t\t\t\t\t\t\thbox = {
\t\t\t\t\t\t\t\t\t\t\twidget = {
\t\t\t\t\t\t\t\t\t\t\t\tusing = layoutpolicy_expanding
\t\t\t\t\t\t\t\t\t\t\t\ticon = {
\t\t\t\t\t\t\t\t\t\t\t\t\tsize = { 100% 100% }
\t\t\t\t\t\t\t\t\t\t\t\t\tparentanchor = center
\t\t\t\t\t\t\t\t\t\t\t\t\tname = "stat_sol_living_standard"
\t\t\t\t\t\t\t\t\t\t\t\t\ttexture = "gfx/interface/icons/sol/sol_living_standard.dds"
\t\t\t\t\t\t\t\t\t\t\t\t\ttexture_density = 2
\t\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t\t\tusing = bg_circle_piechart
\t\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\t}

\t\t\t\t\t\t\t\ttooltipwidget = {
\t\t\t\t\t\t\t\t\tusing = StandardofLiving_tooltip
\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t}

"""


def verify_glorp_reference() -> str:
    if not SOURCE_PATH.exists():
        raise FileNotFoundError(f"Glorp UI reference file not found: {SOURCE_PATH}")
    if not SOURCE_METADATA_PATH.exists():
        raise FileNotFoundError(f"Glorp UI metadata not found: {SOURCE_METADATA_PATH}")
    if not SOURCE_TYPES_PATH.exists():
        raise FileNotFoundError(f"Glorp UI extracted location types not found: {SOURCE_TYPES_PATH}")

    metadata = json.loads(SOURCE_METADATA_PATH.read_text(encoding="utf-8-sig"))
    if metadata.get("id") != "glorp.ui":
        raise RuntimeError(
            f"Expected Glorp UI metadata id 'glorp.ui', found {metadata.get('id')!r}."
        )

    dependency_ids = {
        relationship.get("id")
        for relationship in metadata.get("relationships", [])
        if relationship.get("rel_type") == "dependency"
    }
    if "romaimperator.construction_manager" not in dependency_ids:
        raise RuntimeError(
            "Glorp UI no longer declares Construction Manager as a dependency; "
            "re-audit the built-in SOL location window before regenerating."
        )

    return str(metadata.get("version", "unknown"))


def strip_trailing_whitespace(text: str) -> str:
    newline = "\n" if text.endswith("\n") else ""
    return "\n".join(line.rstrip(" \t") for line in text.splitlines()) + newline


def _remove_regex(text: str, pattern: re.Pattern[str], expected: int, label: str) -> str:
    text, count = pattern.subn("", text)
    if count != expected:
        raise RuntimeError(f"Expected to remove {expected} {label} block(s), found {count}.")
    return text


def _remove_lines_containing(text: str, needle: str, expected: int, label: str) -> str:
    lines = text.splitlines(keepends=True)
    count = sum(needle in line for line in lines)
    if count != expected:
        raise RuntimeError(f"Expected to remove {expected} {label} line(s), found {count}.")
    return "".join(line for line in lines if needle not in line)


def generate_location_window(glorp_version: str) -> str:
    text = SOURCE_PATH.read_text(encoding="utf-8-sig")

    missing_markers = [marker for marker in EXTERNAL_CM_MARKERS if marker not in text]
    if missing_markers:
        raise RuntimeError(
            "Glorp UI location window no longer contains the audited Construction Manager "
            f"hooks: {missing_markers}"
        )

    zoom_count = text.count(GLORP_ZOOM_BUTTON)
    if zoom_count != 1:
        raise RuntimeError(f"Expected one Glorp zoom button use, found {zoom_count}.")
    text = text.replace(GLORP_ZOOM_BUTTON, SOL_ZOOM_BUTTON, 1)

    text = _remove_regex(text, CM_TOWN_HOVER_RE, 3, "CM town-rights hover")
    text = _remove_regex(text, CM_RGO_WIDGETS_RE, 1, "CM RGO widget")

    visibility_count = text.count(CM_AUTO_EXPAND_VISIBILITY)
    if visibility_count != 1:
        raise RuntimeError(
            f"Expected one CM-aware auto-expand visibility expression, found {visibility_count}."
        )
    text = text.replace(
        CM_AUTO_EXPAND_VISIBILITY,
        VANILLA_AUTO_EXPAND_VISIBILITY,
        1,
    )

    icon_count = text.count(CM_AUTO_EXPAND_ICON)
    if icon_count != 1:
        raise RuntimeError(f"Expected one CM auto-expand status icon, found {icon_count}.")
    text = text.replace(CM_AUTO_EXPAND_ICON, "", 1)

    text = _remove_lines_containing(
        text,
        "cm_check_for_auto_expand_when_upgrading_building",
        3,
        "CM upgrade action",
    )
    text = _remove_lines_containing(
        text,
        "GetMapMode('cm_best_town_right').SetMapMode",
        3,
        "CM town-rights action",
    )

    income_count = text.count(GLORP_INCOME)
    if income_count != 1:
        raise RuntimeError(
            f"Expected exactly one Glorp UI income anchor, found {income_count}: {GLORP_INCOME}"
        )
    text = text.replace(GLORP_INCOME, SOL_INCOME, 1)

    anchor_matches = list(BUTTON_ANCHOR_RE.finditer(text))
    if len(anchor_matches) != 1:
        raise RuntimeError(
            "Expected exactly one SOL button insertion anchor in the Glorp UI demography row, "
            f"found {len(anchor_matches)}."
        )
    insert_at = anchor_matches[0].start()
    text = text[:insert_at] + SOL_BUTTON + text[insert_at:]
    text = strip_trailing_whitespace(text)

    forbidden_runtime_refs = {
        "Glorp zoom type": r"\bzoom_to_button\s*=",
        "Glorp scripted GUI": r"GetScriptedGui\('glorpui_",
        "Construction Manager scripted GUI": r"GetScriptedGui\('cm_",
        "Construction Manager map mode": r"(?:GetMapMode|PushMapModeOverride)\('cm_",
        "Construction Manager GUI type": r"(?m)^\s*cm_[A-Za-z0-9_]+\s*=\s*\{",
    }
    unresolved = [
        label
        for label, pattern in forbidden_runtime_refs.items()
        if re.search(pattern, text)
    ]
    if unresolved:
        raise RuntimeError(f"External runtime references remain in built-in window: {unresolved}")

    return AUTOGENERATED_HEADER + f"# Glorp UI reference version: {glorp_version}\n" + text


def generate_location_types(glorp_version: str) -> str:
    text = strip_trailing_whitespace(SOURCE_TYPES_PATH.read_text(encoding="utf-8-sig"))
    if re.search(r"\b(?:glorpui|cm_)[A-Za-z0-9_]*\b", text, re.IGNORECASE):
        raise RuntimeError("Extracted location-window type file contains external mod references.")
    return (
        AUTOGENERATED_TYPES_HEADER
        + f"# Glorp UI reference version: {glorp_version}\n"
        + text
    )


def generate_outputs() -> dict[Path, str]:
    glorp_version = verify_glorp_reference()
    return {
        TARGET_PATH: generate_location_window(glorp_version),
        TARGET_TYPES_PATH: generate_location_types(glorp_version),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Return non-zero if stable SOL's location window is out of date.",
    )
    args = parser.parse_args()

    generated_outputs = generate_outputs()

    if args.check:
        failed = False
        for path, generated in generated_outputs.items():
            if not path.exists():
                print(f"[FAIL] Missing generated target: {path.relative_to(REPO_ROOT)}")
                failed = True
                continue
            current = path.read_text(encoding="utf-8-sig")
            if current != generated:
                print(f"[FAIL] Out of date: {path.relative_to(REPO_ROOT)}")
                failed = True
                continue
            print(f"[OK] Up to date: {path.relative_to(REPO_ROOT)}")
        if failed:
            print(
                "       Run: $env:PYTHONUTF8='1'; & $env:EU5_PYTHON "
                "scripts/sync_location_window.py"
            )
            return 1
        return 0

    for path, generated in generated_outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated, encoding="utf-8")
        print(f"[OK] Generated {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
